"""PostgreSQL mappings owned by the Checking bounded context."""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import Boolean, CheckConstraint, DateTime, ForeignKey, Index, Integer, Numeric, SmallInteger, String, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import ENUM, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.models import Base, IdMixin, uuid_type

clock = text("clock_timestamp()")
run_status = ENUM("pending", "running", "completed", "completed_with_review_required", "failed_retryable", "failed_terminal", name="checking_run_status", create_type=False)
result_status = ENUM("correct", "incorrect", "partially_correct", "unclear", "insufficient_rubric", "manual_required", name="checking_result_status", create_type=False)
checker_type = ENUM("exact", "multiple_choice", "numeric", "structured_expression", "llm_rubric", "manual_required", name="checking_checker_type", create_type=False)
finding_type = ENUM("rubric", "typical_error", "skill", "general", name="checking_finding_type", create_type=False)
finding_severity = ENUM("info", "minor", "major", "critical", name="checking_finding_severity", create_type=False)
event_type = ENUM("run_created", "run_transition", "result_recorded", "model_attempt", name="checking_event_type", create_type=False)
model_status = ENUM("running", "succeeded", "failed", "invalid", name="checking_model_status", create_type=False)


class CheckRun(IdMixin, Base):
    __tablename__ = "check_runs"
    __table_args__ = (
        UniqueConstraint("submission_id", "request_key", name="uq_check_runs_submission_request"), UniqueConstraint("submission_id", "attempt_no", name="uq_check_runs_submission_attempt"),
        CheckConstraint("request_key = btrim(request_key) AND char_length(request_key) BETWEEN 1 AND 128", name="ck_check_runs_request_key"), CheckConstraint("request_hash ~ '^[0-9a-f]{64}$'", name="ck_check_runs_request_hash"), CheckConstraint("input_fingerprint ~ '^[0-9a-f]{64}$'", name="ck_check_runs_fingerprint"),
        CheckConstraint("handoff_version > 0 AND attempt_no > 0 AND retry_count >= 0 AND row_version > 0", name="ck_check_runs_positive_values"),
        CheckConstraint("snapshot_schema_version = btrim(snapshot_schema_version) AND char_length(snapshot_schema_version) BETWEEN 1 AND 64 AND routing_version = btrim(routing_version) AND char_length(routing_version) BETWEEN 1 AND 64 AND checker_set_version = btrim(checker_set_version) AND char_length(checker_set_version) BETWEEN 1 AND 64 AND threshold_policy_version = btrim(threshold_policy_version) AND char_length(threshold_policy_version) BETWEEN 1 AND 64 AND prompt_model_policy_version = btrim(prompt_model_policy_version) AND char_length(prompt_model_policy_version) BETWEEN 1 AND 64", name="ck_check_runs_versions"),
        CheckConstraint("supersedes_run_id IS NULL OR supersedes_run_id <> id", name="ck_check_runs_not_self_supersede"),
        CheckConstraint("(status='pending' AND started_at IS NULL AND finished_at IS NULL AND failure_code IS NULL) OR (status='running' AND started_at IS NOT NULL AND finished_at IS NULL AND failure_code IS NULL) OR (status IN ('completed','completed_with_review_required') AND started_at IS NOT NULL AND finished_at IS NOT NULL AND failure_code IS NULL) OR (status='failed_retryable' AND started_at IS NOT NULL AND finished_at IS NOT NULL AND failure_code IS NOT NULL) OR (status='failed_terminal' AND started_at IS NOT NULL AND finished_at IS NOT NULL AND failure_code IS NOT NULL)", name="ck_check_runs_status_timestamps"),
        CheckConstraint("finished_at IS NULL OR finished_at >= started_at", name="ck_check_runs_finished_order"), CheckConstraint("heartbeat_at IS NULL OR (started_at IS NOT NULL AND heartbeat_at >= started_at)", name="ck_check_runs_heartbeat_order"), CheckConstraint("failure_code IS NULL OR (failure_code=btrim(failure_code) AND char_length(failure_code) BETWEEN 1 AND 64)", name="ck_check_runs_failure_code"), CheckConstraint("failure_detail IS NULL OR char_length(failure_detail)<=2000", name="ck_check_runs_failure_detail"),
        Index("uq_check_runs_one_active", "submission_id", unique=True, postgresql_where=text("status IN ('pending','running')")), Index("ix_check_runs_history", "submission_id", text("requested_at DESC"), text("id DESC")), Index("ix_check_runs_active", "submission_id", "status"), Index("ix_check_runs_worker", "status", "requested_at", "id"), Index("ix_check_runs_supersedes", "supersedes_run_id"),)
    submission_id: Mapped[UUID] = mapped_column(ForeignKey("student_submissions.id", ondelete="RESTRICT", onupdate="RESTRICT", name="fk_check_runs_submission")); request_key: Mapped[str] = mapped_column(String(128)); request_hash: Mapped[str] = mapped_column(String(64)); handoff_version: Mapped[int] = mapped_column(SmallInteger); input_snapshot: Mapped[object] = mapped_column(JSONB); input_fingerprint: Mapped[str] = mapped_column(String(64))
    snapshot_schema_version: Mapped[str] = mapped_column(String(64)); routing_version: Mapped[str] = mapped_column(String(64)); checker_set_version: Mapped[str] = mapped_column(String(64)); threshold_policy_version: Mapped[str] = mapped_column(String(64)); prompt_model_policy_version: Mapped[str] = mapped_column(String(64)); status: Mapped[str] = mapped_column(run_status, server_default=text("'pending'::checking_run_status")); attempt_no: Mapped[int] = mapped_column(Integer); retry_count: Mapped[int] = mapped_column(Integer, server_default="0"); requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=clock); started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True)); finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True)); heartbeat_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True)); failure_code: Mapped[str | None] = mapped_column(String(64)); failure_detail: Mapped[str | None] = mapped_column(Text); supersedes_run_id: Mapped[UUID | None] = mapped_column(ForeignKey("check_runs.id", ondelete="RESTRICT", onupdate="RESTRICT", name="fk_check_runs_supersedes")); row_version: Mapped[int] = mapped_column(Integer, server_default="1")


class CheckResult(IdMixin, Base):
    __tablename__="check_results"; __table_args__=(UniqueConstraint("check_run_id","assessment_item_id",name="uq_check_results_run_item"), CheckConstraint("max_score>0 AND (score_suggested IS NULL OR score_suggested BETWEEN 0 AND max_score)",name="ck_check_results_score_range"), CheckConstraint("confidence BETWEEN 0 AND 1",name="ck_check_results_confidence"), CheckConstraint("(result_status='correct' AND score_suggested=max_score) OR (result_status='incorrect' AND score_suggested=0) OR (result_status='partially_correct' AND score_suggested>0 AND score_suggested<max_score) OR (result_status IN ('unclear','insufficient_rubric','manual_required') AND score_suggested IS NULL)",name="ck_check_results_status_score"), CheckConstraint("(needs_human_review AND review_reason IS NOT NULL AND char_length(btrim(review_reason)) BETWEEN 1 AND 500) OR (NOT needs_human_review AND review_reason IS NULL)",name="ck_check_results_review"), CheckConstraint("char_length(summary) BETWEEN 1 AND 1000 AND char_length(checker_version) BETWEEN 1 AND 64 AND char_length(schema_version) BETWEEN 1 AND 64",name="ck_check_results_text"), CheckConstraint("reason_code=btrim(reason_code) AND char_length(reason_code) BETWEEN 1 AND 64",name="ck_check_results_reason_code"), CheckConstraint("confidence_policy_version=btrim(confidence_policy_version) AND char_length(confidence_policy_version) BETWEEN 1 AND 64",name="ck_check_results_confidence_policy"), CheckConstraint("jsonb_typeof(confidence_details)='object' AND confidence_details->>'effective'=to_char(confidence,'FM0.0000')",name="ck_check_results_confidence_details"), Index("ix_check_results_item_created","assessment_item_id",text("created_at DESC")), Index("ix_check_results_task_version","task_version_id"), Index("ix_check_results_review","needs_human_review","created_at"))
    check_run_id: Mapped[UUID]=mapped_column(ForeignKey("check_runs.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_check_results_run")); assessment_item_id: Mapped[UUID]=mapped_column(ForeignKey("assessment_items.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_check_results_item")); task_version_id: Mapped[UUID]=mapped_column(ForeignKey("task_versions.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_check_results_version")); checker_type: Mapped[str]=mapped_column(checker_type); checker_version: Mapped[str]=mapped_column(String(64)); schema_version: Mapped[str]=mapped_column(String(64)); result_status: Mapped[str]=mapped_column(result_status); reason_code: Mapped[str]=mapped_column(String(64)); confidence_policy_version: Mapped[str]=mapped_column(String(64)); confidence_details: Mapped[object]=mapped_column(JSONB); score_suggested: Mapped[Decimal|None]=mapped_column(Numeric(10,2)); max_score: Mapped[Decimal]=mapped_column(Numeric(10,2)); confidence: Mapped[Decimal]=mapped_column(Numeric(5,4)); summary: Mapped[str]=mapped_column(String(1000)); student_feedback_draft: Mapped[str|None]=mapped_column(String(4000)); teacher_summary: Mapped[str|None]=mapped_column(String(2000)); needs_human_review: Mapped[bool]=mapped_column(Boolean); review_reason: Mapped[str|None]=mapped_column(String(500)); model_limitations: Mapped[str|None]=mapped_column(String(2000)); validated_result: Mapped[object]=mapped_column(JSONB); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=clock)


class CheckFinding(IdMixin, Base):
    __tablename__="check_findings"; __table_args__=(CheckConstraint("confidence BETWEEN 0 AND 1",name="ck_check_findings_confidence"), CheckConstraint("rubric_item_id IS NOT NULL OR typical_error_id IS NOT NULL OR skill_id IS NOT NULL OR finding_type='general'",name="ck_check_findings_source"), CheckConstraint("snapshot_code IS NULL OR char_length(snapshot_code)<=128",name="ck_check_findings_code"), CheckConstraint("snapshot_title IS NULL OR char_length(snapshot_title)<=500",name="ck_check_findings_title"), CheckConstraint("snapshot_criterion IS NULL OR char_length(snapshot_criterion)<=2000",name="ck_check_findings_criterion"), Index("ix_check_findings_result","check_result_id"), Index("ix_check_findings_provenance","rubric_item_id","typical_error_id","skill_id"))
    check_result_id: Mapped[UUID]=mapped_column(ForeignKey("check_results.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_check_findings_result")); finding_type: Mapped[str]=mapped_column(finding_type); rubric_item_id: Mapped[UUID|None]=mapped_column(uuid_type); typical_error_id: Mapped[UUID|None]=mapped_column(uuid_type); skill_id: Mapped[UUID|None]=mapped_column(uuid_type); snapshot_code: Mapped[str|None]=mapped_column(String(128)); snapshot_title: Mapped[str|None]=mapped_column(String(500)); snapshot_criterion: Mapped[str|None]=mapped_column(String(2000)); severity: Mapped[str]=mapped_column(finding_severity); confidence: Mapped[Decimal]=mapped_column(Numeric(5,4)); evidence: Mapped[object]=mapped_column(JSONB); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=clock)


class CheckerEvent(IdMixin, Base):
    __tablename__="checker_events"; __table_args__=(CheckConstraint("(event_type='run_transition' AND from_status IS NOT NULL AND to_status IS NOT NULL AND from_status<>to_status) OR (event_type<>'run_transition' AND from_status IS NULL AND to_status IS NULL)",name="ck_checker_events_transition"), CheckConstraint("reason_code IS NULL OR char_length(reason_code) BETWEEN 1 AND 64",name="ck_checker_events_reason"), Index("ix_checker_events_run_time","check_run_id","occurred_at","id"), Index("ix_checker_events_type_time","event_type","occurred_at"))
    check_run_id: Mapped[UUID]=mapped_column(ForeignKey("check_runs.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_checker_events_run")); check_result_id: Mapped[UUID|None]=mapped_column(ForeignKey("check_results.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_checker_events_result")); assessment_item_id: Mapped[UUID|None]=mapped_column(ForeignKey("assessment_items.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_checker_events_item")); event_type: Mapped[str]=mapped_column(event_type); from_status: Mapped[str|None]=mapped_column(run_status); to_status: Mapped[str|None]=mapped_column(run_status); reason_code: Mapped[str|None]=mapped_column(String(64)); details: Mapped[object]=mapped_column(JSONB,server_default=text("'{}'::jsonb")); occurred_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=clock)


class PromptVersion(IdMixin, Base):
    __tablename__="prompt_versions"; __table_args__=(UniqueConstraint("name","semantic_version","template_hash",name="uq_prompt_versions_identity"), CheckConstraint("name=btrim(name) AND char_length(name) BETWEEN 1 AND 120 AND semantic_version=btrim(semantic_version) AND char_length(semantic_version) BETWEEN 1 AND 64 AND output_schema_version=btrim(output_schema_version) AND char_length(output_schema_version) BETWEEN 1 AND 64",name="ck_prompt_versions_names"), CheckConstraint("template_hash ~ '^[0-9a-f]{64}$'",name="ck_prompt_versions_hash"), CheckConstraint("retired_at IS NULL OR retired_at>=created_at",name="ck_prompt_versions_retirement"))
    name: Mapped[str]=mapped_column(String(120)); semantic_version: Mapped[str]=mapped_column(String(64)); template_hash: Mapped[str]=mapped_column(String(64)); output_schema_version: Mapped[str]=mapped_column(String(64)); template_text: Mapped[str]=mapped_column(Text); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=clock); retired_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))


class ModelRun(IdMixin, Base):
    __tablename__="model_runs"; __table_args__=(UniqueConstraint("check_run_id","assessment_item_id","attempt_no",name="uq_model_runs_attempt"), CheckConstraint("attempt_no>0 AND timeout_ms>=0 AND (latency_ms IS NULL OR latency_ms>=0) AND input_tokens>=0 AND output_tokens>=0 AND cached_tokens>=0",name="ck_model_runs_numbers"), CheckConstraint("request_fingerprint ~ '^[0-9a-f]{64}$'",name="ck_model_runs_fingerprint"), CheckConstraint("provider_id=btrim(provider_id) AND char_length(provider_id) BETWEEN 1 AND 128 AND model_id=btrim(model_id) AND char_length(model_id) BETWEEN 1 AND 128",name="ck_model_runs_ids"), CheckConstraint("(status='running' AND finished_at IS NULL AND error_code IS NULL) OR (status='succeeded' AND finished_at IS NOT NULL AND validated_output IS NOT NULL AND error_code IS NULL) OR (status IN ('failed','invalid') AND finished_at IS NOT NULL AND error_code IS NOT NULL)",name="ck_model_runs_status"), CheckConstraint("finished_at IS NULL OR finished_at>=started_at",name="ck_model_runs_time"), Index("ix_model_runs_status","status","started_at"), Index("ix_model_runs_provider_request","provider_request_id"))
    check_run_id: Mapped[UUID]=mapped_column(ForeignKey("check_runs.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_model_runs_run")); assessment_item_id: Mapped[UUID]=mapped_column(ForeignKey("assessment_items.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_model_runs_item")); prompt_version_id: Mapped[UUID]=mapped_column(ForeignKey("prompt_versions.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_model_runs_prompt")); check_result_id: Mapped[UUID|None]=mapped_column(ForeignKey("check_results.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_model_runs_result")); provider_id: Mapped[str]=mapped_column(String(128)); model_id: Mapped[str]=mapped_column(String(128)); settings_snapshot: Mapped[object]=mapped_column(JSONB); request_fingerprint: Mapped[str]=mapped_column(String(64)); provider_request_id: Mapped[str|None]=mapped_column(String(256)); status: Mapped[str]=mapped_column(model_status,server_default=text("'running'::checking_model_status")); error_code: Mapped[str|None]=mapped_column(String(64)); error_detail: Mapped[str|None]=mapped_column(String(2000)); attempt_no: Mapped[int]=mapped_column(Integer); timeout_ms: Mapped[int]=mapped_column(Integer); latency_ms: Mapped[int|None]=mapped_column(Integer); raw_output: Mapped[str|None]=mapped_column(Text); validated_output: Mapped[object|None]=mapped_column(JSONB); validation_errors: Mapped[object|None]=mapped_column(JSONB); input_tokens: Mapped[int]=mapped_column(Integer,server_default="0"); output_tokens: Mapped[int]=mapped_column(Integer,server_default="0"); cached_tokens: Mapped[int]=mapped_column(Integer,server_default="0"); started_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=clock); finished_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))


class CostEvent(IdMixin, Base):
    __tablename__="cost_events"; __table_args__=(UniqueConstraint("model_run_id","pricing_version",name="uq_cost_events_model_pricing"), CheckConstraint("currency ~ '^[A-Z]{3}$'",name="ck_cost_events_currency"), CheckConstraint("input_tokens>=0 AND output_tokens>=0 AND cached_tokens>=0 AND amount>=0",name="ck_cost_events_values"), CheckConstraint("pricing_version=btrim(pricing_version) AND char_length(pricing_version) BETWEEN 1 AND 64 AND pricing_source=btrim(pricing_source) AND char_length(pricing_source) BETWEEN 1 AND 128",name="ck_cost_events_pricing"))
    model_run_id: Mapped[UUID]=mapped_column(ForeignKey("model_runs.id",ondelete="RESTRICT",onupdate="RESTRICT",name="fk_cost_events_model_run")); currency: Mapped[str]=mapped_column(String(3)); input_tokens: Mapped[int]=mapped_column(Integer); output_tokens: Mapped[int]=mapped_column(Integer); cached_tokens: Mapped[int]=mapped_column(Integer); amount: Mapped[Decimal]=mapped_column(Numeric(18,8)); pricing_version: Mapped[str]=mapped_column(String(64)); pricing_source: Mapped[str]=mapped_column(String(128)); occurred_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=clock)
