"""Personalized remediation planning and delivery.
Revision ID: 20260907_03
Revises: 20260907_02
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20260907_03"; down_revision="20260907_02"; branch_labels=None; depends_on=None

def upgrade():
 u=postgresql.UUID(as_uuid=True); ts=sa.DateTime(timezone=True)
 op.create_table("remediation_plans",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("owner_user_id",u,nullable=False),sa.Column("student_id",u,nullable=False),sa.Column("class_group_id",u,nullable=False),sa.Column("source_assignment_id",u,nullable=False),sa.Column("source_assignment_participant_id",u,nullable=False),sa.Column("source_submission_id",u,nullable=False),sa.Column("source_check_run_id",u,nullable=False),sa.Column("status",sa.String(16),server_default="draft",nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("instructions",sa.Text),sa.Column("due_at",ts),sa.Column("review_acknowledged_at",ts),sa.Column("creation_key",sa.String(128),nullable=False),sa.Column("creation_fingerprint",sa.CHAR(64),nullable=False),sa.Column("created_at",ts,server_default=sa.text("clock_timestamp()"),nullable=False),sa.Column("updated_at",ts,server_default=sa.text("clock_timestamp()"),nullable=False),sa.Column("assigned_at",ts),sa.Column("cancelled_at",ts),
  sa.ForeignKeyConstraint(["owner_user_id"],["users.id"],ondelete="RESTRICT",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["student_id"],["students.id"],ondelete="RESTRICT",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["class_group_id"],["class_groups.id"],ondelete="RESTRICT",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["source_assignment_id"],["assignments.id"],ondelete="RESTRICT",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["source_assignment_participant_id"],["assignment_participants.id"],ondelete="RESTRICT",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["source_submission_id"],["student_submissions.id"],ondelete="RESTRICT",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["source_check_run_id"],["check_runs.id"],ondelete="RESTRICT",onupdate="RESTRICT"),sa.UniqueConstraint("owner_user_id","creation_key",name="uq_remediation_plans_owner_creation_key"),sa.CheckConstraint("status IN ('draft','assigned','cancelled')"),sa.CheckConstraint("title=btrim(title) AND char_length(title) BETWEEN 1 AND 200"),sa.CheckConstraint("instructions IS NULL OR char_length(instructions)<=4000"),sa.CheckConstraint("creation_fingerprint ~ '^[0-9a-f]{64}$'"),sa.CheckConstraint("(status='draft' AND assigned_at IS NULL AND cancelled_at IS NULL) OR (status='assigned' AND assigned_at IS NOT NULL AND cancelled_at IS NULL) OR (status='cancelled' AND cancelled_at IS NOT NULL)"))
 op.create_index("ix_remediation_plans_owner_class_student_created","remediation_plans",["owner_user_id","class_group_id","student_id",sa.text("created_at DESC"),"id"]); op.create_index("ix_remediation_plans_student_status_assigned","remediation_plans",["student_id","status",sa.text("assigned_at DESC"),"id"]); op.create_index("ix_remediation_plans_source_run_student","remediation_plans",["source_check_run_id","student_id"]); op.create_index("ix_remediation_plans_source_assignment_student","remediation_plans",["source_assignment_id","student_id"])
 op.create_table("remediation_plan_signals",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("remediation_plan_id",u,sa.ForeignKey("remediation_plans.id",ondelete="CASCADE"),nullable=False),sa.Column("check_finding_id",u,sa.ForeignKey("check_findings.id",ondelete="RESTRICT",onupdate="RESTRICT"),nullable=False),sa.Column("created_at",ts,server_default=sa.text("clock_timestamp()"),nullable=False),sa.UniqueConstraint("remediation_plan_id","check_finding_id"))
 op.create_table("remediation_plan_items",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("remediation_plan_id",u,sa.ForeignKey("remediation_plans.id",ondelete="CASCADE"),nullable=False),sa.Column("position",sa.Integer,nullable=False),sa.Column("task_version_id",u,sa.ForeignKey("task_versions.id",ondelete="RESTRICT",onupdate="RESTRICT"),nullable=False),sa.Column("selection_source",sa.String(16),nullable=False),sa.Column("created_at",ts,server_default=sa.text("clock_timestamp()"),nullable=False),sa.CheckConstraint("position>=0"),sa.CheckConstraint("selection_source IN ('suggested','manual')"),sa.UniqueConstraint("remediation_plan_id","position"),sa.UniqueConstraint("remediation_plan_id","task_version_id"))
 op.create_table("remediation_events",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("remediation_plan_id",u,sa.ForeignKey("remediation_plans.id",ondelete="RESTRICT"),nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("actor_user_id",u,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("occurred_at",ts,server_default=sa.text("clock_timestamp()"),nullable=False),sa.Column("details",postgresql.JSONB,server_default=sa.text("'{}'::jsonb"),nullable=False),sa.CheckConstraint("event_type IN ('plan_created','plan_updated','plan_assigned','plan_cancelled')")); op.create_index("ix_remediation_events_plan_time","remediation_events",["remediation_plan_id","occurred_at","id"])
def downgrade(): raise RuntimeError("Forward-only migration")
