"""Typed methodology foundation. Revision ID: 20260810_02; Revises: 20260810_01."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20260810_02"; down_revision="20260810_01"; branch_labels=depends_on=None

def upgrade():
    op.add_column("accepted_answers",sa.Column("value_kind",sa.String(32),nullable=False,server_default="legacy_untyped"))
    for n,t in (("canonical_text",sa.Text()),("canonical_decimal",sa.Numeric()),("absolute_tolerance",sa.Numeric()),("relative_tolerance",sa.Numeric()),("unit_code",sa.String(64)),("normalization_policy_code",sa.String(64)),("normalization_policy_version",sa.Integer())): op.add_column("accepted_answers",sa.Column(n,t,nullable=True))
    op.create_unique_constraint("uq_accepted_answers_id_version","accepted_answers",["id","task_version_id"])
    op.create_check_constraint("ck_accepted_answers_typed_shape","accepted_answers",'''canonical_decimal NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric) AND absolute_tolerance NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric) AND relative_tolerance NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric) AND value_kind IN ('legacy_untyped','text','decimal','expression','choice_set') AND (absolute_tolerance IS NULL OR absolute_tolerance>=0) AND (relative_tolerance IS NULL OR relative_tolerance>=0) AND ((normalization_policy_code IS NULL)=(normalization_policy_version IS NULL)) AND (unit_code IS NULL OR unit_code ~ '^[A-Za-z0-9][A-Za-z0-9_.:/-]{0,63}$') AND ((value_kind='legacy_untyped' AND canonical_text IS NULL AND canonical_decimal IS NULL AND absolute_tolerance IS NULL AND relative_tolerance IS NULL AND unit_code IS NULL AND normalization_policy_code IS NULL) OR (value_kind='text' AND canonical_text IS NOT NULL AND canonical_decimal IS NULL AND absolute_tolerance IS NULL AND relative_tolerance IS NULL AND normalization_policy_code='exact_text_v1' AND normalization_policy_version=1) OR (value_kind='expression' AND canonical_text IS NOT NULL AND canonical_decimal IS NULL AND absolute_tolerance IS NULL AND relative_tolerance IS NULL AND normalization_policy_code='expression_identity_v1' AND normalization_policy_version=1) OR (value_kind='decimal' AND canonical_text IS NULL AND canonical_decimal IS NOT NULL AND normalization_policy_code='decimal_v1' AND normalization_policy_version=1) OR (value_kind='choice_set' AND canonical_text IS NULL AND canonical_decimal IS NULL AND absolute_tolerance IS NULL AND relative_tolerance IS NULL AND unit_code IS NULL AND normalization_policy_code IS NULL))''')
    op.create_table("choice_options",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("task_version_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("task_versions.id",ondelete="CASCADE",onupdate="RESTRICT"),nullable=False),sa.Column("option_key",sa.String(64),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("order_index",sa.Integer(),nullable=False),sa.CheckConstraint("option_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$' AND btrim(content)<>'' AND order_index>=0"),sa.UniqueConstraint("task_version_id","option_key",name="uq_choice_options_version_key"),sa.UniqueConstraint("task_version_id","order_index",name="uq_choice_options_version_order"),sa.UniqueConstraint("id","task_version_id",name="uq_choice_options_id_version"))
    op.create_index("ix_choice_options_version_order","choice_options",["task_version_id","order_index"])
    op.create_table("accepted_answer_options",sa.Column("accepted_answer_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("choice_option_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("task_version_id",postgresql.UUID(as_uuid=True),nullable=False),sa.PrimaryKeyConstraint("accepted_answer_id","choice_option_id"),sa.ForeignKeyConstraint(["accepted_answer_id","task_version_id"],["accepted_answers.id","accepted_answers.task_version_id"],ondelete="CASCADE",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["choice_option_id","task_version_id"],["choice_options.id","choice_options.task_version_id"],ondelete="CASCADE",onupdate="RESTRICT"))
    op.create_table("choice_scoring_policies",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("task_version_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("task_versions.id",ondelete="CASCADE",onupdate="RESTRICT"),nullable=False,unique=True),sa.Column("mode",sa.String(32),nullable=False),sa.Column("policy_version",sa.Integer(),nullable=False,server_default="1"),sa.CheckConstraint("mode IN ('all_or_nothing','per_option') AND policy_version=1"),sa.UniqueConstraint("id","task_version_id",name="uq_choice_scoring_policy_id_version"))
    op.create_table("choice_option_rules",sa.Column("policy_id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("choice_option_id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("task_version_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("weight",sa.Numeric(),nullable=False),sa.ForeignKeyConstraint(["policy_id","task_version_id"],["choice_scoring_policies.id","choice_scoring_policies.task_version_id"],ondelete="CASCADE",onupdate="RESTRICT"),sa.ForeignKeyConstraint(["choice_option_id","task_version_id"],["choice_options.id","choice_options.task_version_id"],ondelete="CASCADE",onupdate="RESTRICT"),sa.CheckConstraint("weight NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric)"))
    op.execute("""CREATE FUNCTION methodology_choice_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_TABLE_NAME='accepted_answer_options' AND NOT EXISTS (SELECT 1 FROM accepted_answers a WHERE a.id=NEW.accepted_answer_id AND a.value_kind='choice_set') THEN RAISE EXCEPTION 'options require choice_set answer'; END IF; RETURN NEW; END $$""")
    op.execute("CREATE TRIGGER trg_methodology_choice_guard BEFORE INSERT OR UPDATE ON accepted_answer_options FOR EACH ROW EXECUTE FUNCTION methodology_choice_guard()")
    op.execute("""CREATE FUNCTION methodology_choice_nonempty() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS (SELECT 1 FROM accepted_answers a WHERE a.id=COALESCE(NEW.id,OLD.id) AND a.value_kind='choice_set') AND NOT EXISTS (SELECT 1 FROM accepted_answer_options o WHERE o.accepted_answer_id=COALESCE(NEW.id,OLD.id)) THEN RAISE EXCEPTION 'choice_set cannot be empty'; END IF; RETURN NULL; END $$""")
    op.execute("CREATE CONSTRAINT TRIGGER trg_methodology_choice_nonempty AFTER INSERT OR UPDATE ON accepted_answers DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION methodology_choice_nonempty()")
def downgrade():
    op.execute("DROP TRIGGER trg_methodology_choice_nonempty ON accepted_answers")
    op.execute("DROP FUNCTION methodology_choice_nonempty()")
    op.execute("DROP TRIGGER trg_methodology_choice_guard ON accepted_answer_options")
    op.execute("DROP FUNCTION methodology_choice_guard()")
    for t in ("choice_option_rules","choice_scoring_policies","accepted_answer_options","choice_options"): op.drop_table(t)
    op.drop_constraint("ck_accepted_answers_typed_shape","accepted_answers",type_="check"); op.drop_constraint("uq_accepted_answers_id_version","accepted_answers",type_="unique")
    for n in ("normalization_policy_version","normalization_policy_code","unit_code","relative_tolerance","absolute_tolerance","canonical_decimal","canonical_text","value_kind"): op.drop_column("accepted_answers",n)
