"""Add immutable AI scan-page matching evidence.

Revision ID: 20260915_01
Revises: 20260914_03
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20260915_01"; down_revision="20260914_03"; branch_labels=None; depends_on=None
u=postgresql.UUID(as_uuid=True); now=sa.text("clock_timestamp()")

def upgrade():
    op.create_table("scan_matching_runs", sa.Column("id",u,primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("batch_id",u,sa.ForeignKey("assessment_scan_batches.id",ondelete="RESTRICT"),nullable=False),sa.Column("revision",sa.Integer,nullable=False),sa.Column("requested_by_user_id",u,sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="running"),sa.Column("prompt_name",sa.String(128),nullable=False),sa.Column("prompt_version",sa.String(32),nullable=False),sa.Column("prompt_template_hash",sa.String(64),nullable=False),sa.Column("output_schema_version",sa.String(64),nullable=False),sa.Column("provider_route",sa.String(256),nullable=False),sa.Column("request_context_fingerprint",sa.String(64),nullable=False),sa.Column("assessment_title_snapshot",sa.String(500),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=now),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False,server_default=now),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("failure_code",sa.String(64)),sa.UniqueConstraint("batch_id","revision",name="uq_scan_matching_runs_revision"),sa.CheckConstraint("revision > 0",name="ck_scan_matching_runs_revision"),sa.CheckConstraint("status IN ('running','succeeded','failed_retryable','failed_terminal')",name="ck_scan_matching_runs_status"),sa.CheckConstraint("request_context_fingerprint ~ '^[0-9a-f]{64}$' AND prompt_template_hash ~ '^[0-9a-f]{64}$'",name="ck_scan_matching_runs_hashes"),sa.CheckConstraint("(status='running' AND completed_at IS NULL AND failure_code IS NULL) OR (status='succeeded' AND completed_at IS NOT NULL AND failure_code IS NULL) OR (status IN ('failed_retryable','failed_terminal') AND completed_at IS NOT NULL AND failure_code IS NOT NULL)",name="ck_scan_matching_runs_lifecycle"))
    op.create_table("scan_matching_roster_entries",sa.Column("matching_run_id",u,sa.ForeignKey("scan_matching_runs.id",ondelete="RESTRICT"),primary_key=True),sa.Column("roster_token",sa.String(128),primary_key=True),sa.Column("assignment_participant_id",u,sa.ForeignKey("assignment_participants.id",ondelete="RESTRICT"),nullable=False),sa.Column("display_name_snapshot",sa.String(300),nullable=False),sa.Column("position",sa.Integer,nullable=False),sa.UniqueConstraint("matching_run_id","assignment_participant_id",name="uq_scan_matching_roster_participant"),sa.UniqueConstraint("matching_run_id","position",name="uq_scan_matching_roster_position"))
    op.create_table("scan_matching_page_entries",sa.Column("matching_run_id",u,sa.ForeignKey("scan_matching_runs.id",ondelete="RESTRICT"),primary_key=True),sa.Column("page_token",sa.String(128),primary_key=True),sa.Column("scan_page_id",u,sa.ForeignKey("scan_pages.id",ondelete="RESTRICT"),nullable=False),sa.Column("source_order",sa.Integer,nullable=False),sa.UniqueConstraint("matching_run_id","scan_page_id",name="uq_scan_matching_page"),sa.UniqueConstraint("matching_run_id","source_order",name="uq_scan_matching_source_order"))
    op.create_table("scan_matching_chunks",sa.Column("id",u,primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("matching_run_id",u,sa.ForeignKey("scan_matching_runs.id",ondelete="RESTRICT"),nullable=False),sa.Column("chunk_index",sa.Integer,nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending"),sa.Column("primary_page_tokens",postgresql.JSONB,nullable=False),sa.Column("context_page_tokens",postgresql.JSONB,nullable=False),sa.Column("provider_id",sa.String(128),nullable=False),sa.Column("model_id",sa.String(128),nullable=False),sa.Column("request_fingerprint",sa.String(64)),sa.Column("provider_request_id",sa.String(256)),sa.Column("input_tokens",sa.Integer),sa.Column("output_tokens",sa.Integer),sa.Column("cached_tokens",sa.Integer),sa.Column("cache_write_tokens",sa.Integer),sa.Column("latency_ms",sa.Integer),sa.Column("validated_output",postgresql.JSONB),sa.Column("failure_code",sa.String(64)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=now),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("matching_run_id","chunk_index",name="uq_scan_matching_chunks_index"),sa.CheckConstraint("status IN ('pending','running','succeeded','failed_retryable','failed_terminal')",name="ck_scan_matching_chunks_status"))
    op.create_table("scan_page_match_proposals",sa.Column("id",u,primary_key=True,server_default=sa.text("gen_random_uuid()")),sa.Column("matching_run_id",u,sa.ForeignKey("scan_matching_runs.id",ondelete="RESTRICT"),nullable=False),sa.Column("scan_page_id",u,sa.ForeignKey("scan_pages.id",ondelete="RESTRICT"),nullable=False),sa.Column("disposition",sa.String(16),nullable=False),sa.Column("proposed_assignment_participant_id",u,sa.ForeignKey("assignment_participants.id",ondelete="RESTRICT")),sa.Column("confidence",sa.Numeric(8,7),nullable=False),sa.Column("evidence_code",sa.String(128),nullable=False),sa.Column("evidence_summary",sa.String(4000),nullable=False),sa.Column("proposed_group_token",sa.String(128)),sa.Column("proposed_page_order",sa.Integer),sa.Column("provider_requires_human_review",sa.Boolean,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=now),sa.UniqueConstraint("matching_run_id","scan_page_id",name="uq_scan_page_match_proposal"),sa.CheckConstraint("confidence >= 0 AND confidence <= 1",name="ck_scan_page_match_confidence"),sa.CheckConstraint("(disposition='matched' AND proposed_assignment_participant_id IS NOT NULL) OR (disposition IN ('ambiguous','unmatched') AND proposed_assignment_participant_id IS NULL)",name="ck_scan_page_match_disposition"))
    op.create_table("scan_page_match_candidates",sa.Column("matching_run_id",u,sa.ForeignKey("scan_matching_runs.id",ondelete="RESTRICT"),primary_key=True),sa.Column("scan_page_id",u,sa.ForeignKey("scan_pages.id",ondelete="RESTRICT"),primary_key=True),sa.Column("assignment_participant_id",u,sa.ForeignKey("assignment_participants.id",ondelete="RESTRICT"),primary_key=True),sa.Column("rank",sa.Integer,nullable=False),sa.UniqueConstraint("matching_run_id","scan_page_id","rank",name="uq_scan_page_match_candidate_rank"),sa.CheckConstraint("rank BETWEEN 1 AND 8",name="ck_scan_page_match_candidate_rank"))

def downgrade():
    for name in ("scan_page_match_candidates","scan_page_match_proposals","scan_matching_chunks","scan_matching_page_entries","scan_matching_roster_entries","scan_matching_runs"): op.drop_table(name)
