import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {AcceptancePanel} from "./AcceptancePanel";
import {ApiError,type AuthoringWorkspaceViewV1} from "./api";
import * as api from "./api";
const workspace=(status:"passed"|"warnings"|"blocked"="passed"):AuthoringWorkspaceViewV1=>({schema_version:"authoring_workspace_view.v1",session:{id:"s",owner:"o",lifecycle_status:"ready",created_at:"2026-01-01T00:00:00Z"},generation:{generated_draft_available:true,generator_route:null,generator_attempt_status:"succeeded"},solver:{solver_status:"solvable",validation_status:"validated",semantic_result:null},review:{current_revision:2,revision_count:2,reviewer_state:"reviewing",latest_changes_summary:{}},quality:{quality_status:status,blocking_findings:status==="blocked"?[{code:"bad",message:"Блокирует"}]:[],warnings:status==="warnings"?[{code:"warn",message:"Проверьте"}]:[],override_state:{overridden:false,reason:null,warning_codes:[]}},acceptance:{accepted_revision:null,promoted_task_reference:null},diagnostics:{attempt_count:1,total_cost_by_currency:[],provider_usage_summary:[]}});
const history={schema_version:"authoring_review_history.v1" as const,session_id:"s",current_revision:2,accepted_revision_id:null,revisions:[{id:"r",revision_number:2,snapshot:{} as any,created_at:"2026-01-01T00:00:00Z",actor_id:"reviewer",change_summary:{changed_fields:["title"]}}]};
afterEach(()=>{cleanup();vi.restoreAllMocks()});
function setup(status:"passed"|"warnings"|"blocked"="passed",onAccepted=vi.fn()){vi.spyOn(api,"getAuthoringReviewHistory").mockResolvedValue(history);render(<AcceptancePanel sessionId="s" workspace={workspace(status)} onAccepted={onAccepted}/>);return onAccepted}
describe("AcceptancePanel",()=>{
 it("renders the accept button and current revision",async()=>{setup();expect(screen.getByRole("button",{name:"Принять в Content Bank"})).toBeTruthy();expect(await screen.findByText("reviewer")).toBeTruthy();expect(screen.getByText("Название")).toBeTruthy()});
 it("disables acceptance for blocked quality",()=>{setup("blocked");expect((screen.getByRole("button",{name:"Принять в Content Bank"}) as HTMLButtonElement).disabled).toBe(true)});
 it("requires warning confirmation and a bounded reason",async()=>{setup("warnings");const button=screen.getByRole("button",{name:"Принять в Content Bank"});expect((button as HTMLButtonElement).disabled).toBe(true);await userEvent.click(screen.getByRole("checkbox"));expect((button as HTMLButtonElement).disabled).toBe(true);await userEvent.type(screen.getByLabelText("Причина исключения"),"Проверено вручную");expect((button as HTMLButtonElement).disabled).toBe(false)});
 it("accepts after confirmation, sends only control fields, shows result and refreshes",async()=>{const accepted=vi.fn();const call=vi.spyOn(api,"acceptAuthoringSession").mockResolvedValue({session_id:"s",task_id:"task-1",task_version_id:"version-1",created_at:"2026-01-01T00:00:00Z",lifecycle_status:"draft",already_existing:false});setup("warnings",accepted);await userEvent.click(screen.getByRole("checkbox"));await userEvent.type(screen.getByLabelText("Причина исключения"),"Проверено");await userEvent.type(screen.getByRole("textbox",{name:/Примечание к приёмке/}),"Готово");await userEvent.click(screen.getByRole("button",{name:"Принять в Content Bank"}));expect(screen.getByRole("dialog").textContent).toContain("Выбранная редакция2");await userEvent.click(screen.getByRole("button",{name:"Подтвердить приёмку"}));expect(await screen.findByText("task-1")).toBeTruthy();expect(screen.getByText("version-1")).toBeTruthy();expect(screen.getByText("draft")).toBeTruthy();expect(call).toHaveBeenCalledWith("s",{acceptance_note:"Готово",confirm_questionable:true,warning_override_reason:"Проверено"});expect(Object.keys(call.mock.calls[0][1])).toEqual(["acceptance_note","confirm_questionable","warning_override_reason"]);expect(accepted).toHaveBeenCalled()});
 it.each([["authoring_quality_blocked","качество заблокировано"],["authoring_review_already_accepted","уже принята"],["authoring_review_version_conflict","Редакция изменилась"],["authoring_session_not_found","не найдена"],["validation_error","Проверьте заполненные поля"]])("shows %s errors",async(code,message)=>{vi.spyOn(api,"acceptAuthoringSession").mockRejectedValue(new ApiError(code.includes("not_found")?404:code==="validation_error"?422:409,code,"error"));setup();await userEvent.click(screen.getByRole("button",{name:"Принять в Content Bank"}));await userEvent.click(screen.getByRole("button",{name:"Подтвердить приёмку"}));expect((await screen.findByRole("alert")).textContent).toContain(message)});
});
