import {useEffect,useState} from "react";
import {acceptAuthoringSession,ApiError,getAuthoringReviewHistory,type AuthoringAcceptanceResponse,type AuthoringReviewRevision,type AuthoringWorkspaceViewV1} from "./api";

const fieldLabels:Record<string,string>={title:"Название",statement:"Условие",choices:"Варианты ответа",choice_options:"Варианты ответа",expected_answer:"Ожидаемый ответ",solution:"Решение",hints:"Подсказки"};
const errorMessages:Record<string,string>={authoring_quality_blocked:"Приёмка невозможна: качество заблокировано.",authoring_quality_warning_override_required:"Подтвердите предупреждения и укажите причину исключения.",authoring_review_already_accepted:"Эта авторская сессия уже принята.",authoring_review_not_accepting:"Эта авторская сессия уже принята или больше недоступна для приёмки.",authoring_review_version_conflict:"Редакция изменилась. Рабочее пространство обновлено.",authoring_review_revision_not_found:"Выбранная редакция не найдена.",authoring_session_not_found:"Авторская сессия не найдена.",validation_error:"Проверьте заполненные поля."};
function Findings({items,empty}:{items:{code:string;message:string}[];empty:string}){return items.length?<ul className="workspace-findings">{items.map((item,index)=><li key={`${item.code}-${index}`}><strong>{item.code}</strong>: {item.message}</li>)}</ul>:<p>{empty}</p>}
function changedFields(revision?:AuthoringReviewRevision){const value=revision?.change_summary.changed_fields;return Array.isArray(value)?value.filter((field):field is string=>typeof field==="string"&&field in fieldLabels).map(field=>fieldLabels[field]):[]}

export function AcceptancePanel({sessionId,workspace,refreshToken=0,onAccepted}:{sessionId:string;workspace:AuthoringWorkspaceViewV1;refreshToken?:number;onAccepted:()=>void}){
 const [revision,setRevision]=useState<AuthoringReviewRevision>();const [historyError,setHistoryError]=useState("");const [note,setNote]=useState("");const [confirmed,setConfirmed]=useState(false);const [reason,setReason]=useState("");const [modal,setModal]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState<AuthoringAcceptanceResponse>();
 useEffect(()=>{const controller=new AbortController;setHistoryError("");getAuthoringReviewHistory(sessionId,controller.signal).then(history=>{if(!controller.signal.aborted)setRevision(history.revisions.find(item=>item.revision_number===workspace.review.current_revision))}).catch(()=>!controller.signal.aborted&&setHistoryError("Не удалось загрузить данные текущей редакции."));return()=>controller.abort()},[sessionId,workspace.review.current_revision,refreshToken]);
 const warnings=workspace.quality.warnings.length>0||workspace.quality.quality_status==="warnings";const blocked=workspace.quality.quality_status==="blocked"||workspace.quality.blocking_findings.length>0;const accepted=Boolean(workspace.acceptance.accepted_revision)||Boolean(result);const reasonValid=!warnings||(confirmed&&reason.trim().length>=1&&reason.trim().length<=2000);const canOpen=!blocked&&!accepted&&workspace.review.current_revision!==null&&reasonValid&&note.length<=2000;
 const accept=async()=>{setBusy(true);setError("");try{const payload:{acceptance_note?:string;confirm_questionable?:boolean;warning_override_reason?:string}={};if(note.trim())payload.acceptance_note=note.trim();if(warnings){payload.confirm_questionable=true;payload.warning_override_reason=reason.trim()}const value=await acceptAuthoringSession(sessionId,payload);setResult(value);setModal(false);onAccepted()}catch(value){const api=value instanceof ApiError?value:null;setError(api?(errorMessages[api.code]??(api.status===422?errorMessages.validation_error:api.status===404?errorMessages.authoring_session_not_found:"Не удалось принять редакцию.")):"Не удалось принять редакцию.");setModal(false);if(api?.code.includes("conflict"))onAccepted()}finally{setBusy(false)}};
 const fields=changedFields(revision);return <section className="workspace-panel acceptance-panel"><h2>Приёмка</h2><h3>Текущая редакция</h3><dl><dt>Редакция</dt><dd>{workspace.review.current_revision??"—"}</dd><dt>Создана пользователем</dt><dd>{revision?.actor_id??"—"}</dd><dt>Изменённые поля</dt><dd>{fields.length?fields.join(", "):"Нет изменений"}</dd></dl>{historyError&&<div className="alert error" role="alert">{historyError}</div>}<h3>Качество</h3><dl><dt>Статус</dt><dd>{workspace.quality.quality_status}</dd></dl><h4>Блокирующие замечания</h4><Findings items={workspace.quality.blocking_findings} empty="Нет блокирующих замечаний."/><h4>Предупреждения</h4><Findings items={workspace.quality.warnings} empty="Нет предупреждений."/>{!accepted&&<div className="acceptance-form"><label>Примечание к приёмке<textarea value={note} maxLength={2000} onChange={event=>setNote(event.target.value)}/><small>{note.length}/2000</small></label>{warnings&&<><label className="checkbox-row"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>Я проверил(а) предупреждения и подтверждаю исключение</label><label>Причина исключения<textarea aria-label="Причина исключения" required maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/><small>{reason.length}/2000</small></label></>}<button type="button" disabled={!canOpen} onClick={()=>setModal(true)}>Принять в Content Bank</button>{blocked&&<p className="help-text">Устраните блокирующие замечания перед приёмкой.</p>}</div>}{error&&<div className="alert error" role="alert">{error}</div>}{result&&<div className="alert success" role="status"><h3>Версия принята</h3><dl><dt>Созданное задание</dt><dd>{result.task_id}</dd><dt>Созданная версия задания</dt><dd>{result.task_version_id}</dd><dt>Статус</dt><dd>{result.lifecycle_status}</dd></dl></div>}{accepted&&!result&&<p className="alert success">Редакция № {workspace.acceptance.accepted_revision?.revision_number} уже принята.</p>}{modal&&<div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="accept-title"><h2 id="accept-title">Вы принимаете эту версию задания в Content Bank</h2><dl><dt>Выбранная редакция</dt><dd>{workspace.review.current_revision}</dd><dt>Статус качества</dt><dd>{workspace.quality.quality_status}</dd></dl><div className="dialog-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setModal(false)}>Отмена</button><button type="button" disabled={busy} onClick={accept}>{busy?"Принимаем…":"Подтвердить приёмку"}</button></div></section></div>}</section>
}
