import {FormEvent,useEffect,useState} from "react";
import {getCatalog,type CatalogItem} from "./api";
import {errorMessage} from "./errors";
import {createClass,listClasses,type AdminClassGroup,type ClassStatus} from "./classroomAdminApi";

const statuses:{value:ClassStatus;label:string}[]=[{value:"active",label:"Активные"},{value:"archived",label:"Архивные"},{value:"all",label:"Все"}];
const gradeLabel=(x:AdminClassGroup)=>x.grade_id?(x.grade_name||`${x.grade_number} класс`):"Класс обучения не указан";
export function AdminClassesPage({route,navigate}:{route:string;navigate:(to:string)=>void}){
 const raw=new URLSearchParams(route.split("?")[1]||"").get("status"),status:ClassStatus=raw==="archived"||raw==="all"?raw:"active";
 const[items,setItems]=useState<AdminClassGroup[]>([]),[grades,setGrades]=useState<CatalogItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[name,setName]=useState(""),[grade,setGrade]=useState(""),[external,setExternal]=useState(""),[validation,setValidation]=useState("");
 useEffect(()=>{let alive=true;setLoading(true);setError("");Promise.all([listClasses(status),getCatalog("grades")]).then(([classes,catalog])=>{if(alive){setItems(classes);setGrades(catalog.items.sort((a,b)=>(Number(a.name.match(/\d+/)?.[0])||999)-(Number(b.name.match(/\d+/)?.[0])||999)||a.name.localeCompare(b.name,"ru")))}}).catch(e=>alive&&setError(errorMessage(e,"Не удалось загрузить классы."))).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[status]);
 function change(value:ClassStatus){navigate(`/admin/classes?status=${value}`)}
 async function submit(e:FormEvent){e.preventDefault();if(!name.trim()||!grade){setValidation(!name.trim()?"Укажите название класса.":"Укажите класс обучения.");return}setBusy(true);setValidation("");setError("");try{const value=await createClass({name:name.trim(),grade_id:grade,external_ref:external.trim()||null});navigate(`/admin/classes/${value.id}`)}catch(e){setError(errorMessage(e,"Не удалось создать класс."))}finally{setBusy(false)}}
 return <section><div className="page-heading"><div><h1>Классы</h1><p>Учебные классы, преподаватели и ученики</p></div></div><details className="class-create"><summary>Создать класс</summary><form className="management-form" onSubmit={submit}>{validation&&<div className="alert error" role="alert">{validation}</div>}<label>Название<input maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Класс обучения<select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Выберите</option>{grades.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Внешний идентификатор<input maxLength={120} value={external} onChange={e=>setExternal(e.target.value)}/><small>Необязательный идентификатор для интеграций или импорта.</small></label><button disabled={busy}>{busy?"Создание…":"Создать класс"}</button></form></details><label className="status-filter">Статус<select value={status} onChange={e=>change(e.target.value as ClassStatus)}>{statuses.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{error?<div className="alert error" role="alert">{error}</div>:loading?<p className="loading-state" role="status">Загрузка классов…</p>:!items.length?<div className="empty-state">Классов с выбранным статусом нет.</div>:<div className="table-wrap"><table><thead><tr><th>Название</th><th>Класс обучения</th><th>Ученики</th><th>Учителя</th><th>Статус</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><a href={`/admin/classes/${x.id}`} onClick={e=>{e.preventDefault();navigate(e.currentTarget.pathname)}}><strong>{x.name}</strong></a></td><td>{gradeLabel(x)}</td><td>{x.active_student_count}</td><td>{x.assigned_teacher_count}</td><td><span className="badge">{x.archived_at?"Архив":"Активен"}</span>{(!x.is_configuration_complete||!x.grade_id)&&<> <span className="badge warning-badge">Не настроен</span></>}</td></tr>)}</tbody></table></div>}</section>
}
