import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {AdminClassesPage} from "./AdminClassesPage";
import * as classroom from "./classroomAdminApi";
import * as api from "./api";
vi.mock("./classroomAdminApi",async()=>({...await vi.importActual<typeof import("./classroomAdminApi")>("./classroomAdminApi"),listClasses:vi.fn(),createClass:vi.fn()}));
vi.mock("./api",async()=>({...await vi.importActual<typeof import("./api")>("./api"),getCatalog:vi.fn()}));
const item={id:"class-1",name:"7А",grade_id:"grade-7",grade_number:7,grade_name:"7 класс",external_ref:null,created_at:"2026-01-01",archived_at:null,is_configuration_complete:true,active_student_count:22,assigned_teacher_count:2};
beforeEach(()=>{vi.mocked(api.getCatalog).mockResolvedValue({items:[{id:"grade-7",name:"7 класс"}]});vi.mocked(classroom.listClasses).mockResolvedValue([item])});afterEach(()=>{cleanup();vi.resetAllMocks()});
describe("AdminClassesPage",()=>{
 it("loads the active class and renders canonical grade, counters and status",async()=>{render(<AdminClassesPage route="/admin/classes" navigate={vi.fn()}/>);expect(await screen.findByRole("link",{name:"7А"})).toBeTruthy();expect(screen.getAllByText("7 класс")).toHaveLength(2);expect(screen.getByText("22")).toBeTruthy();expect(screen.getByText("2")).toBeTruthy();expect(screen.getByText("Активен")).toBeTruthy();expect(classroom.listClasses).toHaveBeenCalledWith("active")});
 it("navigates status filters and renders empty state",async()=>{vi.mocked(classroom.listClasses).mockResolvedValue([]);const navigate=vi.fn();render(<AdminClassesPage route="/admin/classes?status=archived" navigate={navigate}/>);expect(await screen.findByText("Классов с выбранным статусом нет.")).toBeTruthy();await userEvent.selectOptions(screen.getByLabelText("Статус"),"all");expect(navigate).toHaveBeenCalledWith("/admin/classes?status=all")});
 it("shows legacy classes without hiding configuration state",async()=>{vi.mocked(classroom.listClasses).mockResolvedValue([{...item,id:"legacy",grade_id:null,grade_name:null,grade_number:null,is_configuration_complete:false}]);render(<AdminClassesPage route="/admin/classes" navigate={vi.fn()}/>);expect(await screen.findByText("Класс обучения не указан")).toBeTruthy();expect(screen.getByText("Не настроен")).toBeTruthy()});
 it("validates and creates a class without account fields",async()=>{const navigate=vi.fn();vi.mocked(classroom.createClass).mockResolvedValue(item);render(<AdminClassesPage route="/admin/classes" navigate={navigate}/>);await screen.findByText("7А");await userEvent.click(screen.getByText("Создать класс",{selector:"summary"}));await userEvent.click(screen.getByRole("button",{name:"Создать класс"}));expect(screen.getByRole("alert").textContent).toContain("название");await userEvent.type(screen.getByLabelText("Название"),"7А");await userEvent.selectOptions(screen.getByLabelText("Класс обучения"),"grade-7");await userEvent.click(screen.getByRole("button",{name:"Создать класс"}));await waitFor(()=>expect(classroom.createClass).toHaveBeenCalledWith({name:"7А",grade_id:"grade-7",external_ref:null}));expect(navigate).toHaveBeenCalledWith("/admin/classes/class-1");expect(screen.queryByLabelText(/логин|пароль|роль/i)).toBeNull()});
 it("renders API errors",async()=>{vi.mocked(classroom.listClasses).mockRejectedValue(new Error("offline"));render(<AdminClassesPage route="/admin/classes" navigate={vi.fn()}/>);expect((await screen.findByRole("alert")).textContent).toContain("Не удалось загрузить классы.")});
});
