import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {ApiError,getCatalog,request,type CatalogItem} from "./api";
import type {AdminUser} from "./adminApi";
import {errorMessage} from "./errors";
import {archiveClass,archiveClassStudent,assignClassTeacher,createClassStudent,getClassGroup,listClasses,listClassStudents,listClassTeachers,moveClassStudent,unassignClassTeacher,updateClass,type AdminClassGroup,type AdminClassStudent,type AdminClassTeacher,type StudentStatus} from "./classroomAdminApi";

const known:Record<string,string>={class_not_found:"Класс не найден.",class_archived:"Класс находится в архиве.",class_grade_required:"Сначала укажите класс обучения.",grade_not_found:"Выбранный класс обучения не найден.",teacher_inactive:"Учётная запись преподавателя отключена.",teacher_role_required:"У пользователя нет роли учителя.",student_archived:"Профиль ученика находится в архиве.",external_ref_conflict:"Такой внешний идентификатор уже используется."};
const message=(e:unknown,fallback:string)=>e instanceof ApiError&&known[e.code]?known[e.code]:errorMessage(e,fallback);
async function allUsers(){const items:AdminUser[]=[];let offset=0,total=1;while(offset<total){const page=await request<{items:AdminUser[];total:number}>(`/api/admin/users?offset=${offset}&limit=100`);items.push(...page.items);total=page.total;offset+=page.items.length;if(!page.items.length)break}return items}
const gradeName=(x:AdminClassGroup)=>x.grade_name||`${x.grade_number??"—"} класс`;
export function AdminClassDetailPage({classId,navigate}:{classId:string;navigate:(to:string)=>void}){
 const[group,setGroup]=useState<AdminClassGroup>(),[teachers,setTeachers]=useState<AdminClassTeacher[]>([]),[students,setStudents]=useState<AdminClassStudent[]>([]),[grades,setGrades]=useState<CatalogItem[]>([]),[users,setUsers]=useState<AdminUser[]>([]),[targets,setTargets]=useState<AdminClassGroup[]>([]),[loading,setLoading]=useState(true),[errors,setErrors]=useState<string[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(""),[studentStatus,setStudentStatus]=useState<StudentStatus>("active");
 const[name,setName]=useState(""),[grade,setGrade]=useState(""),[external,setExternal]=useState(""),[teacherId,setTeacherId]=useState(""),[studentName,setStudentName]=useState(""),[studentExternal,setStudentExternal]=useState(""),[moving,setMoving]=useState<AdminClassStudent>(),[targetId,setTargetId]=useState("");
 const refreshGroup=useCallback(async()=>{const x=await getClassGroup(classId);setGroup(x);setName(x.name);setGrade(x.grade_id||"");setExternal(x.external_ref||"")},[classId]);
 const refreshTeachers=useCallback(async()=>setTeachers(await listClassTeachers(classId)),[classId]);
 const refreshStudents=useCallback(async()=>setStudents(await listClassStudents(classId,studentStatus)),[classId,studentStatus]);
 const refreshUsers=useCallback(async()=>setUsers(await allUsers()),[]);
 useEffect(()=>{let alive=true;setLoading(true);setErrors([]);Promise.allSettled([refreshGroup(),refreshTeachers(),refreshStudents(),getCatalog("grades").then(x=>setGrades(x.items)),refreshUsers(),listClasses("active").then(setTargets)]).then(results=>{if(alive){const labels=["основные данные","учителей","учеников","класс обучения","кандидатов в учителя","список классов"];setErrors(results.flatMap((r,i)=>r.status==="rejected"?[`Не удалось загрузить ${labels[i]}.`]:[]));setLoading(false)}});return()=>{alive=false}},[classId]);
 useEffect(()=>{if(group)refreshStudents().catch(e=>setErrors([message(e,"Не удалось загрузить учеников.")]))},[studentStatus]);
 const candidates=useMemo(()=>users.filter(x=>x.is_active&&x.roles.includes("teacher")&&!teachers.some(t=>t.user_id===x.user_id)).sort((a,b)=>a.display_name.localeCompare(b.display_name,"ru")),[users,teachers]);
 const moveTargets=targets.filter(x=>x.id!==classId&&!x.archived_at&&x.grade_id&&x.is_configuration_complete);
 async function run(key:string,action:()=>Promise<unknown>,success:string,refresh:()=>Promise<unknown>){if(busy)return;setBusy(key);setErrors([]);setNotice("");try{await action();await refresh();setNotice(success)}catch(e){setErrors([message(e,"Не удалось выполнить действие.")])}finally{setBusy("")}}
 async function save(e:FormEvent){e.preventDefault();if(!group)return;const patch:Record<string,string|null>={};if(name.trim()!==group.name)patch.name=name.trim();if(grade!==group.grade_id)patch.grade_id=grade;if((external.trim()||null)!==group.external_ref)patch.external_ref=external.trim()||null;if(!Object.keys(patch).length){setNotice("Изменений нет.");return}await run("save",()=>updateClass(classId,patch),"Изменения сохранены.",refreshGroup)}
 async function assign(){if(!teacherId||busy)return;setBusy("assign");setErrors([]);setNotice("");try{await assignClassTeacher(classId,teacherId);setNotice("Преподаватель назначен.");setTeacherId("")}catch(e){setErrors([e instanceof ApiError&&["teacher_not_found","teacher_inactive","teacher_role_required"].includes(e.code)?"Не удалось назначить преподавателя. Его учётная запись могла измениться.":message(e,"Не удалось назначить преподавателя.")])}finally{await Promise.allSettled([refreshTeachers(),refreshUsers(),refreshGroup()]);setBusy("")}}
 async function unassign(t:AdminClassTeacher){if(!confirm(`Убрать преподавателя «${t.display_name}» из класса?`))return;await run(`teacher-${t.user_id}`,()=>unassignClassTeacher(classId,t.user_id),"Преподаватель убран из класса.",()=>Promise.all([refreshTeachers(),refreshUsers(),refreshGroup()]))}
 async function createStudent(e:FormEvent){e.preventDefault();if(!studentName.trim())return;await run("student-create",()=>createClassStudent(classId,{display_name:studentName.trim(),external_ref:studentExternal.trim()||null}),"Профиль ученика создан.",async()=>{setStudentName("");setStudentExternal("");await Promise.all([refreshStudents(),refreshGroup()])})}
 async function archiveStudent(s:AdminClassStudent){if(!confirm(`Архивировать профиль ученика «${s.display_name}»?\nИстория его работ сохранится.`))return;await run(`student-${s.id}`,()=>archiveClassStudent(classId,s.id),"Профиль ученика архивирован.",()=>Promise.all([refreshStudents(),refreshGroup()]))}
 async function move(){if(!moving||!targetId||!group)return;const target=moveTargets.find(x=>x.id===targetId);if(!target||!confirm(`Перевести ученика «${moving.display_name}» из ${group.name} в ${target.name}?`))return;setBusy(`student-${moving.id}`);setErrors([]);try{await moveClassStudent(classId,moving.id,{target_class_group_id:targetId,expected_current_class_group_id:classId});setMoving(undefined);setTargetId("");setNotice("Ученик переведён.");await Promise.all([refreshStudents(),refreshGroup(),listClasses("active").then(setTargets)])}catch(e){if(e instanceof ApiError&&e.code==="student_class_conflict"){setErrors(["Ученик уже был переведён или его класс изменился. Данные обновлены."]);setMoving(undefined);await refreshStudents()}else setErrors([message(e,"Не удалось перевести ученика.")])}finally{setBusy("")}}
 if(loading&&!group)return <p className="loading-state" role="status">Загрузка класса…</p>;
 if(!group)return <section className="empty-state"><h1>Класс не найден.</h1>{errors.map(x=><p key={x} role="alert">{x}</p>)}</section>;
 const archived=!!group.archived_at,configured=!!group.grade_id&&group.is_configuration_complete;
 return <section className="class-detail"><a href="/admin/classes" onClick={e=>{e.preventDefault();navigate("/admin/classes")}}>← К классам</a><div className="page-heading"><div><h1>{group.name}</h1><p>{group.grade_id?gradeName(group):"Класс обучения не указан"}</p></div><div><span className="badge">{archived?"Архивный класс":"Активен"}</span>{!configured&&<> <span className="badge warning-badge">Не настроен</span></>}</div></div>{errors.map(x=><div key={x} role="alert" className="alert error">{x}</div>)}{notice&&<div role="status" className="alert success">{notice}</div>}{!configured&&<div className="configuration-warning" role="status"><strong>Для этого класса не указан класс обучения.</strong><br/>Укажите его, чтобы назначать преподавателей и добавлять учеников.</div>}
 <article className="management-section"><h2>Основные данные</h2>{archived&&<p className="help-text">Архивный класс доступен только для просмотра. Редактирование отключено.</p>}<form className="management-form" onSubmit={save}><label>Название<input required maxLength={120} disabled={archived} value={name} onChange={e=>setName(e.target.value)}/></label><label>Класс обучения<select required disabled={archived} value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Выберите</option>{grades.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Внешний идентификатор<input maxLength={120} disabled={archived} value={external} onChange={e=>setExternal(e.target.value)}/></label><button disabled={archived||busy==="save"}>Сохранить</button>{!archived&&<button type="button" className="danger" disabled={!!busy} onClick={()=>{if(confirm(`Архивировать класс «${group.name}»?\nИстория самостоятельных работ и учеников сохранится.`))run("archive",()=>archiveClass(classId),"Класс архивирован.",refreshGroup)}}>Архивировать класс</button>}</form></article>
 <article className="management-section"><h2>Учителя</h2>{archived?<p className="help-text">Новых преподавателей нельзя назначать в архивный класс.</p>:!configured?<p className="help-text">Сначала укажите класс обучения.</p>:<div className="inline-management"><label>Назначить учителя<select value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Выберите</option>{candidates.map(x=><option key={x.user_id} value={x.user_id}>{x.display_name}</option>)}</select></label><button disabled={!teacherId||!!busy} onClick={assign}>Назначить</button></div>}{!teachers.length?<p className="empty-state">Преподаватели не назначены.</p>:<ul className="management-list">{teachers.map(t=><li key={t.user_id}><span><strong>{t.display_name}</strong> <span className="badge">{t.is_active?"Активен":"Отключён"}</span></span><button className="secondary" disabled={!!busy} onClick={()=>unassign(t)}>Убрать из класса</button></li>)}</ul>}</article>
 <article className="management-section"><h2>Ученики</h2><label className="status-filter">Статус<select value={studentStatus} onChange={e=>setStudentStatus(e.target.value as StudentStatus)}><option value="active">Активные</option><option value="archived">Архивные</option><option value="all">Все</option></select></label>{archived?<p className="help-text">Добавление учеников в архивный класс недоступно.</p>:!configured?<p className="help-text">Сначала укажите класс обучения.</p>:<form className="inline-management" onSubmit={createStudent}><label>Имя<input required maxLength={120} value={studentName} onChange={e=>setStudentName(e.target.value)}/></label><label>Внешний идентификатор<input maxLength={120} value={studentExternal} onChange={e=>setStudentExternal(e.target.value)}/></label><button disabled={!!busy}>Добавить ученика</button></form>}<p className="help-text">Для входа ученика создайте или привяжите учётную запись в разделе «Пользователи». <a href="/admin/users" onClick={e=>{e.preventDefault();navigate("/admin/users")}}>Перейти к пользователям</a></p>{!students.length?<p className="empty-state">В списке нет учеников.</p>:<div className="table-wrap"><table><thead><tr><th>Имя</th><th>Внешний идентификатор</th><th>ID профиля</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.display_name}</td><td>{s.external_ref||"—"}</td><td><small>{s.id}</small><br/><button className="link-button" onClick={()=>navigator.clipboard?.writeText(s.id)}>Скопировать ID</button></td><td><span className="badge">{s.archived_at?"Архив":"Активен"}</span></td><td>{!s.archived_at&&<div className="row-actions"><button className="secondary" disabled={!!busy||!moveTargets.length} onClick={()=>{setMoving(s);setTargetId("")}}>Перевести</button><button className="danger" disabled={!!busy} onClick={()=>archiveStudent(s)}>Архивировать</button></div>}</td></tr>)}</tbody></table></div>}</article>{moving&&<div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="move-title"><h2 id="move-title">Перевести ученика «{moving.display_name}»</h2><label>Класс назначения<select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Выберите</option>{moveTargets.map(x=><option key={x.id} value={x.id}>{x.name} · {gradeName(x)}</option>)}</select></label><p className="help-text">Ранее назначенные работы останутся в истории прежнего класса.</p><div className="dialog-actions"><button className="secondary" onClick={()=>setMoving(undefined)}>Отмена</button><button disabled={!targetId||!!busy} onClick={move}>Перевести</button></div></div></div>}</section>
}
