import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor,within} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {AdminClassDetailPage} from "./AdminClassDetailPage";
import * as classroom from "./classroomAdminApi";
import * as api from "./api";

vi.mock("./classroomAdminApi",async()=>{const actual=await vi.importActual<typeof import("./classroomAdminApi")>("./classroomAdminApi");return {...actual,getClassGroup:vi.fn(),listClassTeachers:vi.fn(),listClassStudents:vi.fn(),listStudentCandidates:vi.fn(),listClasses:vi.fn(),createClassStudent:vi.fn(),archiveClassStudent:vi.fn(),moveClassStudent:vi.fn()}});
vi.mock("./api",async()=>({...await vi.importActual<typeof import("./api")>("./api"),getCatalog:vi.fn(),request:vi.fn()}));
const group={id:"class-1",name:"7А",grade_id:"grade-7",grade_number:7,grade_name:"7 класс",external_ref:null,created_at:"2026-01-01",archived_at:null,is_configuration_complete:true,active_student_count:2,assigned_teacher_count:0};
const linked={id:"9ac1f170-0000-4000-8000-000000000001",display_name:"Старое имя",external_ref:null,class_group_id:"class-1",archived_at:null,user_id:"user-1",first_name:"Иван",last_name:"Петров",login:"ivan.petrov"};
const legacy={id:"9ac1f170-0000-4000-8000-000000000002",display_name:"Легаси Ученик",external_ref:null,class_group_id:"class-1",archived_at:null,user_id:null,first_name:null,last_name:null,login:null};
const candidate={user_id:"candidate-1",first_name:"Анна",last_name:"Смирнова",display_name:"Анна Смирнова",login:"anna",provisioning_state:"available" as const};

beforeEach(()=>{vi.mocked(classroom.getClassGroup).mockResolvedValue(group);vi.mocked(classroom.listClassTeachers).mockResolvedValue([]);vi.mocked(classroom.listClassStudents).mockResolvedValue([linked,legacy]);vi.mocked(classroom.listStudentCandidates).mockResolvedValue([candidate]);vi.mocked(classroom.listClasses).mockResolvedValue([group]);vi.mocked(api.getCatalog).mockResolvedValue({items:[{id:"grade-7",name:"7 класс"}]});vi.mocked(api.request).mockResolvedValue({items:[],total:0});vi.mocked(classroom.createClassStudent).mockResolvedValue(linked)});
afterEach(()=>{cleanup();vi.resetAllMocks()});
async function ready(){render(<AdminClassDetailPage classId="class-1" navigate={vi.fn()}/>);await screen.findByRole("heading",{name:"7А"});await screen.findByRole("option",{name:"Анна Смирнова · anna"})}

describe("AdminClassDetailPage student accounts",()=>{
 it("loads and searches classroom candidates without exposing the old profile workflow",async()=>{await ready();expect(classroom.listStudentCandidates).toHaveBeenCalledWith("class-1",{query:"",limit:20});expect(screen.queryByLabelText("Имя")).toBeNull();expect(screen.queryByText("ID профиля")).toBeNull();expect(screen.queryByText("Скопировать ID")).toBeNull();expect(screen.queryByText(/создайте или привяжите/)).toBeNull();await userEvent.type(screen.getByLabelText("Поиск ученика"),"мария");vi.mocked(classroom.listStudentCandidates).mockResolvedValue([{...candidate,user_id:"candidate-2",first_name:"Мария",last_name:null,display_name:"Мария",login:"maria"}]);await userEvent.click(screen.getByRole("button",{name:"Найти"}));expect(await screen.findByRole("option",{name:"Мария · maria"})).toBeTruthy();expect(screen.queryByRole("option",{name:"Анна Смирнова · anna"})).toBeNull();expect(classroom.listStudentCandidates).toHaveBeenLastCalledWith("class-1",{query:"мария",limit:20})});
 it("provisions the selected account and refreshes roster and candidates",async()=>{await ready();await userEvent.selectOptions(screen.getByLabelText("Учётная запись ученика"),"candidate-1");await userEvent.type(screen.getByLabelText("Внешний идентификатор (необязательно)"),"school-42");const studentCalls=vi.mocked(classroom.listClassStudents).mock.calls.length,candidateCalls=vi.mocked(classroom.listStudentCandidates).mock.calls.length;await userEvent.click(screen.getByRole("button",{name:"Добавить ученика"}));await screen.findByText("Ученик добавлен в класс.");expect(classroom.createClassStudent).toHaveBeenCalledWith("class-1",{user_id:"candidate-1",external_ref:"school-42"});expect(vi.mocked(classroom.createClassStudent).mock.calls[0][1]).not.toHaveProperty("display_name");expect(vi.mocked(classroom.createClassStudent).mock.calls[0][1]).not.toHaveProperty("student_id");expect(vi.mocked(classroom.listClassStudents).mock.calls.length).toBeGreaterThan(studentCalls);expect(vi.mocked(classroom.listStudentCandidates).mock.calls.length).toBeGreaterThan(candidateCalls);expect(screen.getByLabelText<HTMLSelectElement>("Учётная запись ученика").value).toBe("");expect(screen.getByLabelText<HTMLInputElement>("Внешний идентификатор (необязательно)").value).toBe("")});
 it("shows account-facing roster data and safely renders a legacy profile",async()=>{await ready();const rows=screen.getAllByRole("row");expect(within(rows[1]).getByText("Иван")).toBeTruthy();expect(within(rows[1]).getByText("Петров")).toBeTruthy();expect(within(rows[1]).getByText("ivan.petrov")).toBeTruthy();expect(within(rows[2]).getByText("Легаси Ученик")).toBeTruthy();expect(within(rows[2]).getByText("Нет учётной записи")).toBeTruthy();expect(screen.queryByText(linked.id)).toBeNull();expect(screen.queryByText(legacy.id)).toBeNull()});
 it.each([
  ["student_user_inactive","Учётная запись ученика отключена."],
  ["student_role_required","У пользователя нет роли ученика."],
  ["student_already_in_class","Ученик уже находится в этом классе."],
  ["student_in_another_class","Ученик уже состоит в другом классе. Используйте перевод между классами."],
  ["student_profile_archived","Профиль ученика находится в архиве."],
  ["external_ref_conflict","Такой внешний идентификатор уже используется."],
 ])("maps provisioning error %s and refreshes candidates",async(code,text)=>{vi.mocked(classroom.createClassStudent).mockRejectedValue(new api.ApiError(409,code,"backend"));await ready();const calls=vi.mocked(classroom.listStudentCandidates).mock.calls.length;await userEvent.selectOptions(screen.getByLabelText("Учётная запись ученика"),"candidate-1");await userEvent.click(screen.getByRole("button",{name:"Добавить ученика"}));expect(await screen.findByText(text)).toBeTruthy();await waitFor(()=>expect(vi.mocked(classroom.listStudentCandidates).mock.calls.length).toBeGreaterThan(calls));expect(screen.getByRole("button",{name:"Добавить ученика"})).toBeTruthy()});
 it("preserves status filtering and archive behavior",async()=>{await ready();await userEvent.selectOptions(screen.getByLabelText("Статус"),"archived");await waitFor(()=>expect(classroom.listClassStudents).toHaveBeenCalledWith("class-1","archived"));vi.spyOn(window,"confirm").mockReturnValue(true);await userEvent.selectOptions(screen.getByLabelText("Статус"),"active");await screen.findByText("Иван");await userEvent.click(screen.getAllByRole("button",{name:"Архивировать"})[0]);await waitFor(()=>expect(classroom.archiveClassStudent).toHaveBeenCalledWith("class-1",linked.id))});
});
