import {afterEach,describe,expect,it,vi} from "vitest";
import {addAssessmentItem,createAssessment,createAssessmentVariant,deleteAssessmentItem,deleteAssessmentVariant,getAssessment,listAssessments,patchAssessment,patchAssessmentItem,reorderAssessmentItems,searchApprovedTasks} from "./api";
const ok=(body:unknown={},status=200)=>Promise.resolve(new Response(status===204?null:JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));
afterEach(()=>vi.restoreAllMocks());
describe("Assessment API client",()=>{
 it("uses exact assessment requests and decimal/CAS payloads",async()=>{const f=vi.spyOn(globalThis,"fetch").mockImplementation(()=>ok());await listAssessments("draft",20,10);await createAssessment({title:"T",description:null});await getAssessment("a");await patchAssessment("a",{title:"N",expected_updated_at:"T0"});await createAssessmentVariant("a","A");await deleteAssessmentVariant("a","v");await addAssessmentItem("a","v",{task_version_id:"version-B",points:"2.50"});await deleteAssessmentItem("a","v","i");await reorderAssessmentItems("a","v",["i2","i1"],"T2");await patchAssessmentItem("a","v","i","2.50","T1");const calls=f.mock.calls.map(([u,i])=>[String(u).replace(/^.*\/api/,'/api'),i?.method, i?.body&&JSON.parse(String(i.body))]);expect(calls).toEqual([
  ["/api/assessment-core/assessments?offset=20&limit=10&status=draft",undefined,undefined],["/api/assessment-core/assessments","POST",{title:"T",description:null}],["/api/assessment-core/assessments/a",undefined,undefined],["/api/assessment-core/assessments/a","PATCH",{title:"N",expected_updated_at:"T0"}],["/api/assessment-core/assessments/a/variants","POST",{name:"A"}],["/api/assessment-core/assessments/a/variants/v","DELETE",undefined],["/api/assessment-core/assessments/a/variants/v/items","POST",{task_version_id:"version-B",points:"2.50"}],["/api/assessment-core/assessments/a/variants/v/items/i","DELETE",undefined],["/api/assessment-core/assessments/a/variants/v/item-order","PUT",{item_ids:["i2","i1"],expected_updated_at:"T2"}],["/api/assessment-core/assessments/a/variants/v/items/i","PATCH",{points:"2.50",expected_updated_at:"T1"}]
 ])});
 it("always forces approved Content Bank status",async()=>{const f=vi.spyOn(globalThis,"fetch").mockImplementation(()=>ok({items:[]}));await searchApprovedTasks(new URLSearchParams({q:"x",status:"draft"}));expect(String(f.mock.calls[0][0])).toContain("q=x&status=approved")});
});
