import {afterEach,describe,expect,it,vi} from "vitest";
import {act} from "react";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {App} from "./main";
const response=(x:unknown,status=200)=>Promise.resolve(new Response(status===204?null:JSON.stringify(x),{status,headers:{"Content-Type":"application/json"}}));
const item=(id:string,position:number,points="1.00")=>({id,task_version_id:`version-${id}`,position,points});
const detail=(updated_at="T0",status="draft",items=[item("i1",1),item("i2",2)])=>({id:"a",title:"Алгебра",description:"Тест",status,variants:[{id:"v",name:"A",position:1,items,total_points:"2.00"}],created_at:"2026-01-01T00:00:00Z",updated_at,published_at:null,published_by:null});
afterEach(()=>{cleanup();vi.restoreAllMocks();history.replaceState({},"","/")});
describe("Assessment pages",()=>{
 it("renders list, empty/error and filter routes",async()=>{history.replaceState({},"","/assessments");const f=vi.spyOn(globalThis,"fetch").mockImplementation(u=>String(u).includes("status=draft")?response({items:[],total:0,offset:0,limit:100}):response({items:[{...detail(),variant_count:1}],total:1,offset:0,limit:100}));render(<App/>);expect(screen.getByText("Загрузка работ…")).toBeTruthy();expect(await screen.findByText("Алгебра")).toBeTruthy();await userEvent.selectOptions(screen.getByLabelText("Статус"),"draft");expect(await screen.findByText("Работ пока нет.")).toBeTruthy();expect(String(f.mock.calls.at(-1)?.[0])).toContain("status=draft")});
 it("creates and navigates to detail",async()=>{history.replaceState({},"","/assessments/new");vi.spyOn(globalThis,"fetch").mockImplementation(()=>response(detail()));render(<App/>);await userEvent.type(screen.getByLabelText("Название"),"Алгебра");await userEvent.click(screen.getByRole("button",{name:"Создать работу"}));await waitFor(()=>expect(location.pathname).toBe("/assessments/a"))});
 it("shows not found and published read-only",async()=>{history.replaceState({},"","/assessments/a");vi.spyOn(globalThis,"fetch").mockImplementation(()=>response({error:{code:"assessment_not_found",message:"Нет"}},404));render(<App/>);expect(await screen.findByRole("heading",{name:"Работа не найдена"})).toBeTruthy();cleanup();vi.restoreAllMocks();vi.spyOn(globalThis,"fetch").mockImplementation(()=>response(detail("T0","published")));render(<App/>);expect(await screen.findByText(/Состав больше нельзя изменять/)).toBeTruthy();expect((screen.getByRole("button",{name:"Добавить задание"}) as HTMLButtonElement).disabled).toBe(true);expect(screen.queryByRole("button",{name:"Сохранить баллы"})).toBeNull()});
 it("uses latest_version_id, not task_id, when adding",async()=>{history.replaceState({},"","/assessments/a");const f=vi.spyOn(globalThis,"fetch").mockImplementation((u,i)=>{const url=String(u);if(url.includes("catalog/"))return response({items:[]});if(url.includes("/api/content-bank/tasks?"))return response({items:[{task_id:"task-A",latest_version_id:"version-B",version_no:3,title:"Квадрат",statement:"Решите",subject_id:"s",subject_name:"Математика",grade_id:"g",grade_name:"8",topic_id:"t",topic_name:"Алгебра",task_type:"calculation",difficulty:20,status:"approved"}],total:1,offset:0,limit:10});if(i?.method==="POST"&&url.endsWith("/items"))return response(item("new",3),201);return response(detail())});render(<App/>);await screen.findByText("Алгебра");await userEvent.click(screen.getByRole("button",{name:"Добавить задание"}));expect(await screen.findByText("Решите")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"Добавить"}));await waitFor(()=>{const call=f.mock.calls.find(([u,i])=>String(u).endsWith("/items")&&i?.method==="POST");expect(JSON.parse(String(call?.[1]?.body))).toEqual({task_version_id:"version-B",points:"1.00"})})});
 it("refreshes CAS T0 to T1 for points and T2 for reorder",async()=>{history.replaceState({},"","/assessments/a");let gets=0;const bodies:unknown[]=[];vi.spyOn(globalThis,"fetch").mockImplementation((u,i)=>{const url=String(u);if(!i?.method&&url.includes("/class-groups"))return response({items:[],total:0,offset:0,limit:100});if(!i?.method&&url.includes("/assignments?"))return response({items:[],total:0,offset:0,limit:100});if(!i?.method&&url.includes("assessment-core"))return response(detail(["T0","T1","T2","T3"][gets++]));if(i?.method==="POST"&&url.endsWith("/items"))return response(item("new",3),201);if(i?.body)bodies.push(JSON.parse(String(i.body)));return response({})});render(<App/>);await screen.findByText("Алгебра");const input=screen.getAllByLabelText("Баллы")[0];await userEvent.clear(input);await userEvent.type(input,"2.50");await userEvent.click(screen.getAllByRole("button",{name:"Сохранить баллы"})[0]);await waitFor(()=>expect(bodies).toContainEqual({points:"2.50",expected_updated_at:"T0"}));await userEvent.click(screen.getByRole("button",{name:"Переместить задание 1 ниже"}));await waitFor(()=>expect(bodies).toContainEqual({item_ids:["i2","i1"],expected_updated_at:"T1"}))});
 it("refetches on concurrent conflict without hiding composition",async()=>{history.replaceState({},"","/assessments/a");let patch=false;vi.spyOn(globalThis,"fetch").mockImplementation((_u,i)=>i?.method==="PATCH"&&!patch?(patch=true,response({error:{code:"concurrent_conflict",message:"Conflict"}},409)):response(detail("T1")));render(<App/>);await screen.findByText("Алгебра");const title=screen.getByLabelText("Название");await userEvent.clear(title);await userEvent.type(title,"Новое");await userEvent.click(screen.getByRole("button",{name:"Сохранить описание"}));expect(await screen.findByText(/Работа была изменена/)).toBeTruthy();expect(screen.getByText("Варианты")).toBeTruthy()});
 it("prevents a late search response overwriting the newer query",async()=>{history.replaceState({},"","/assessments/a");let oldResolve:(r:Response)=>void=()=>{};vi.spyOn(globalThis,"fetch").mockImplementation((u)=>{const url=String(u);if(url.includes("catalog/"))return response({items:[]});if(url.includes("q=old"))return new Promise(r=>oldResolve=r);if(url.includes("q=new"))return response({items:[{task_id:"t2",latest_version_id:"v2",version_no:1,title:"NEW",statement:"new",subject_id:"s",subject_name:"S",grade_id:"g",grade_name:"G",topic_id:"t",topic_name:"T",task_type:"test",difficulty:1,status:"approved"}],total:1,offset:0,limit:10});if(url.includes("content-bank/tasks"))return response({items:[],total:0,offset:0,limit:10});return response(detail())});render(<App/>);await screen.findByText("Алгебра");await userEvent.click(screen.getByRole("button",{name:"Добавить задание"}));const q=screen.getByLabelText("Поиск");await userEvent.type(q,"old");await userEvent.click(screen.getByRole("button",{name:"Найти"}));await userEvent.clear(q);await userEvent.type(q,"new");await userEvent.click(screen.getByRole("button",{name:"Найти"}));expect(await screen.findByText("NEW")).toBeTruthy();await act(async()=>oldResolve(await response({items:[{title:"OLD"}],total:1,offset:0,limit:10})));expect(screen.queryByText("OLD")).toBeNull()});
});
