import {afterEach,describe,expect,it,vi} from "vitest";
import {act,cleanup,render,screen,waitFor,within} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {AuditHistory,auditLabels} from "./AuditHistory";
import {MethodologyEditor} from "./MethodologyEditor";
afterEach(()=>{cleanup();vi.restoreAllMocks()});
const ev=(action:keyof typeof auditLabels="task_created",extra={})=>({id:action,task_id:"task",task_version_id:"v",version_no:2,action,actor_id:"11111111-1111-1111-1111-111111111111",reason:null,details:{},occurred_at:"2026-07-28T10:00:00Z",...extra});
const res=(items:any[],total=items.length)=>new Response(JSON.stringify({items,total,offset:0,limit:20}),{status:200});
describe("history",()=>{
 it("shows loading and empty",async()=>{let done!:(x:Response)=>void;vi.spyOn(globalThis,"fetch").mockReturnValue(new Promise(r=>done=r));render(<AuditHistory taskId="task"/>);expect(screen.getByRole("status")).toBeTruthy();done(res([]));expect(await screen.findByText("История изменений пока пуста")).toBeTruthy()});
 it("renders every action label",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(res((Object.keys(auditLabels) as (keyof typeof auditLabels)[]).map(x=>ev(x))));render(<AuditHistory taskId="task"/>);const history=await screen.findByRole("list");const items=within(history).getAllByRole("listitem");expect(items).toHaveLength(7);for(const [index,label] of Object.values(auditLabels).entries())expect(within(items[index]).getByText(label)).toBeTruthy()});
 it("renders safe metadata and localized statuses",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(res([ev("returned_to_draft",{reason:"Исправить",details:{from_status:"review",to_status:"draft",hints_count:3,secret:"hidden"}})]));render(<AuditHistory taskId="task"/>);for(const x of ["Исправить","На проверке","Черновик","3","v2","11111111-1111-1111-1111-111111111111"])expect(await screen.findByText(x)).toBeTruthy();expect(screen.queryByText("hidden")).toBeNull();expect(document.querySelector("time")!.getAttribute("datetime")).toBe("2026-07-28T10:00:00Z")});
 it("omits empty optional metadata",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(res([ev("task_created",{version_no:null})]));render(<AuditHistory taskId="task"/>);await screen.findByText("Задание создано");expect(screen.queryByText("Версия")).toBeNull();expect(screen.queryByText("Причина")).toBeNull();expect(document.querySelector(".audit-details")).toBeNull()});
 it("filters, resets pagination, and shows filtered empty",async()=>{const f=vi.spyOn(globalThis,"fetch").mockImplementation(async input=>{const url=new URL(String(input));return res([],url.searchParams.has("action")?0:40)});render(<AuditHistory taskId="task"/>);await screen.findByText("История изменений пока пуста");await userEvent.click(screen.getByRole("button",{name:"Далее"}));await waitFor(()=>expect(String(f.mock.calls.at(-1)?.[0])).toContain("offset=20"));await userEvent.selectOptions(screen.getByLabelText("Тип события"),"task_archived");await waitFor(()=>expect(String(f.mock.calls.at(-1)?.[0])).toContain("offset=0&limit=20&action=task_archived"));expect(await screen.findByText("Событий этого типа нет")).toBeTruthy()});
 it("supports previous/next boundaries",async()=>{const f=vi.spyOn(globalThis,"fetch").mockResolvedValue(res([ev()],25));render(<AuditHistory taskId="task"/>);await screen.findByText("Задание создано");expect((screen.getByRole("button",{name:"Назад"}) as HTMLButtonElement).disabled).toBe(true);await userEvent.click(screen.getByRole("button",{name:"Далее"}));await waitFor(()=>expect(String(f.mock.calls.at(-1)?.[0])).toContain("offset=20"));expect((screen.getByRole("button",{name:"Далее"}) as HTMLButtonElement).disabled).toBe(true);await userEvent.click(screen.getByRole("button",{name:"Назад"}));await waitFor(()=>expect(String(f.mock.calls.at(-1)?.[0])).toContain("offset=0"))});
 it("shows error and retries",async()=>{const f=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(new Response("",{status:500})).mockResolvedValueOnce(res([]));render(<AuditHistory taskId="task"/>);await screen.findByRole("alert");await userEvent.click(screen.getByRole("button",{name:"Повторить"}));expect(await screen.findByText("История изменений пока пуста")).toBeTruthy();expect(f).toHaveBeenCalledTimes(2)});
 it("ignores stale results",async()=>{let resolveFirst!:(x:Response)=>void,resolveSecond!:(x:Response)=>void;const first=new Promise<Response>(r=>resolveFirst=r),second=new Promise<Response>(r=>resolveSecond=r);const f=vi.spyOn(globalThis,"fetch").mockReturnValueOnce(first).mockReturnValueOnce(second);render(<AuditHistory taskId="task"/>);expect(f).toHaveBeenCalledTimes(1);await userEvent.selectOptions(screen.getByLabelText("Тип события"),"task_archived");expect(f).toHaveBeenCalledTimes(2);await act(async()=>resolveSecond(res([ev("task_archived")])));const history=await screen.findByRole("list");expect(within(history).getByText("Задание архивировано")).toBeTruthy();await act(async()=>resolveFirst(res([ev()])));expect(within(history).queryByText("Задание создано")).toBeNull();expect(within(history).getByText("Задание архивировано")).toBeTruthy()});
});
it("loads lazily and preserves dirty form",async()=>{const f=vi.spyOn(globalThis,"fetch").mockResolvedValue(res([]));const methodology={expected_solution:{id:"s",solution_text:"old",final_answer:null,solution_steps:[]},rubric:null,accepted_answers:[],typical_errors:[],hints:[]};const card={archived_at:null,latest_version:{id:"v",status:"draft",answer_format:"number",skills:[],methodology}};render(<MethodologyEditor card={card} mainPanel={<p>Main</p>} auditPanel={<AuditHistory taskId="task"/>} onDirtyChange={()=>{}} onSaved={()=>{}}/>);expect(f).not.toHaveBeenCalled();await userEvent.click(screen.getByRole("tab",{name:"Решение"}));await userEvent.type(screen.getByDisplayValue("old")," changed");await userEvent.click(screen.getByRole("tab",{name:"История"}));await screen.findByText("История изменений пока пуста");await userEvent.click(screen.getByRole("tab",{name:"Решение"}));expect(screen.getByDisplayValue("old changed")).toBeTruthy()});
