import {useCallback,useEffect,useRef,useState} from "react";
import {getTaskAudit,type AuditAction,type AuditEvent,type AuditPage} from "./api";

export const auditLabels:Record<AuditAction,string>={tag_added_to_version:"Тег добавлен",tag_removed_from_version:"Тег удалён",task_created:"Задание создано",methodology_updated:"Методика обновлена",submitted_for_review:"Отправлено на проверку",returned_to_draft:"Возвращено в черновик",version_approved:"Версия утверждена",version_created:"Создана новая версия",task_archived:"Задание архивировано"};
const statusLabels:Record<string,string>={draft:"Черновик",review:"На проверке",approved:"Утверждено",archived:"Архив"};
const detailLabels:Record<string,string>={from_status:"Предыдущий статус",to_status:"Новый статус",source_version_no:"Исходная версия",previous_approved_version_no:"Предыдущая утверждённая версия",rubric_items_count:"Критериев",accepted_answers_count:"Принятых ответов",hints_count:"Подсказок",typical_error_links_count:"Связей с типичными ошибками"};
const detailKeys=Object.keys(detailLabels),limit=20;
function Details({event}:{event:AuditEvent}){const entries=detailKeys.flatMap(key=>{const value=event.details?.[key];return value===undefined||value===null||value===""?[]:[[key,typeof value==="string"&&(key==="from_status"||key==="to_status")?(statusLabels[value]??value):String(value)] as const]});return entries.length?<dl className="audit-details">{entries.map(([key,value])=><div key={key}><dt>{detailLabels[key]}</dt><dd>{value}</dd></div>)}</dl>:null}
export function AuditHistory({taskId,revision=0}:{taskId:string;revision?:number}){const [action,setAction]=useState<AuditAction|"">("");const [offset,setOffset]=useState(0);const [page,setPage]=useState<AuditPage>();const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [retry,setRetry]=useState(0);const requestNo=useRef(0);const load=useCallback(()=>setRetry(x=>x+1),[]);
 useEffect(()=>{const controller=new AbortController(),current=++requestNo.current;setLoading(true);setError("");getTaskAudit(taskId,{offset,limit,action:action||undefined,signal:controller.signal}).then(result=>{if(current!==requestNo.current)return;if(!result.items.length&&result.total>0&&offset>0){setOffset(Math.max(0,Math.floor((result.total-1)/limit)*limit));return}setPage(result)}).catch(e=>{if(current===requestNo.current&&e?.name!=="AbortError")setError(e instanceof Error?e.message:"Не удалось загрузить историю изменений.")}).finally(()=>{if(current===requestNo.current)setLoading(false)});return()=>controller.abort()},[taskId,offset,action,retry,revision]);
 const from=page?.items.length?offset+1:0,to=page?.items.length?offset+page.items.length:0,total=page?.total??0;return <div className="audit-history"><div className="audit-toolbar"><label htmlFor="audit-action">Тип события</label><select id="audit-action" value={action} onChange={e=>{setAction(e.target.value as AuditAction|"");setOffset(0)}}><option value="">Все события</option>{Object.entries(auditLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{error?<div className="alert error" role="alert"><p>Не удалось загрузить историю изменений.</p><button type="button" onClick={load}>Повторить</button></div>:loading?<p role="status">Загрузка истории изменений…</p>:!page?.items.length?<div className="empty">{action?"Событий этого типа нет":"История изменений пока пуста"}</div>:<ol className="audit-events">{page.items.map(event=><li key={event.id}><div className="audit-event-head"><strong>{auditLabels[event.action]??"Неизвестное событие"}</strong><time dateTime={event.occurred_at} title={event.occurred_at}>{new Date(event.occurred_at).toLocaleString("ru-RU")}</time></div><dl className="audit-meta">{event.version_no!=null&&<div><dt>Версия</dt><dd>v{event.version_no}</dd></div>}<div><dt>Исполнитель</dt><dd><code>{event.actor_id}</code></dd></div>{event.reason&&<div><dt>Причина</dt><dd>{event.reason}</dd></div>}</dl><Details event={event}/></li>)}</ol>}<div className="pagination audit-pagination"><span>Показано {from}–{to} из {total}</span><button type="button" className="secondary" disabled={offset===0||loading} onClick={()=>setOffset(x=>Math.max(0,x-limit))}>Назад</button><button type="button" className="secondary" disabled={loading||offset+limit>=total} onClick={()=>setOffset(x=>x+limit)}>Далее</button></div></div>}
