import {FormEvent,useEffect,useState} from "react";
import {ApiError,createAuthoringSession,getAuthoringRoutes,getCatalog,getSubjectRoots,runAuthoringSession,type AuthoringCreateRequest,type AuthoringRoute,type CatalogItem,type SubjectRoot} from "./api";

const formats:Record<AuthoringCreateRequest["task_type"],AuthoringCreateRequest["answer_format"][]>={test:["single_choice","multiple_choice"],calculation:["short_text","number","expression"],problem:["number","expression","long_text"],open_question:["short_text","long_text"],essay:["long_text"]};
const key=(route:AuthoringRoute)=>`${route.provider_id}\u0000${route.model_id}`;
const apiMessage=(error:unknown,fallback:string)=>error instanceof ApiError?(error.details?.map?.((item:{message?:string})=>item.message).filter(Boolean).join("; ")||error.message||fallback):fallback;

export function AuthoringCreatePage({navigate}:{navigate:(to:string)=>void}){
 const [catalogs,setCatalogs]=useState<{subjects:SubjectRoot[];grades:CatalogItem[];topics:CatalogItem[];subtopics:CatalogItem[];skills:CatalogItem[]}>({subjects:[],grades:[],topics:[],subtopics:[],skills:[]}),[routes,setRoutes]=useState<AuthoringRoute[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[error,setError]=useState(""),[stage,setStage]=useState<"idle"|"creating"|"generating">("idle"),[sessionId,setSessionId]=useState("");
 const [form,setForm]=useState({subject_id:"",grade_id:"",topic_id:"",subtopic_id:"",skill_ids:[] as string[],difficulty:"50",task_type:"problem" as AuthoringCreateRequest["task_type"],answer_format:"number" as AuthoringCreateRequest["answer_format"],task_goal:"",generator:"",solver:""});
 useEffect(()=>{const c=new AbortController;Promise.all([getSubjectRoots(c.signal),getCatalog("grades",c.signal),getCatalog("topics",c.signal),getCatalog("subtopics",c.signal),getCatalog("skills",c.signal),getAuthoringRoutes(c.signal)]).then(([subjects,grades,topics,subtopics,skills,available])=>{if(!c.signal.aborted){setCatalogs({subjects:subjects.items,grades:grades.items,topics:topics.items,subtopics:subtopics.items,skills:skills.items});setRoutes(available.items);setForm(old=>({...old,generator:available.items[0]?key(available.items[0]):"",solver:available.items[0]?key(available.items[0]):""}))}}).catch(()=>!c.signal.aborted&&setLoadError("Не удалось загрузить справочники и маршруты провайдеров.")).finally(()=>!c.signal.aborted&&setLoading(false));return()=>c.abort()},[]);
 const topics=catalogs.topics.filter(x=>x.subject_id===form.subject_id&&x.grade_id===form.grade_id),subtopics=catalogs.subtopics.filter(x=>x.topic_id===form.topic_id),skills=catalogs.skills.filter(x=>x.topic_id===form.topic_id&&(!form.subtopic_id||x.subtopic_id===form.subtopic_id));
 const change=(name:string,value:string)=>setForm(old=>({...old,[name]:value,...(name==="subject_id"||name==="grade_id"?{topic_id:"",subtopic_id:"",skill_ids:[]}:name==="topic_id"?{subtopic_id:"",skill_ids:[]}:name==="subtopic_id"?{skill_ids:[]}:{}),...(name==="task_type"?{answer_format:formats[value as AuthoringCreateRequest["task_type"]][0]}:{})}));
 const selectedRoute=(value:string)=>routes.find(item=>key(item)===value)!;
 async function generate(id:string){setStage("generating");setError("");try{await runAuthoringSession(id,selectedRoute(form.generator),selectedRoute(form.solver));navigate(`/content-bank/authoring/sessions/${encodeURIComponent(id)}/workspace`)}catch(value){setError(apiMessage(value,"Провайдер не смог сгенерировать задание. Повторите запуск."));setStage("idle")}}
 async function submit(event:FormEvent){event.preventDefault();setError("");if(!form.skill_ids.length){setError("Выберите хотя бы один навык.");return}setStage("creating");try{const created=await createAuthoringSession({subject_id:form.subject_id,grade_id:form.grade_id,topic_id:form.topic_id,subtopic_id:form.subtopic_id||null,skill_ids:form.skill_ids,task_goal:form.task_goal.trim(),task_type:form.task_type,answer_format:form.answer_format,difficulty:Number(form.difficulty),pedagogical_constraints:[]});setSessionId(created.id);await generate(created.id)}catch(value){setError(apiMessage(value,"Не удалось создать авторскую сессию."));setStage("idle")}}
 if(loading)return <section className="loading-state" role="status"><h1>Новое AI-задание</h1><p>Загрузка формы…</p></section>;
 return <section className="authoring-create" aria-labelledby="authoring-create-title"><div className="page-heading"><div><h1 id="authoring-create-title">Новое AI-задание</h1><p>Опишите учебную цель и запустите генерацию</p></div></div>{loadError&&<div className="alert error" role="alert">{loadError}</div>}{error&&<div className="alert error" role="alert">{error}{sessionId&&<button type="button" onClick={()=>generate(sessionId)}>Повторить генерацию</button>}</div>}<form onSubmit={submit}><fieldset disabled={stage!=="idle"||!!sessionId}><legend>Классификация</legend><div className="form-grid"><Select label="Предмет" value={form.subject_id} onChange={v=>change("subject_id",v)} items={catalogs.subjects}/><Select label="Класс" value={form.grade_id} onChange={v=>change("grade_id",v)} items={catalogs.grades}/><Select label="Тема" value={form.topic_id} onChange={v=>change("topic_id",v)} items={topics}/><Select label="Подтема" required={false} value={form.subtopic_id} onChange={v=>change("subtopic_id",v)} items={subtopics}/><label>Навыки <span className="required-note">(обязательно)</span><select multiple required aria-label="Навыки" value={form.skill_ids} onChange={e=>{const skill_ids=Array.from(e.currentTarget.selectedOptions,x=>x.value);setForm(old=>({...old,skill_ids}))}}>{skills.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>Можно выбрать несколько навыков.</small></label></div></fieldset><fieldset disabled={stage!=="idle"||!!sessionId}><legend>Задание</legend><div className="form-grid"><label>Цель генерации <span className="required-note">(обязательно)</span><textarea required maxLength={2000} value={form.task_goal} onChange={e=>change("task_goal",e.target.value)}/></label><label>Сложность<input required aria-label="Сложность" type="number" min="1" max="100" value={form.difficulty} onChange={e=>change("difficulty",e.target.value)}/></label><label>Тип задания<select aria-label="Тип задания" value={form.task_type} onChange={e=>change("task_type",e.target.value)}>{Object.keys(formats).map(x=><option key={x}>{x}</option>)}</select></label><label>Формат ответа<select aria-label="Формат ответа" value={form.answer_format} onChange={e=>change("answer_format",e.target.value)}>{formats[form.task_type].map(x=><option key={x}>{x}</option>)}</select></label></div></fieldset><fieldset disabled={stage!=="idle"||!!sessionId}><legend>Маршруты провайдеров</legend><div className="form-grid"><RouteSelect label="Маршрут генератора" value={form.generator} routes={routes} onChange={v=>change("generator",v)}/><RouteSelect label="Маршрут решателя" value={form.solver} routes={routes} onChange={v=>change("solver",v)}/></div></fieldset><div className="form-actions"><button disabled={stage!=="idle"||!!loadError}>{stage==="creating"?"Создание сессии…":stage==="generating"?"Генерация…":"Создать и сгенерировать"}</button><a href="/content-bank" onClick={e=>{e.preventDefault();navigate("/content-bank")}}>Отмена</a></div></form></section>
}
function Select({label,value,onChange,items,required=true}:{label:string;value:string;onChange:(v:string)=>void;items:{id:string;name:string}[];required?:boolean}){return <label>{label}{required&&<span className="required-note"> (обязательно)</span>}<select required={required} aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">Выберите</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
function RouteSelect({label,value,routes,onChange}:{label:string;value:string;routes:AuthoringRoute[];onChange:(v:string)=>void}){return <label>{label}<select required aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{routes.map(x=><option key={key(x)} value={key(x)}>{x.provider_id} · {x.model_id}</option>)}</select></label>}
