import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {beforeEach,describe,expect,it,vi} from "vitest";
import * as api from "./api";
import {AuthoringCreatePage} from "./AuthoringCreatePage";

vi.mock("./api",async()=>{const actual=await vi.importActual<typeof import("./api")>("./api");return {...actual,getSubjectRoots:vi.fn(),getCatalog:vi.fn(),getAuthoringRoutes:vi.fn(),createAuthoringSession:vi.fn(),runAuthoringSession:vi.fn()}});
const mocked=vi.mocked(api);
beforeEach(()=>{vi.clearAllMocks();mocked.getSubjectRoots.mockResolvedValue({items:[{id:"subject",name:"Математика"}]});mocked.getCatalog.mockImplementation(async name=>({items:name==="grades"?[{id:"grade",name:"8 класс"}]:name==="topics"?[{id:"topic",name:"Алгебра",subject_id:"subject",grade_id:"grade"}]:name==="subtopics"?[{id:"subtopic",name:"Уравнения",topic_id:"topic"}]:[{id:"skill",name:"Решать уравнения",topic_id:"topic",subtopic_id:"subtopic"}]}));mocked.getAuthoringRoutes.mockResolvedValue({items:[{provider_id:"openai",model_id:"generator"},{provider_id:"anthropic",model_id:"solver"}]});mocked.createAuthoringSession.mockResolvedValue({id:"session-1",execution_status:"draft"});mocked.runAuthoringSession.mockResolvedValue({id:"session-1",execution_status:"succeeded"})});

async function ready(navigate=vi.fn()){render(<AuthoringCreatePage navigate={navigate}/>);await screen.findByRole("heading",{name:"Новое AI-задание"});await waitFor(()=>expect((screen.getByLabelText("Предмет") as HTMLSelectElement).disabled).toBe(false));return navigate}
async function fill(){const user=userEvent.setup();await user.selectOptions(screen.getByLabelText("Предмет"),"subject");await user.selectOptions(screen.getByLabelText("Класс"),"grade");await user.selectOptions(screen.getByLabelText("Тема"),"topic");await user.selectOptions(screen.getByLabelText("Подтема"),"subtopic");await user.selectOptions(screen.getByLabelText("Навыки"),"skill");await user.type(screen.getByLabelText(/Цель генерации/),"Создать задачу на квадратное уравнение");await user.selectOptions(screen.getByLabelText("Маршрут решателя"),"anthropic\u0000solver");return user}

describe("AuthoringCreatePage",()=>{
 it("renders every safe authoring field without internal controls",async()=>{await ready();for(const name of ["Предмет","Класс","Тема","Подтема","Навыки","Сложность","Тип задания","Формат ответа","Маршрут генератора","Маршрут решателя"])expect(screen.getByLabelText(name)).toBeTruthy();expect(screen.getByLabelText(/Цель генерации/)).toBeTruthy();expect(screen.queryByLabelText(/owner|fingerprint|prompt|pipeline/i)).toBeNull()});
 it("creates a safe session, runs it, and navigates to its workspace",async()=>{const navigate=await ready();const user=await fill();await user.click(screen.getByRole("button",{name:"Создать и сгенерировать"}));await waitFor(()=>expect(mocked.createAuthoringSession).toHaveBeenCalledTimes(1));expect(mocked.createAuthoringSession).toHaveBeenCalledWith({subject_id:"subject",grade_id:"grade",topic_id:"topic",subtopic_id:"subtopic",skill_ids:["skill"],task_goal:"Создать задачу на квадратное уравнение",task_type:"problem",answer_format:"number",difficulty:50,pedagogical_constraints:[]});expect(mocked.runAuthoringSession).toHaveBeenCalledWith("session-1",{provider_id:"openai",model_id:"generator"},{provider_id:"anthropic",model_id:"solver"});expect(navigate).toHaveBeenCalledWith("/content-bank/authoring/sessions/session-1/workspace")});
 it("shows validation errors and does not create a session",async()=>{await ready();const user=userEvent.setup();await user.click(screen.getByRole("button",{name:"Создать и сгенерировать"}));expect(mocked.createAuthoringSession).not.toHaveBeenCalled()});
 it("shows provider errors and retries the existing session without recreating it",async()=>{mocked.runAuthoringSession.mockRejectedValueOnce(new api.ApiError(502,"provider_failed","Провайдер недоступен"));await ready();const user=await fill();await user.click(screen.getByRole("button",{name:"Создать и сгенерировать"}));expect((await screen.findByRole("alert")).textContent).toContain("Провайдер недоступен");await user.click(screen.getByRole("button",{name:"Повторить генерацию"}));await waitFor(()=>expect(mocked.runAuthoringSession).toHaveBeenCalledTimes(2));expect(mocked.createAuthoringSession).toHaveBeenCalledTimes(1)});
});
