import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen} from "@testing-library/react";
import {AuthoringWorkspacePage} from "./AuthoringWorkspacePage";
import {ApiError,type AuthoringWorkspaceViewV1} from "./api";
import * as api from "./api";

const fixture:AuthoringWorkspaceViewV1={schema_version:"authoring_workspace_view.v1",session:{id:"session-secret-id",owner:"owner-secret-id",lifecycle_status:"ready",created_at:"2026-08-23T10:00:00Z"},generation:{generated_draft_available:true,generator_route:{provider_id:"safe-provider",model_id:"safe-model"},generator_attempt_status:"succeeded"},solver:{solver_status:"solvable",validation_status:"validated",semantic_result:{status:"validated"}},review:{current_revision:3,revision_count:2,reviewer_state:"in_review",latest_changes_summary:{changed_fields:["title","statement"]}},quality:{quality_status:"warnings",blocking_findings:[{code:"answer_missing",message:"Добавьте ответ"}],warnings:[{code:"hint_short",message:"Расширьте подсказку"}],override_state:{overridden:false,reason:null,warning_codes:[]}},acceptance:{accepted_revision:{id:"revision-secret-id",revision_number:2},promoted_task_reference:{task_id:"task-secret-id",task_version_id:"version-secret-id"}},diagnostics:{attempt_count:4,total_cost_by_currency:[{currency:"USD",amount:"12.50"}],provider_usage_summary:[]}};
afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe("AuthoringWorkspacePage",()=>{
 it("renders the workspace and every read-only section from the fixture",async()=>{vi.spyOn(api,"getAuthoringWorkspace").mockResolvedValue(fixture);render(<AuthoringWorkspacePage sessionId="session-1"/>);expect(await screen.findByText("ready")).toBeTruthy();for(const heading of ["Сессия","Генерация","Решение","Рецензирование","Качество","Приёмка"])expect(screen.getByRole("heading",{name:heading})).toBeTruthy();expect(screen.getByText("answer_missing")).toBeTruthy();expect(screen.getByText(/changed_fields: title, statement/)).toBeTruthy();expect(screen.queryByRole("button",{name:/принять/i})).toBeNull()});
 it("never renders sensitive payloads, costs, or internal identifiers",async()=>{vi.spyOn(api,"getAuthoringWorkspace").mockResolvedValue({...fixture,prompt:"hidden prompt",raw_provider_data:"raw response",solver_reasoning:"secret reasoning"} as AuthoringWorkspaceViewV1);const {container}=render(<AuthoringWorkspacePage sessionId="session-1"/>);await screen.findByText("ready");const text=container.textContent??"";for(const secret of ["hidden prompt","raw response","secret reasoning","12.50","session-secret-id","owner-secret-id","revision-secret-id","task-secret-id","version-secret-id"])expect(text).not.toContain(secret)});
 it("shows a loading state",()=>{vi.spyOn(api,"getAuthoringWorkspace").mockReturnValue(new Promise(()=>{}));render(<AuthoringWorkspacePage sessionId="session-1"/>);expect(screen.getByRole("status").textContent).toContain("Загрузка рабочего пространства")});
 it("shows the API error state",async()=>{vi.spyOn(api,"getAuthoringWorkspace").mockRejectedValue(new ApiError(500,"unexpected_error","boom"));render(<AuthoringWorkspacePage sessionId="session-1"/>);expect((await screen.findByRole("alert")).textContent).toContain("Не удалось загрузить авторское рабочее пространство.");expect(screen.getByRole("button",{name:"Повторить"})).toBeTruthy()});
 it("shows the not-ready state for an empty projection",async()=>{vi.spyOn(api,"getAuthoringWorkspace").mockResolvedValue({...fixture,generation:{generated_draft_available:false,generator_route:null,generator_attempt_status:null},solver:{solver_status:null,validation_status:null,semantic_result:null},review:{current_revision:null,revision_count:0,reviewer_state:"not_started",latest_changes_summary:{}},quality:{...fixture.quality,quality_status:"not_available",blocking_findings:[],warnings:[]}});render(<AuthoringWorkspacePage sessionId="session-1"/>);expect(await screen.findByRole("heading",{name:"Рабочее пространство ещё не готово"})).toBeTruthy()});
});
