import {useCallback,useEffect,useMemo,useState} from "react";
import {ApiError,createAuthoringReviewRevision,getAuthoringReview,getAuthoringReviewHistory,type AuthoringReviewDraft,type AuthoringReviewResponse} from "./api";

const clone=(draft:AuthoringReviewDraft):AuthoringReviewDraft=>structuredClone(draft);
export function AuthoringReviewEditor({sessionId,onSaved}:{sessionId:string;onSaved?:()=>void}){
 const [review,setReview]=useState<AuthoringReviewResponse>();const [draft,setDraft]=useState<AuthoringReviewDraft>();const [artifact,setArtifact]=useState<AuthoringReviewDraft>();const [revision,setRevision]=useState<number>();const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [conflict,setConflict]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");setConflict(false);try{const [next,history]=await Promise.all([getAuthoringReview(sessionId),getAuthoringReviewHistory(sessionId)]);setReview(next);setDraft(clone(next.draft));setArtifact(old=>old??clone(next.draft));setRevision(history.current_revision)}catch(e){setError(e instanceof ApiError&&e.status===409?"Рецензирование ещё не начато.":"Не удалось загрузить редактор рецензии.")}finally{setLoading(false)}},[sessionId]);
 useEffect(()=>{void load()},[load]);
 const dirty=useMemo(()=>!!review&&!!draft&&JSON.stringify(review.draft)!==JSON.stringify(draft),[review,draft]);
 const errors=!draft?{}:{statement:draft.statement.trim()?"":"Условие обязательно.",answer:draft.expected_answer.trim()?"":"Ожидаемый ответ обязателен.",solution:draft.solution.trim()?"":"Решение обязательно.",choices:draft.choice_options.some(x=>!x.content.trim())?"Заполните все варианты ответа.":""};
 const invalid=Object.values(errors).some(Boolean);
 const field=(name:keyof AuthoringReviewDraft,value:unknown)=>setDraft(old=>old?{...old,[name]:value}:old);
 async function save(){if(!review||!draft||invalid||!dirty)return;setSaving(true);setError("");setConflict(false);try{const next=await createAuthoringReviewRevision(sessionId,review.version,draft);const history=await getAuthoringReviewHistory(sessionId);setReview(next);setDraft(clone(next.draft));setRevision(history.current_revision);onSaved?.()}catch(e){if(e instanceof ApiError&&e.status===409&&e.code==="authoring_review_version_conflict")setConflict(true);else if(e instanceof ApiError&&Array.isArray(e.details)){setError(e.details.map(x=>x.message??String(x)).join("; ")||e.message)}else setError("Не удалось сохранить новую редакцию.")}finally{setSaving(false)}}
 if(loading)return <section className="workspace-panel" role="status">Загрузка редактора…</section>;
 if(!draft||!review||!artifact)return <section className="workspace-panel"><h2>Редактор</h2>{error&&<div className="alert error" role="alert">{error}</div>}</section>;
 return <><section className="workspace-panel artifact-panel"><h2>AI-артефакт</h2><h3>{artifact.title||"Без названия"}</h3><p className="artifact-statement">{artifact.statement}</p><dl><dt>Варианты</dt><dd>{artifact.choice_options.length?artifact.choice_options.map(x=>`${x.key}: ${x.content}`).join(" · "):"—"}</dd><dt>Ожидаемый ответ</dt><dd>{artifact.expected_answer}</dd><dt>Решение</dt><dd>{artifact.solution}</dd><dt>Подсказки</dt><dd>{artifact.hints.join(" · ")||"—"}</dd></dl></section><section className="workspace-panel review-editor"><h2>Редактор</h2><p><strong>Редакция № {revision}</strong> · {dirty?"Есть несохранённые изменения":"Все изменения сохранены"}</p>{conflict&&<div className="alert error" role="alert">Контент был изменён в другой сессии<button type="button" onClick={load}>Перезагрузить</button></div>}{error&&<div className="alert error" role="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();void save()}}><label>Название<input value={draft.title??""} onChange={e=>field("title",e.target.value||null)}/></label><label>Условие<textarea aria-invalid={!!errors.statement} value={draft.statement} onChange={e=>field("statement",e.target.value)}/>{errors.statement&&<span className="field-error">{errors.statement}</span>}</label><fieldset><legend>Варианты ответа</legend>{draft.choice_options.map((option,index)=><label key={option.key}>Вариант {option.key}<input aria-invalid={!option.content.trim()} value={option.content} onChange={e=>field("choice_options",draft.choice_options.map((x,i)=>i===index?{...x,content:e.target.value}:x))}/></label>)}</fieldset>{errors.choices&&<span className="field-error">{errors.choices}</span>}<label>Ожидаемый ответ<textarea aria-invalid={!!errors.answer} value={draft.expected_answer} onChange={e=>field("expected_answer",e.target.value)}/>{errors.answer&&<span className="field-error">{errors.answer}</span>}</label><label>Решение<textarea aria-invalid={!!errors.solution} value={draft.solution} onChange={e=>field("solution",e.target.value)}/>{errors.solution&&<span className="field-error">{errors.solution}</span>}</label><fieldset><legend>Подсказки</legend>{draft.hints.map((hint,index)=><label key={index}>Подсказка {index+1}<textarea value={hint} onChange={e=>field("hints",draft.hints.map((x,i)=>i===index?e.target.value:x))}/></label>)}</fieldset><button type="submit" disabled={!dirty||invalid||saving}>{saving?"Сохранение…":"Сохранить новую редакцию"}</button></form></section></>;
}
