import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from "react";
import {ApiError,request,setUnauthorizedHandler} from "./api";

export type Principal={user_id:string;login:string;display_name:string;roles:string[];capabilities:string[];student_id:string|null};
export type AuthStatus="loading"|"authenticated"|"anonymous"|"error";
type AuthValue={status:AuthStatus;principal:Principal|null;error:string;login:(login:string,password:string)=>Promise<void>;logout:()=>Promise<void>;refreshPrincipal:()=>Promise<Principal>;becomeAnonymous:()=>void};
const AuthContext=createContext<AuthValue|null>(null);
export const hasCapability=(principal:Principal|null|undefined,capability:string)=>!!principal?.capabilities.includes(capability);
export const landingFor=(principal:Principal)=>hasCapability(principal,"student.assignments.read")?"/student/assignments":hasCapability(principal,"content.read")?"/content-bank":hasCapability(principal,"image_solving.use")?"/image-solving/new":hasCapability(principal,"assessment.manage")?"/assessments":hasCapability(principal,"users.manage")?"/admin/users":"/no-access";

export function AuthProvider({children}:{children:ReactNode}){const [status,setStatus]=useState<AuthStatus>("loading"),[principal,setPrincipal]=useState<Principal|null>(null),[error,setError]=useState("");const becomeAnonymous=useCallback(()=>{setPrincipal(null);setStatus("anonymous");setError("")},[]);const refreshPrincipal=useCallback(async()=>{const value=await request<Principal>("/api/auth/me");setPrincipal(value);setStatus("authenticated");setError("");return value},[]);useEffect(()=>{setUnauthorizedHandler(becomeAnonymous);refreshPrincipal().catch(e=>{if(e instanceof ApiError&&e.status===401)becomeAnonymous();else{setPrincipal(null);setStatus("error");setError("Не удалось связаться с сервером. Попробуйте ещё раз.")}});return()=>setUnauthorizedHandler()},[becomeAnonymous,refreshPrincipal]);const login=useCallback(async(login:string,password:string)=>{const value=await request<Principal>("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({login,password})});setPrincipal(value);setStatus("authenticated");setError("")},[]);const logout=useCallback(async()=>{try{await request("/api/auth/logout",{method:"POST"})}catch(e){if(!(e instanceof ApiError&&e.status===401))throw e}finally{becomeAnonymous()}},[becomeAnonymous]);const value=useMemo(()=>({status,principal,error,login,logout,refreshPrincipal,becomeAnonymous}),[status,principal,error,login,logout,refreshPrincipal,becomeAnonymous]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const value=useContext(AuthContext);if(!value)throw new Error("useAuth must be used within AuthProvider");return value}
