import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {AuthoringReviewEditor} from "./AuthoringReviewEditor";
import {ApiError,type AuthoringReviewResponse} from "./api";
import * as api from "./api";

const review:AuthoringReviewResponse={schema_version:"authoring_review_response.v1",session_id:"session-1",state:"reviewing",version:2,created_at:"2026-08-23T10:00:00Z",updated_at:"2026-08-23T10:00:00Z",draft:{schema_version:"authoring_review_draft.v1",title:"Исходное название",statement:"Исходное условие",task_type:"test",answer_format:"single_choice",choice_options:[{key:"a",content:"Первый"},{key:"b",content:"Второй"}],expected_answer:"a",solution:"Решение",hints:["Подсказка"]}};
const history=(current_revision=1)=>({schema_version:"authoring_review_history.v1" as const,session_id:"session-1",current_revision,accepted_revision_id:null,revisions:[{revision_number:current_revision}]});
function arrange(){vi.spyOn(api,"getAuthoringReview").mockResolvedValue(review);vi.spyOn(api,"getAuthoringReviewHistory").mockResolvedValue(history());return render(<AuthoringReviewEditor sessionId="session-1"/>)}
afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe("AuthoringReviewEditor",()=>{
 it("renders editable review content without protected fields",async()=>{arrange();expect(await screen.findByRole("heading",{name:"Редактор"})).toBeTruthy();expect(screen.getByLabelText("Название")).toBeTruthy();for(const protectedLabel of ["Тип задания","Формат ответа","Предмет","Класс","Тема","Подтема","Навыки","Сложность","Провайдер"])expect(screen.queryByLabelText(protectedLabel)).toBeNull()});
 it("edits title and statement and reports unsaved changes",async()=>{arrange();const user=userEvent.setup();await user.clear(await screen.findByLabelText("Название"));await user.type(screen.getByLabelText("Название"),"Новое название");await user.clear(screen.getByLabelText(/^Условие/));await user.type(screen.getByLabelText(/^Условие/),"Новое условие");expect(document.body.textContent).toContain("Есть несохранённые изменения")});
 it("saves a revision and updates its number",async()=>{arrange();const saved={...review,version:3,draft:{...review.draft,title:"Новое название"}};const save=vi.spyOn(api,"createAuthoringReviewRevision").mockResolvedValue(saved);const user=userEvent.setup();await user.clear(await screen.findByLabelText("Название"));await user.type(screen.getByLabelText("Название"),"Новое название");vi.mocked(api.getAuthoringReviewHistory).mockResolvedValue(history(2));await user.click(screen.getByRole("button",{name:"Сохранить новую редакцию"}));await waitFor(()=>expect(save).toHaveBeenCalledWith("session-1",2,expect.objectContaining({title:"Новое название",statement:"Исходное условие"})));expect(await screen.findByText("Редакция № 2",{exact:false})).toBeTruthy()});
 it("shows a version conflict and lets the reviewer reload",async()=>{arrange();vi.spyOn(api,"createAuthoringReviewRevision").mockRejectedValue(new ApiError(409,"authoring_review_version_conflict","conflict"));const user=userEvent.setup();await user.clear(await screen.findByLabelText("Название"));await user.type(screen.getByLabelText("Название"),"Конфликт");await user.click(screen.getByRole("button",{name:"Сохранить новую редакцию"}));expect((await screen.findByRole("alert")).textContent).toContain("Контент был изменён в другой сессии");await user.click(screen.getByRole("button",{name:"Перезагрузить"}));await waitFor(()=>expect(api.getAuthoringReview).toHaveBeenCalledTimes(2))});
});
