import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {AuthoringRevisionHistory} from "./AuthoringRevisionHistory";
import {ApiError,type AuthoringReviewHistory} from "./api";
import * as api from "./api";
const snapshot={schema_version:"authoring_review_draft.v1" as const,title:"Секретный снимок",statement:"Условие",task_type:"single_choice",answer_format:"choice",choice_options:[],expected_answer:"A",solution:"Решение",hints:[]};
const history:AuthoringReviewHistory={schema_version:"authoring_review_history.v1",session_id:"session-secret",current_revision:2,accepted_revision_id:null,revisions:[{id:"revision-secret-0",revision_number:0,snapshot,created_at:"2026-08-23T10:00:00Z",actor_id:"Автор 1",change_summary:{source:"provider-secret",changed_fields:[]}},{id:"revision-secret-2",revision_number:2,snapshot,created_at:"2026-08-23T11:00:00Z",actor_id:"Автор 2",change_summary:{source:"hidden-prompt",changed_fields:["title","statement"],provider_data:"raw-secret"}}]};
afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe("AuthoringRevisionHistory",()=>{
 it("renders the safe timeline and latest revision diff",async()=>{vi.spyOn(api,"getAuthoringReviewHistory").mockResolvedValue(history);vi.spyOn(api,"getAuthoringReviewDiff").mockResolvedValue({schema_version:"authoring_review_diff.v1",session_id:"session-secret",from_revision:0,to_revision:2,changes:[{field:"title",from:"До",to:"После"},{field:"hints",from:["Старая"],to:["Новая"]}]});const {container}=render(<AuthoringRevisionHistory sessionId="session-1"/>);expect(await screen.findByRole("button",{name:"Редакция № 2"})).toBeTruthy();expect(screen.getByText(/Название, Условие/)).toBeTruthy();expect((await screen.findAllByText("После")).length).toBeGreaterThan(1);expect(screen.getByText("Старая")).toBeTruthy();const text=container.textContent??"";for(const secret of ["Секретный снимок","provider-secret","hidden-prompt","raw-secret","revision-secret-0","session-secret"])expect(text).not.toContain(secret)});
 it("selects a revision and shows the single-revision state",async()=>{vi.spyOn(api,"getAuthoringReviewHistory").mockResolvedValue(history);const diff=vi.spyOn(api,"getAuthoringReviewDiff").mockResolvedValue({schema_version:"authoring_review_diff.v1",session_id:"x",from_revision:0,to_revision:2,changes:[]});const user=userEvent.setup();render(<AuthoringRevisionHistory sessionId="session-1"/>);await user.click(await screen.findByRole("button",{name:"Редакция № 0"}));expect(screen.getByText("Для сравнения нужны как минимум две редакции.")).toBeTruthy();await waitFor(()=>expect(screen.getByRole("button",{name:"Редакция № 0"}).getAttribute("aria-pressed")).toBe("true"));expect(diff).toHaveBeenCalledTimes(1)});
 it("handles no revisions and API errors",async()=>{vi.spyOn(api,"getAuthoringReviewHistory").mockResolvedValueOnce({...history,current_revision:0,revisions:[]});const {unmount}=render(<AuthoringRevisionHistory sessionId="session-1"/>);expect(await screen.findByText("Редакций пока нет.")).toBeTruthy();unmount();vi.mocked(api.getAuthoringReviewHistory).mockRejectedValue(new ApiError(500,"error","boom"));render(<AuthoringRevisionHistory sessionId="session-2"/>);expect((await screen.findByRole("alert")).textContent).toContain("Не удалось загрузить историю")});
 it("reports an invalid revision pair",async()=>{vi.spyOn(api,"getAuthoringReviewHistory").mockResolvedValue(history);vi.spyOn(api,"getAuthoringReviewDiff").mockRejectedValue(new ApiError(404,"authoring_review_revision_not_found","missing"));render(<AuthoringRevisionHistory sessionId="session-1"/>);expect((await screen.findByRole("alert")).textContent).toContain("недопустимая пара")});
});
