import {useEffect,useId,useRef,useState} from "react";
import {getCatalogOptions,type CatalogOption} from "./api";

type Props={label:string;kind:"subjects"|"topics"|"subtopics"|"skills";parents:Record<string,string>;
 value:CatalogOption|null;recognized?:string;recommended?:CatalogOption[];disabled?:boolean;canCreate?:boolean;
 createLabel:string;onSelect:(value:CatalogOption)=>void;onCreate:(name:string)=>Promise<CatalogOption>};
const normalize=(value:string)=>value.normalize("NFKC").trim().toLocaleLowerCase("ru-RU").replace(/\s+/g," ");

export function CatalogCombobox(p:Props){const id=useId(),[open,setOpen]=useState(false),[query,setQuery]=useState(p.value?.name??p.recognized??""),[items,setItems]=useState<CatalogOption[]>([]),[active,setActive]=useState(0),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),timer=useRef<number|undefined>(undefined),request=useRef<AbortController|undefined>(undefined);
 useEffect(()=>{setQuery(p.value?.name??p.recognized??"");setItems([]);setOpen(false)},[p.kind,JSON.stringify(p.parents)]);
 useEffect(()=>{if(!open||p.disabled)return;window.clearTimeout(timer.current);request.current?.abort();timer.current=window.setTimeout(()=>{const c=new AbortController();request.current=c;getCatalogOptions(p.kind,{...p.parents,q:query},c.signal).then(x=>{if(!c.signal.aborted){const recommended=(p.recommended??[]).filter(r=>!x.items.some(i=>i.id===r.id));setItems([...recommended,...x.items]);setActive(0)}}).catch(()=>{});},200);return()=>{window.clearTimeout(timer.current);request.current?.abort()}},[open,query,p.kind,JSON.stringify(p.parents)]);
 const exact=items.some(x=>normalize(x.name)===normalize(query)),mayCreate=!!p.canCreate&&!!query.trim()&&!exact&&!p.disabled;
 const choose=(item:CatalogOption)=>{p.onSelect(item);setQuery(item.name);setOpen(false);setConfirm(false)};
 const key=(e:React.KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);setConfirm(false)}else if(e.key==="ArrowDown"){e.preventDefault();setOpen(true);setActive(x=>Math.min(x+1,items.length-1))}else if(e.key==="ArrowUp"){e.preventDefault();setActive(x=>Math.max(0,x-1))}else if(e.key==="Enter"&&open&&items[active]){e.preventDefault();choose(items[active])}};
 const create=async()=>{setBusy(true);try{choose(await p.onCreate(query.trim()))}finally{setBusy(false)}};
 return <div className="catalog-combobox"><label htmlFor={`${id}-input`}>{p.label}</label><input id={`${id}-input`} role="combobox" aria-expanded={open} aria-controls={`${id}-list`} aria-autocomplete="list" disabled={p.disabled} value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} onKeyDown={key}/>{p.recognized&&<small>Распознано: «{p.recognized}»</small>}{open&&<div id={`${id}-list`} role="listbox" className="catalog-options">{(p.recommended?.length??0)>0&&<strong>Рекомендовано</strong>}{items.map((item,index)=><button type="button" role="option" aria-selected={index===active} className={index===active?"active":""} key={item.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(item)}>{item.name}{item.status==="provisional"&&<small> · предложено</small>}</button>)}{mayCreate&&!confirm&&<button type="button" className="catalog-create" onClick={()=>setConfirm(true)}>+ {p.createLabel} «{query.trim()}»</button>}{mayCreate&&confirm&&<div className="catalog-create-confirm" role="dialog" aria-label={`${p.createLabel}?`}><strong>{p.createLabel}?</strong><span>Название: {query.trim()}</span><div><button type="button" className="secondary" onClick={()=>setConfirm(false)}>Отмена</button><button type="button" disabled={busy} onClick={create}>{busy?"Добавляем…":"Добавить"}</button></div></div>}{!items.length&&!mayCreate&&<small>Подходящих значений нет</small>}</div>}</div>}
