// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";import {cleanup,render,screen,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {CreateForm,type Catalogs} from "./main";
const catalogs:Catalogs={subjects:[{id:"s1",name:"Математика"},{id:"s2",name:"Физика"}],grades:[{id:"g",name:"7"}],topics:[{id:"t1",name:"Алгебра",subject_id:"s1",grade_id:"g"},{id:"t2",name:"Механика",subject_id:"s2",grade_id:"g"}],subtopics:[],skills:[{id:"sk1",name:"Решение",topic_id:"t1"},{id:"sk2",name:"Расчёт",topic_id:"t2"}]};
const tag=(id:string,name:string,subject:string|null)=>({id,name,normalized_name:name.toLowerCase(),category:{code:"exam",name:"Экзамен",sort_order:1},subject:subject?{id:subject,name:subject==="s1"?"Математика":"Физика"}:null,status:"active",replacement:null,created_at:"",created_by:"",updated_at:"",updated_by:""});const json=(x:any,status=200)=>Promise.resolve(new Response(JSON.stringify(x),{status,headers:{"Content-Type":"application/json",Location:"/api/content-bank/tasks/new"}}));
function server(){const calls:{url:string;init?:RequestInit}[]=[];vi.stubGlobal("fetch",vi.fn((input:any,init?:RequestInit)=>{const url=String(input);calls.push({url,init});if(url.includes("/tags?")){const sid=new URL(url).searchParams.get("subject_id");return json({items:sid==="s1"?[tag("global","ОГЭ",null),tag("math","Алгебраический","s1")]:[tag("global","ОГЭ",null),tag("physics","Практика","s2")],total:2,offset:0,limit:50})}if(url.endsWith("check-duplicates"))return json({has_likely_duplicates:false,items:[]});return json({id:"new",duplicate_warnings:[]},201)}));return calls}
async function fill(subject="s1"){await userEvent.selectOptions(screen.getByLabelText(/Предмет/),subject);await userEvent.selectOptions(screen.getByLabelText(/Класс/),"g");await userEvent.selectOptions(screen.getByLabelText(/Тема/),subject==="s1"?"t1":"t2");await userEvent.selectOptions(screen.getByLabelText(/Основной навык/),subject==="s1"?"sk1":"sk2");await userEvent.type(screen.getByLabelText(/Условие/),"Условие")}
async function pick(name:string){const input=screen.getByRole("combobox",{name:"Поиск: Теги"});await userEvent.type(input,name[0]);await userEvent.click(await screen.findByRole("option",{name:new RegExp(name)}))}
afterEach(()=>{cleanup();vi.restoreAllMocks()});describe("create task tags integration",()=>{
 it("runs duplicate check then creates with exact canonical tag_ids",async()=>{const calls=server();render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await pick("ОГЭ");await pick("Алгебраический");await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByRole("status");const mutations=calls.filter(x=>x.url.endsWith("check-duplicates")||x.url.endsWith("/tasks"));expect(mutations.map(x=>x.url.split("/").at(-1))).toEqual(["check-duplicates","tasks"]);const body=JSON.parse(String(mutations[1].init?.body));expect(body.tag_ids).toEqual(["global","math"]);expect(body.role).toBeUndefined();expect(body.actor).toBeUndefined();expect(JSON.stringify(body)).not.toContain("Алгебраический")},10000);
 it("creates without tags using schema-compatible empty array",async()=>{const calls=server();render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByText("Задание создано.",{exact:false});expect(JSON.parse(String(calls.find(x=>x.url.endsWith("/tasks"))!.init?.body)).tag_ids).toEqual([])});
 it("subject change keeps global, removes incompatible scoped tag and excludes it from payload",async()=>{const calls=server();render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await pick("ОГЭ");await pick("Алгебраический");await userEvent.selectOptions(screen.getByLabelText(/Предмет/),"s2");expect(await screen.findByText(/Несовместимые.*сняты/)).toBeTruthy();expect(screen.getByText("ОГЭ")).toBeTruthy();expect(screen.queryByText("Алгебраический")).toBeNull();await userEvent.selectOptions(screen.getByLabelText(/Класс/),"g");await userEvent.selectOptions(screen.getByLabelText(/Тема/),"t2");await userEvent.selectOptions(screen.getByLabelText(/Основной навык/),"sk2");await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByText("Задание создано.",{exact:false});expect(JSON.parse(String(calls.find(x=>x.url.endsWith("/tasks"))!.init?.body)).tag_ids).toEqual(["global"])});
 it("double submit produces one task request while preserving selected tags",async()=>{const calls=server();render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await pick("ОГЭ");await userEvent.dblClick(screen.getByRole("button",{name:"Создать задание"}));await waitFor(()=>expect(calls.filter(x=>x.url.endsWith("/tasks"))).toHaveLength(1));expect(JSON.parse(String(calls.find(x=>x.url.endsWith("/tasks"))!.init?.body)).tag_ids).toEqual(["global"])});
});
