import {afterEach,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {CreateForm,type Catalogs} from "./main";
const catalogs:Catalogs={subjects:[{id:"subject",name:"Math"}],grades:[{id:"grade",name:"7"}],topics:[{id:"topic",name:"Motion",subject_id:"subject",grade_id:"grade"}],subtopics:[],skills:[{id:"skill",name:"Solve",topic_id:"topic"},{id:"skill-2",name:"Explain",topic_id:"topic"}]};
const candidate={task_id:"other",task_version_id:"other-v",version_no:2,title:"Similar",status:"approved",statement:"Find x quickly",statement_similarity:.91,same_primary_skill:true,same_final_answer:false,reasons:["high_statement_similarity","same_primary_skill"]};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",Location:"/api/content-bank/tasks/new"}});
async function fill(){await userEvent.selectOptions(screen.getByLabelText(/Предмет/),"subject");await userEvent.selectOptions(screen.getByLabelText(/Класс/),"grade");await userEvent.selectOptions(screen.getByLabelText(/Тема/),"topic");await userEvent.selectOptions(screen.getByLabelText(/Основной навык/),"skill");await userEvent.type(screen.getByLabelText(/Условие/),"Find x")}
afterEach(()=>{cleanup();vi.restoreAllMocks()});
it("checks before create, renders candidates, and only creates after explicit override",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockImplementation(input=>Promise.resolve(String(input).endsWith("check-duplicates")?json({has_likely_duplicates:true,items:[candidate]}):json({id:"new",duplicate_warnings:[candidate]},201)));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));expect(await screen.findByText("Similar")).toBeTruthy();expect(fetch).toHaveBeenCalledTimes(1);await userEvent.click(screen.getByRole("button",{name:"Создать всё равно"}));expect((await screen.findByRole("status")).textContent).toContain("Задание создано");expect(fetch).toHaveBeenCalledTimes(2)});
it("invalidates duplicate results after statement changes",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(()=>Promise.resolve(json({has_likely_duplicates:true,items:[candidate]})));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByText("Similar");await userEvent.type(screen.getByLabelText(/Условие/)," changed");expect(screen.queryByRole("button",{name:"Создать всё равно"})).toBeNull()});
it("ignores a stale duplicate response",async()=>{let resolve!:(r:Response)=>void;vi.spyOn(globalThis,"fetch").mockImplementation(()=>new Promise(r=>{resolve=r}));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await userEvent.type(screen.getByLabelText(/Условие/)," changed");resolve(json({has_likely_duplicates:true,items:[candidate]}));await waitFor(()=>expect(screen.queryByText("Similar")).toBeNull())});
it("protects forced create from a double click and focuses the result",async()=>{let checks=0;const fetch=vi.spyOn(globalThis,"fetch").mockImplementation(input=>Promise.resolve(String(input).endsWith("check-duplicates")?json({has_likely_duplicates:true,items:[candidate]}):(checks++,json({id:"new",duplicate_warnings:[]},201))));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByText("Similar");await userEvent.dblClick(screen.getByRole("button",{name:"Создать всё равно"}));const status=await screen.findByRole("status");expect(checks).toBe(1);expect(document.activeElement).toBe(status);expect(fetch).toHaveBeenCalledTimes(2)});
it("returns focus to the form when duplicate editing is selected",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(()=>Promise.resolve(json({has_likely_duplicates:true,items:[candidate]})));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByText("Similar");await userEvent.click(screen.getByRole("button",{name:"Вернуться к редактированию"}));expect(document.activeElement).toBe(screen.getByLabelText(/Предмет/))});

it("creates only after an empty duplicate check, in strict request order",async()=>{const order:string[]=[];vi.spyOn(globalThis,"fetch").mockImplementation(input=>{const url=String(input);order.push(url.endsWith("check-duplicates")?"check-duplicates":"create");return Promise.resolve(url.endsWith("check-duplicates")?json({has_likely_duplicates:false,items:[]}):json({id:"new",duplicate_warnings:[]},201))});render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByRole("status");expect(order).toEqual(["check-duplicates","create"])});
it("shows a duplicate-check error, does not create, and checks again on retry",async()=>{let checks=0,creates=0;const fetch=vi.spyOn(globalThis,"fetch").mockImplementation(input=>{if(String(input).endsWith("check-duplicates")){checks++;return Promise.resolve(checks===1?json({error:{code:"unavailable",message:"Проверка недоступна"}},503):json({has_likely_duplicates:false,items:[]}))}creates++;return Promise.resolve(json({id:"new",duplicate_warnings:[]},201))});render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));expect((await screen.findByRole("alert")).textContent).toContain("Проверка недоступна");expect(creates).toBe(0);await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByRole("status");expect(checks).toBe(2);expect(creates).toBe(1);expect(fetch).toHaveBeenCalledTimes(3)});
it("invalidates candidates and override permission when the primary skill changes",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(()=>Promise.resolve(json({has_likely_duplicates:true,items:[candidate]})));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByText("Similar");await userEvent.selectOptions(screen.getByLabelText(/Основной навык/),"skill-2");expect(screen.queryByText("Similar")).toBeNull();expect(screen.queryByRole("button",{name:"Создать всё равно"})).toBeNull()});
it("renders backend create warnings after an empty pre-check",async()=>{let call=0;vi.spyOn(globalThis,"fetch").mockImplementation(()=>Promise.resolve(++call===1?json({has_likely_duplicates:false,items:[]}):json({id:"new",duplicate_warnings:[candidate]},201)));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));await screen.findByRole("status");expect(screen.getByText("Similar")).toBeTruthy()});
it("renders a nullable title and unknown future reason safely",async()=>{const future={...candidate,title:null,reasons:["future_reason"]};vi.spyOn(globalThis,"fetch").mockImplementation(()=>Promise.resolve(json({has_likely_duplicates:true,items:[future]})));render(<CreateForm catalogs={catalogs} onCreated={()=>{}} navigate={()=>{}}/>);await fill();await userEvent.click(screen.getByRole("button",{name:"Создать задание"}));expect(await screen.findByRole("link",{name:"Без названия"})).toBeTruthy();expect(screen.getByText(/future_reason/)).toBeTruthy()});
