import {FormEvent,useCallback,useEffect,useMemo,useRef,useState} from "react";
import {FolderDialog,type FolderDialogAction} from "./FolderDialog";
import {ApiError,getCatalog,getFolderTree,getLevelContents,getSubjectRoots,type CatalogItem,type Folder,type FolderNode,type LevelContents,type SubjectRoot} from "./api";
import {TagChips} from "./TagPicker";
import {TagFilter,normalizeTagParams,uniqueTagIds} from "./TagFilter";

const messages:Record<string,string>={folder_not_found:"Папка не найдена.",subject_not_found:"Предмет не найден.",folder_name_invalid:"Проверьте название папки.",folder_name_conflict:"Папка с таким названием уже существует на этом уровне.",folder_subject_mismatch:"Нельзя использовать папку другого предмета.",folder_cycle:"Нельзя переместить папку в себя или её потомка.",folder_max_depth_exceeded:"Максимальная глубина — 8 уровней.",folder_not_empty:"Удалить можно только пустую папку.",task_folder_subject_mismatch:"Нельзя переместить задание в другой предмет.",folder_concurrent_modification:"Данные уже изменились на сервере. Обновите содержимое и повторите действие.",task_not_found:"Задание не найдено."};
const errorText=(e:unknown)=>e instanceof ApiError?(messages[e.code]||e.message||"Не удалось выполнить действие."):"Не удалось выполнить действие.";
const flatten=(nodes:FolderNode[]):FolderNode[]=>nodes.flatMap(n=>[n,...flatten(n.children)]);
const filterNames={grade_id:"Класс",topic_id:"Тема",subtopic_id:"Подтема",skill_id:"Навык",task_type:"Тип",difficulty:"Сложность",status:"Статус",tags:"Теги"} as const;
type FilterKey=keyof typeof filterNames; type Values=Record<string,string>;
const taskTypes=["test","calculation","problem","open_question","essay"],statuses=["draft","review","approved","archived"];
const queryKeys=["grade_id","topic_id","subtopic_id","skill_id","task_type","difficulty_min","difficulty_max","status","q","offset","limit","sort_by","sort_order"];
const sortFields=["relevance","created_at","updated_at","title","difficulty","status","version_no"],sortOrders=["asc","desc"];
const initialQuery=()=>new URLSearchParams(location.search);
const initialValues=()=>{const p=initialQuery(),values=Object.fromEntries(queryKeys.map(k=>[k,p.get(k)??""])) as Values;if(values.task_type&&!taskTypes.includes(values.task_type))values.task_type="";if(values.status&&!statuses.includes(values.status))values.status="";if(values.sort_by&&!sortFields.includes(values.sort_by))values.sort_by="";if(values.sort_order&&!sortOrders.includes(values.sort_order))values.sort_order="";if(values.sort_by==="relevance"&&!values.q?.trim())values.sort_by="";return values};
const initialTagIds=()=>uniqueTagIds(initialQuery().getAll("tag_id"));
const initialActive=()=>{const values=initialValues();return new Set<FilterKey>((Object.keys(filterNames) as FilterKey[]).filter(k=>k==="tags"?initialTagIds().length>0:k==="difficulty"?!!values.difficulty_min||!!values.difficulty_max:!!values[k]))};
type Props={subjectId?:string;folderId?:string|null;navigate:(to:string)=>void};
export function FolderBrowser({subjectId,folderId=null,navigate}:Props){
 const [subjects,setSubjects]=useState<SubjectRoot[]>([]),[tree,setTree]=useState<FolderNode[]>([]),[level,setLevel]=useState<LevelContents>(),[catalogs,setCatalogs]=useState<Record<string,CatalogItem[]>>({grades:[],topics:[],subtopics:[],skills:[]});
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[values,setValues]=useState<Values>(initialValues),[active,setActive]=useState<Set<FilterKey>>(initialActive),[tagIds,setTagIds]=useState<string[]>(initialTagIds);
 const [draftQ,setDraftQ]=useState(initialQuery().get("q")??""),[filterMenuOpen,setFilterMenuOpen]=useState(false),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<{action:FolderDialogAction;opener:HTMLElement|null}|null>(null),requestNo=useRef(0),addFilterButton=useRef<HTMLButtonElement>(null),controlRefs=useRef<Record<string,HTMLElement|null>>({});
 const offset=Number(values.offset||0),limit=Number(values.limit||20),q=values.q||"";
 const difficultyError=useMemo(()=>{const a=values.difficulty_min,b=values.difficulty_max;if((a&&(!/^\d+$/.test(a)||+a<1||+a>100))||(b&&(!/^\d+$/.test(b)||+b<1||+b>100)))return "Введите целое число от 1 до 100.";if(a&&b&&+a>+b)return "Минимум не может превышать максимум.";return ""},[values.difficulty_min,values.difficulty_max]);
 const params=useMemo(()=>{const p=new URLSearchParams;queryKeys.forEach(k=>values[k]&&p.set(k,values[k]));tagIds.forEach(id=>p.append("tag_id",id));if(!p.has("offset"))p.set("offset","0");if(!p.has("limit"))p.set("limit","20");if(p.get("sort_by")==="relevance"&&!q)p.delete("sort_by");return p},[values,q,tagIds]);
 const sync=(next:Values,nextTagIds=tagIds)=>{const p=new URLSearchParams;queryKeys.forEach(k=>next[k]&&p.set(k,next[k]));nextTagIds.forEach(id=>p.append("tag_id",id));const url=`${location.pathname}${p.size?`?${p}`:""}`;if(url!==`${location.pathname}${location.search}`)history.pushState({},"",url)};
 const update=(patch:Values)=>setValues(old=>{const next={...old,...patch,offset:patch.offset??"0"};sync(next);return next});
 const load=useCallback(async()=>{if(difficultyError)return;const current=++requestNo.current;setLoading(true);setError("");const controller=new AbortController();try{if(!subjectId){const x=await getSubjectRoots(controller.signal);if(current===requestNo.current)setSubjects(x.items);return}const [t,c]=await Promise.all([getFolderTree(subjectId,controller.signal),getLevelContents(subjectId,folderId,params,controller.signal)]);if(current===requestNo.current){setTree(t.folders);setLevel(c)}}catch(e){if(current===requestNo.current&&!(e instanceof DOMException&&e.name==="AbortError"))setError(errorText(e))}finally{if(current===requestNo.current)setLoading(false)}return()=>controller.abort()},[subjectId,folderId,params.toString(),difficultyError]);
 useEffect(()=>{load()},[load]);useEffect(()=>{if(subjectId)Promise.all((["grades","topics","subtopics","skills"] as const).map(n=>getCatalog(n).then(x=>[n,Array.isArray(x.items)?x.items:[]] as const))).then(x=>setCatalogs(Object.fromEntries(x))).catch(()=>{})},[subjectId]);
 useEffect(()=>{const p=new URLSearchParams(location.search),before=p.getAll("tag_id");const ids=normalizeTagParams(p);if(before.length!==ids.length)history.replaceState({},"",`${location.pathname}${p.size?`?${p}`:""}`)},[]);
 useEffect(()=>{const onPop=()=>{setValues(initialValues());setTagIds(initialTagIds());setActive(initialActive());setDraftQ(initialQuery().get("q")??"")};addEventListener("popstate",onPop);return()=>removeEventListener("popstate",onPop)},[]);
 const all=useMemo(()=>flatten(tree),[tree]),current=folderId?all.find(x=>x.id===folderId):undefined;
 const topics=catalogs.topics.filter(x=>(!values.grade_id||x.grade_id===values.grade_id)&&(!x.subject_id||x.subject_id===subjectId)),subs=catalogs.subtopics.filter(x=>!values.topic_id||x.topic_id===values.topic_id),skills=catalogs.skills.filter(x=>(!values.topic_id||x.topic_id===values.topic_id)&&(!values.subtopic_id||x.subtopic_id===values.subtopic_id));
 const open=(action:FolderDialogAction,opener:HTMLElement)=>setDialog({action,opener});
 const change=(key:string,value:string)=>{const patch:Values={[key]:value};if(key==="grade_id")Object.assign(patch,{topic_id:"",subtopic_id:"",skill_id:""});if(key==="topic_id")Object.assign(patch,{subtopic_id:"",skill_id:""});if(key==="subtopic_id")patch.skill_id="";update(patch)};
 const add=(key:FilterKey)=>{setActive(old=>new Set(old).add(key));setFilterMenuOpen(false);queueMicrotask(()=>controlRefs.current[key]?.focus())};
 const remove=(key:FilterKey)=>{setActive(old=>{const n=new Set(old);n.delete(key);return n});if(key==="tags"){setTagIds([]);const next={...values,offset:"0"};setValues(next);sync(next,[])}else{const patch:Values=key==="difficulty"?{difficulty_min:"",difficulty_max:""}:{[key]:""};update(patch)}queueMicrotask(()=>addFilterButton.current?.focus())};
 const clear=()=>{const next={...values};queryKeys.forEach(k=>{if(!["limit"].includes(k))next[k]=""});setValues(next);setTagIds([]);setActive(new Set);setDraftQ("");sync(next,[]);queueMicrotask(()=>addFilterButton.current?.focus())};
 const selectControl=(key:FilterKey,label:string,items:(CatalogItem|string)[])=><label>{label}<select ref={e=>{controlRefs.current[key]=e}} value={values[key]||""} onChange={e=>change(key,e.target.value)}><option value="">Все</option>{items.map(x=>typeof x==="string"?<option key={x} value={x}>{x}</option>:<option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
 const control=(key:FilterKey)=>key==="tags"?<TagFilter ids={tagIds} subjectId={subjectId} onChange={tags=>{const ids=uniqueTagIds(tags.map(x=>x.id));setTagIds(ids);const next={...values,offset:"0"};setValues(next);sync(next,ids)}}/>:key==="difficulty"?<div><span className="filter-label">Сложность</span><div className="difficulty-range"><label>Минимум<input ref={e=>{controlRefs.current[key]=e}} type="number" min="1" max="100" step="1" value={values.difficulty_min||""} onChange={e=>change("difficulty_min",e.target.value)}/></label><label>Максимум<input type="number" min="1" max="100" step="1" value={values.difficulty_max||""} onChange={e=>change("difficulty_max",e.target.value)}/></label></div>{difficultyError&&<span className="field-error" role="alert">{difficultyError}</span>}</div>:selectControl(key,filterNames[key],key==="grade_id"?catalogs.grades:key==="topic_id"?topics:key==="subtopic_id"?subs:key==="skill_id"?skills:key==="task_type"?taskTypes:statuses);
 if(!subjectId)return <><div className="page-heading"><div><h1>Банк заданий</h1><p>Выберите предмет</p></div></div>{error&&<div className="alert error" role="alert">{error}<button onClick={load}>Повторить</button></div>}{loading?<p className="loading-state" role="status">Загрузка предметов…</p>:!subjects.length?<div className="empty-state">Банк заданий пока пуст.</div>:<section className="file-grid">{subjects.map(s=><a key={s.id} className="file-item subject-item" href={`/content-bank/subjects/${s.id}`} onClick={e=>{e.preventDefault();navigate(e.currentTarget.pathname)}}><span aria-hidden="true">📚</span><strong>{s.name}</strong></a>)}</section>}</>;
 const filtered=!!q||active.size>0;
 return <><div className="page-heading"><div><h1>Банк заданий</h1><p>{level?`${level.level_task_total} на этом уровне · ${level.subject_task_total} по предмету`:"Файлы предмета"}</p></div><div className="heading-actions"><a className="button-link" href={folderId?`/content-bank/subjects/${subjectId}/folders/${folderId}/new`:`/content-bank/subjects/${subjectId}/new`} onClick={e=>{e.preventDefault();navigate(e.currentTarget.pathname)}}>Создать задание</a><button disabled={busy} onClick={e=>open({kind:"create",parentId:folderId},e.currentTarget)}>Новая папка</button></div></div><nav className="breadcrumbs" aria-label="Текущее положение"><a href="/content-bank" onClick={e=>{e.preventDefault();navigate("/content-bank")}}>Предметы</a>{level&&<><span>/</span><a href={`/content-bank/subjects/${subjectId}`} onClick={e=>{e.preventDefault();navigate(`${e.currentTarget.pathname}${location.search}`)}} aria-current={!folderId?"page":undefined}>{level.subject.name}</a></>}{(level?.breadcrumb??[]).map((f,i)=><span key={f.id} className="crumb"><span>/</span><a href={`/content-bank/subjects/${subjectId}/folders/${f.id}${location.search}`} aria-current={i===(level?.breadcrumb.length??0)-1?"page":undefined} onClick={e=>{e.preventDefault();navigate(`${e.currentTarget.pathname}${e.currentTarget.search}`)}}>{f.name}</a></span>)}</nav>{notice&&<div className="alert success" role="status">{notice}</div>}{error&&<div className="alert error" role="alert">{error} <button className="secondary" onClick={load}>Обновить</button></div>}
 <section className="compact-filter-panel" aria-label="Поиск и фильтры заданий"><form className="search" onSubmit={(e:FormEvent)=>{e.preventDefault();const value=draftQ.trim();setDraftQ(value);update({q:value,sort_by:values.sort_by==="relevance"&&!value?"":values.sort_by||""})}}><label>Поиск на текущем уровне<input maxLength={200} value={draftQ} onChange={e=>setDraftQ(e.target.value)}/></label><button>Найти</button></form><div className="filter-toolbar"><div className="add-filter"><button ref={addFilterButton} type="button" className="secondary" aria-expanded={filterMenuOpen} aria-controls="available-task-filters" onClick={()=>setFilterMenuOpen(x=>!x)}>Добавить фильтр</button>{filterMenuOpen&&<div id="available-task-filters" className="available-filters" aria-label="Доступные фильтры" onKeyDown={e=>{if(e.key==="Escape"){e.preventDefault();setFilterMenuOpen(false);queueMicrotask(()=>addFilterButton.current?.focus())}}}>{(Object.keys(filterNames) as FilterKey[]).filter(k=>!active.has(k)).map(k=><button type="button" className="secondary" key={k} onClick={()=>add(k)}>{filterNames[k]}</button>)}{active.size===Object.keys(filterNames).length&&<span>Все фильтры добавлены</span>}</div>}</div><div className="sort-controls"><label>Сортировка<select value={values.sort_by||""} onChange={e=>update({sort_by:e.target.value})}><option value="">По умолчанию</option>{q&&<option value="relevance">Релевантность</option>}<option value="created_at">Дата создания</option><option value="updated_at">Дата обновления</option><option value="title">Название</option><option value="difficulty">Сложность</option><option value="status">Статус</option><option value="version_no">Версия</option></select></label><select aria-label="Направление сортировки" value={values.sort_order||"desc"} onChange={e=>update({sort_order:e.target.value})}><option value="desc">По убыванию</option><option value="asc">По возрастанию</option></select></div>{filtered&&<button type="button" className="secondary" onClick={clear}>Сбросить все</button>}</div>{active.size>0&&<div className="active-filters" aria-label="Активные фильтры">{[...active].map(key=><div className="filter-chip" key={key}>{control(key)}<button type="button" className="remove-filter" aria-label={`Убрать фильтр “${filterNames[key]}”`} onClick={()=>remove(key)}>×</button></div>)}</div>}</section>
 {loading?<p className="loading-state" role="status">Загрузка содержимого…</p>:level&&<>{!level.folders.length&&!level.tasks.items.length?<div className="empty-state">{filtered?<>Задания по текущим фильтрам не найдены. <button className="secondary" onClick={clear}>Сбросить фильтры</button></>:folderId?"Эта папка пуста.":"В предмете пока нет папок и заданий."}</div>:<section className="level-list" aria-label="Содержимое текущего уровня">{level.folders.map(f=><article className="file-row folder-row" key={f.id}><a href={`/content-bank/subjects/${subjectId}/folders/${f.id}${location.search}`} onClick={e=>{e.preventDefault();navigate(`${e.currentTarget.pathname}${e.currentTarget.search}`)}}>📁 <strong>{f.name}</strong></a></article>)}{level.tasks.items.map((t:any)=>{const title=t.title?.trim()||t.statement?.slice(0,80)?.trim()||"Задание без названия";return <article className="file-row task-row" key={t.task_id}><div>📄 <a className="task-title-link" aria-label={`Открыть задание «${title}»`} href={`/content-bank/tasks/${t.task_id}`} onClick={e=>{if(e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(e.currentTarget.pathname)}}><strong>{title}</strong></a><small>Сложность {t.difficulty} · {t.status}</small><TagChips tags={t.tags||[]} limit={3}/></div><span><button className="secondary" disabled={busy} onClick={e=>open({kind:"move-task",task:t},e.currentTarget)}>Переместить</button></span></article>})}</section>} {level.folders.length>0&&!level.tasks.items.length&&filtered&&<div className="empty-state task-empty">Задания по текущим фильтрам не найдены. <button className="secondary" onClick={clear}>Сбросить фильтры</button></div>}<div className="pagination"><span>{level.tasks.total?offset+1:0}–{Math.min(offset+level.tasks.items.length,level.tasks.total)} из {level.tasks.total}</span><label>На странице<select value={limit} onChange={e=>update({limit:e.target.value,offset:"0"})}><option>10</option><option>20</option><option>50</option></select></label><button className="secondary" disabled={offset===0||loading} onClick={()=>update({offset:String(Math.max(0,offset-limit))})}>Назад</button><button className="secondary" disabled={offset+limit>=level.tasks.total||loading} onClick={()=>update({offset:String(offset+limit)})}>Далее</button></div></>}{dialog&&level&&<FolderDialog action={dialog.action} subjectId={subjectId} subjectName={level.subject.name} currentFolderId={folderId} currentFolderName={current?.name??null} tree={tree} opener={dialog.opener} onClose={()=>setDialog(null)} onRefresh={load} onSuccess={async deleted=>{setNotice("Действие выполнено.");if(deleted?.id===folderId)navigate(deleted.parent_id?`/content-bank/subjects/${subjectId}/folders/${deleted.parent_id}`:`/content-bank/subjects/${subjectId}`);else await load()}}/>}</>}
