// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";import {cleanup,fireEvent,render,screen,waitFor,within} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {FolderBrowser} from "./FolderBrowser";
afterEach(()=>{cleanup();vi.restoreAllMocks()});const response=(body:unknown,status=200)=>Promise.resolve(new Response(status===204?null:JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));const subject={id:"s1",name:"Математика"},folder={id:"f1",subject_id:"s1",parent_id:null,name:"Алгебра",depth:1,created_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-02T00:00:00Z"},child={...folder,id:"f2",parent_id:"f1",name:"Линейные",depth:2},other={...folder,id:"f3",name:"Геометрия",depth:1},duplicate={...child,id:"f4",parent_id:"f3"};const task={task_id:"t1",title:"Legacy",statement:"Root",folder_id:null,difficulty:25,status:"draft"};
function mock(level:any={subject,folder:null,breadcrumb:[],folders:[folder],tasks:{items:[task],total:1,offset:0,limit:20},level_task_total:1,subject_task_total:1},tree:any=[{...folder,children:[{...child,children:[]}]},{...other,children:[{...duplicate,children:[]}]}]){return vi.fn((input:RequestInfo|URL,init?:RequestInit)=>{const u=String(input);if(init?.method)return response(init.method==="DELETE"?null:folder,init.method==="DELETE"?204:200);return u.includes("folders/tree")?response({subject,folders:tree}):response(level)})}
describe("FolderBrowser dialogs",()=>{it("creates root folder in an accessible dialog and restores focus",async()=>{const f=mock();vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={vi.fn()}/>);const opener=await screen.findByRole("button",{name:"Новая папка"});await userEvent.click(opener);const dialog=screen.getByRole("dialog",{name:"Создать папку"}),input=within(dialog).getByLabelText("Название папки");expect(document.activeElement).toBe(input);await userEvent.type(input,"Новая");await userEvent.click(within(dialog).getByRole("button",{name:"Подтвердить"}));const call=f.mock.calls.find(x=>x[1]?.method==="POST")!;expect(JSON.parse(String(call[1]!.body))).toEqual({name:"Новая",parent_id:null});await waitFor(()=>expect(screen.queryByRole("dialog")).toBeNull());expect(document.activeElement).toBe(opener)});
it("creates nested folder and closes on Escape",async()=>{const f=mock({...mockLevel(),folder, breadcrumb:[folder],folders:[]});vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" folderId="f1" navigate={vi.fn()}/>);await userEvent.click(await screen.findByRole("button",{name:"Новая папка"}));fireEvent.keyDown(screen.getByRole("dialog"),{key:"Escape"});expect(screen.queryByRole("dialog")).toBeNull();await userEvent.click(screen.getByRole("button",{name:"Новая папка"}));await userEvent.type(screen.getByLabelText("Название папки"),"Вложенная");await userEvent.click(screen.getByRole("button",{name:"Подтвердить"}));expect(JSON.parse(String(f.mock.calls.find(x=>x[1]?.method==="POST")![1]!.body)).parent_id).toBe("f1")});
it("keeps rename value and dialog after conflict, then offers CAS refresh",async()=>{const f=mock();f.mockImplementationOnce(f.getMockImplementation()!).mockImplementationOnce(f.getMockImplementation()!);vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={vi.fn()}/>);const buttons=await screen.findAllByRole("button",{name:"Переименовать"});await userEvent.click(buttons[0]);const input=screen.getByLabelText("Новое название");await userEvent.clear(input);await userEvent.type(input,"Дубликат");f.mockImplementationOnce(()=>response({error:{code:"folder_name_conflict",message:"raw"}},409));await userEvent.click(screen.getByRole("button",{name:"Подтвердить"}));expect(await screen.findByText(/уже существует/)).toBeTruthy();expect((input as HTMLInputElement).value).toBe("Дубликат");expect(screen.getByRole("dialog")).toBeTruthy()});
it("sends rename CAS timestamp",async()=>{const f=mock();vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={vi.fn()}/>);await userEvent.click((await screen.findAllByRole("button",{name:"Переименовать"}))[0]);await userEvent.click(screen.getByRole("button",{name:"Подтвердить"}));const body=JSON.parse(String(f.mock.calls.find(x=>x[1]?.method==="PATCH")![1]!.body));expect(body).toEqual({name:"Алгебра",expected_updated_at:folder.updated_at})});
it("folder picker shows paths and excludes self and descendants",async()=>{const f=mock();vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={vi.fn()}/>);await userEvent.click((await screen.findAllByRole("button",{name:"Переместить"}))[0]);const d=screen.getByRole("dialog",{name:"Переместить папку"});expect(within(d).getByText(/Корень: Математика/)).toBeTruthy();expect(within(d).queryByText("Линейные")).toBeNull();expect(within(d).getByText("Геометрия / Линейные")).toBeTruthy()});
it("moves task with exact CAS and disables current location",async()=>{const f=mock();vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={vi.fn()}/>);await userEvent.click((await screen.findAllByRole("button",{name:"Переместить"})).at(-1)!);const confirm=screen.getByRole("button",{name:"Подтвердить"});expect((confirm as HTMLButtonElement).disabled).toBe(true);await userEvent.click(screen.getAllByRole("radio")[2]);await userEvent.click(confirm);expect(JSON.parse(String(f.mock.calls.find(x=>x[1]?.method==="PUT")![1]!.body))).toEqual({folder_id:"f2",expected_folder_id:null})});
it("keeps delete dialog open on folder_not_empty",async()=>{const f=mock();vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={vi.fn()}/>);await userEvent.click((await screen.findAllByRole("button",{name:"Удалить"}))[0]);f.mockImplementationOnce(()=>response({error:{code:"folder_not_empty",message:"raw"}},409));await userEvent.click(within(screen.getByRole("dialog")).getByRole("button",{name:"Удалить"}));expect(await screen.findByText(/Папка не пуста/)).toBeTruthy();expect(screen.getByRole("dialog",{name:"Удалить папку"})).toBeTruthy()});
it("keeps legacy root task, task pagination and search",async()=>{const f=mock({...mockLevel(),tasks:{items:[task],total:31,offset:0,limit:20}});vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={vi.fn()}/>);expect(await screen.findByText("Legacy")).toBeTruthy();expect(screen.getByText("1–1 из 31")).toBeTruthy();await userEvent.type(screen.getByLabelText("Поиск на текущем уровне"),"квадрат");await userEvent.click(screen.getByRole("button",{name:"Найти"}));await waitFor(()=>expect(f.mock.calls.some(x=>String(x[0]).includes("q=%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82"))).toBe(true))})});
function mockLevel(){return {subject,folder:null,breadcrumb:[],folders:[folder],tasks:{items:[task],total:1,offset:0,limit:20},level_task_total:1,subject_task_total:1}}
