// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";import {cleanup,render,screen,waitFor,within} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {TaskList,type Catalogs} from "./main";
const catalogs:Catalogs={subjects:[],grades:[],topics:[],subtopics:[],skills:[]},tag=(id:string,name:string,status="active",replacement:any=null)=>({id,name,category_code:"exam",subject_id:null,status,replacement}),managed=(id:string,name:string)=>({...tag(id,name),normalized_name:name.toLowerCase(),category:{code:"exam",name:"Экзамен",sort_order:1},subject:null,created_at:"",created_by:"",updated_at:"",updated_by:""});
const item=(id:string,tags:any[])=>({task_id:id,title:`Задача ${id}`,statement:"Условие",subject_name:"Математика",grade_name:"7",topic_name:"Алгебра",primary_skill_name:null,task_type:"problem",difficulty:77,status:"draft",version_no:1,created_at:"2026-01-01",updated_at:"2026-01-01",tags});const json=(x:any,status=200)=>Promise.resolve(new Response(JSON.stringify(x),{status,headers:{"Content-Type":"application/json"}}));
function setup(url="/global"){history.replaceState({},"",url);const calls:string[]=[];vi.stubGlobal("fetch",vi.fn((input:any)=>{const u=String(input);calls.push(u);if(u.includes("/tags?"))return json({items:[managed("a","Альфа"),managed("b","Бета")],total:2,offset:0,limit:50});if(u.match(/\/tags\/(a|b)$/))return json(managed(u.endsWith("a")?"a":"b",u.endsWith("a")?"Альфа":"Бета"));return json({items:[item("none",[]),item("three",[tag("1","Один"),tag("2","Два"),tag("3","Три")]),item("many",[tag("4","Четыре"),tag("5","Пять"),tag("old","Старый","deprecated",tag("new","Новый")),tag("6","Шесть")])],total:41,offset:Number(new URL(u).searchParams.get("offset")||0),limit:20})}));render(<TaskList catalogs={catalogs} refresh={0} navigate={()=>{}}/>);return calls}
async function open(){await userEvent.click(screen.getByRole("button",{name:"Фильтр по тегам"}))}async function pick(name:string){const input=screen.getByRole("combobox",{name:"Поиск: Теги"});await userEvent.type(input,name[0]);await userEvent.click(await screen.findByRole("option",{name:new RegExp(name)}))}
afterEach(()=>{cleanup();vi.restoreAllMocks();history.replaceState({},"","/")});describe("global task tag boundaries",()=>{
 it("global catalog search sends active q without subject_id",async()=>{const calls=setup();await screen.findByText("Задача none");await open();await userEvent.type(screen.getByRole("combobox",{name:"Поиск: Теги"}),"аль");await waitFor(()=>expect(calls.some(u=>{const x=new URL(u);return x.pathname.endsWith("/tags")&&x.searchParams.get("status")==="active"&&x.searchParams.get("q")==="аль"&&!x.searchParams.has("subject_id")})).toBe(true))});
 it("global API and URL use exact repeated IDs with existing query facets",async()=>{const calls=setup("/global?q=поиск&difficulty_min=10&sort_by=title&offset=40");await screen.findByText("Задача none");await open();await pick("Альфа");await pick("Бета");const p=new URLSearchParams(location.search);expect(p.getAll("tag_id")).toEqual(["a","b"]);expect(p.get("offset")).toBe("0");expect(p.get("q")).toBe("поиск");expect(p.get("difficulty_min")).toBe("10");expect(p.get("sort_by")).toBe("title");await waitFor(()=>expect(calls.some(u=>{const x=new URL(u);return x.pathname.endsWith("/tasks")&&x.searchParams.getAll("tag_id").join() === "a,b"&&x.searchParams.get("q")==="поиск"&&x.searchParams.get("difficulty_min")==="10"&&x.searchParams.get("sort_by")==="title"})).toBe(true));expect(location.search).not.toContain("a%2Cb")});
 it("pagination request preserves both selected IDs",async()=>{const calls=setup("/global?tag_id=a&tag_id=b");await screen.findByText("Альфа");await userEvent.click(screen.getByRole("button",{name:"Далее"}));await waitFor(()=>expect(calls.some(u=>{const p=new URL(u).searchParams;return p.get("offset")==="20"&&p.getAll("tag_id").join() === "a,b"})).toBe(true));expect(screen.getByText(/21–23 из 41/)).toBeTruthy()});
 it("remove one keeps the other and clear removes all tag params",async()=>{setup("/global?tag_id=a&tag_id=b&q=keep");await screen.findByText("Альфа");await userEvent.click(screen.getByRole("button",{name:"Удалить тег «Альфа»"}));expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["b"]);await userEvent.click(screen.getByRole("button",{name:"Убрать фильтр “Теги”"}));const p=new URLSearchParams(location.search);expect(p.has("tag_id")).toBe(false);expect(p.get("q")).toBe("keep")});
 it("renders DTO tags compactly and performs no per-row tag fetches",async()=>{const calls=setup();await screen.findByText("Задача many");const rows=screen.getAllByRole("row");const none=rows.find(r=>within(r).queryByText("Задача none"))!;expect(none.querySelector(".tag-chips")).toBeNull();const many=rows.find(r=>within(r).queryByText("Задача many"))!;expect(within(many).getByText("Четыре")).toBeTruthy();expect(within(many).getByText("Пять")).toBeTruthy();expect(within(many).getByText("Старый")).toBeTruthy();expect(within(many).getByText("+1").getAttribute("aria-label")).toContain("Шесть");expect(within(many).getByText("Устарел")).toBeTruthy();expect(within(many).getByText("Старый").title).toContain("Новый");expect(within(many).getByRole("link",{name:/Задача many/})).toBeTruthy();expect(calls.filter(u=>/\/tags(?:\/|\?)/.test(u))).toHaveLength(0)});
});
