import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {ImportPage} from "./ImportPage";
import {IMPORT_HEADERS} from "./importTypes";

const catalogs:Record<string,unknown[]>={
 subjects:[{id:"subject-id",name:"Math",code:"math"}],grades:[{id:"grade-id",name:"7",number:7}],
 topics:[{id:"topic-id",name:"Motion",code:"motion",subject_id:"subject-id",grade_id:"grade-id"}],
 subtopics:[{id:"subtopic-id",name:"Speed",code:"speed",topic_id:"topic-id"}],
 skills:[{id:"skill-id",name:"Solve",code:"solve",topic_id:"topic-id",subtopic_id:"subtopic-id"}],
};
const file=(title="First",subject="math")=>new File([IMPORT_HEADERS.join(",")+`\n${subject},7,motion,speed,${title},Do it,problem,number,basic,,solve,1.0000,`],`${title}.csv`,{type:"text/csv"});
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const preview=(token="token",titleRows=[2])=>({import_token:token,format:"csv",expires_at:"2030-01-01T00:00:00Z",can_commit:true,summary:{rows_total:titleRows.length,rows_valid:titleRows.length,rows_invalid:0},rows:titleRows.map(row_number=>({row_number,status:"valid",issues:[]}))});
function server(options:{commit?:()=>Response|Promise<Response>;preview?:()=>Response|Promise<Response>}={}){return vi.spyOn(globalThis,"fetch").mockImplementation((input)=>{const url=String(input);const catalog=Object.keys(catalogs).find(x=>url.endsWith(`/catalog/${x}`));if(catalog)return Promise.resolve(json({catalog,items:catalogs[catalog]}));if(url.endsWith("/imports/preview"))return Promise.resolve(options.preview?.()??json(preview()));if(url.endsWith("/imports/commit"))return Promise.resolve(options.commit?.()??json({imported_count:1,items:[{row_number:2,task_id:"task-id",task_version_id:"version-id",version_no:1,status:"draft"}]},201));throw new Error(`Unexpected URL ${url}`)})}
const body=(call:any[])=>JSON.parse(String((call[1] as RequestInit).body));
const calls=(fetch:ReturnType<typeof server>,suffix:string)=>fetch.mock.calls.filter(([url])=>String(url).endsWith(suffix));
async function uploadAndPreview(inputFile=file()){await userEvent.upload(screen.getByLabelText(/Файл \(.csv/),inputFile);await userEvent.click(screen.getByRole("button",{name:"Проверить файл"}));await screen.findByRole("heading",{name:"Preview"})}
afterEach(()=>{cleanup();vi.restoreAllMocks()});

describe("ImportPage workflow",()=>{
 it("opens the import page",()=>{render(<ImportPage navigate={()=>{}}/>);expect(screen.getByRole("heading",{name:"Импорт CSV/XLSX"})).toBeTruthy();expect(screen.getByLabelText(/Файл \(.csv/)).toBeTruthy()});
 it("loads each catalog once and sends the exact normalized preview",async()=>{const fetch=server();render(<ImportPage navigate={()=>{}}/>);await uploadAndPreview();for(const name of Object.keys(catalogs))expect(calls(fetch,`/catalog/${name}`)).toHaveLength(1);const requests=calls(fetch,"/imports/preview");expect(requests).toHaveLength(1);expect(body(requests[0])).toEqual({format:"csv",rows:[{row_number:2,subject_id:"subject-id",grade_id:"grade-id",topic_id:"topic-id",subtopic_id:"subtopic-id",initial_version:{title:"First",statement:"Do it",task_type:"problem",answer_format:"number",difficulty:"basic",source:null,skills:[{skill_id:"skill-id",weight:"1.0000",is_primary:true}]}}]})});
 it("selects backend-valid rows, clears selection, and restores it",async()=>{server();render(<ImportPage navigate={()=>{}}/>);await uploadAndPreview();const checkbox=screen.getByRole("checkbox",{name:/Строка 2/});expect((checkbox as HTMLInputElement).checked).toBe(true);await userEvent.click(screen.getByRole("button",{name:"Снять выбор"}));expect((checkbox as HTMLInputElement).checked).toBe(false);expect((screen.getByRole("button",{name:/Импортировать выбранные/}) as HTMLButtonElement).disabled).toBe(true);await userEvent.click(screen.getByRole("button",{name:"Выбрать все допустимые"}));expect((checkbox as HTMLInputElement).checked).toBe(true)});
 it("shows a local-invalid row disabled and never previews a wholly invalid file",async()=>{const fetch=server();render(<ImportPage navigate={()=>{}}/>);await userEvent.upload(screen.getByLabelText(/Файл \(.csv/),file("Invalid","unknown"));await userEvent.click(screen.getByRole("button",{name:"Проверить файл"}));const table=await screen.findByRole("table");expect((within(table).getByRole("checkbox",{name:/Строка 2/}) as HTMLInputElement).disabled).toBe(true);expect(within(table).getByText("Код предмета не найден или неоднозначен.")).toBeTruthy();expect(calls(fetch,"/imports/preview")).toHaveLength(0)});
 it("commits the exact token and selected rows once on double click, then links the result",async()=>{const fetch=server();vi.spyOn(window,"confirm").mockReturnValue(true);render(<ImportPage navigate={()=>{}}/>);await uploadAndPreview();await userEvent.dblClick(screen.getByRole("button",{name:/Импортировать выбранные/}));await screen.findByRole("heading",{name:"Импорт завершён"});const commits=calls(fetch,"/imports/commit");expect(commits).toHaveLength(1);expect(body(commits[0])).toEqual({import_token:"token",row_numbers:[2]});expect(screen.getByText("task-id")).toBeTruthy();expect(screen.getByRole("link",{name:"Открыть карточку"}).getAttribute("href")).toBe("/content-bank/tasks/task-id")});
 it("starting another import clears the success result and old selection",async()=>{server();vi.spyOn(window,"confirm").mockReturnValue(true);render(<ImportPage navigate={()=>{}}/>);await uploadAndPreview();await userEvent.click(screen.getByRole("button",{name:/Импортировать выбранные/}));await screen.findByRole("heading",{name:"Импорт завершён"});await userEvent.click(screen.getByRole("button",{name:"Импортировать другой файл"}));await userEvent.upload(screen.getByLabelText(/Файл \(.csv/),file("Second"));expect(screen.queryByText("task-id")).toBeNull();expect(screen.queryByRole("heading",{name:"Preview"})).toBeNull();expect((screen.getByRole("button",{name:"Проверить файл"}) as HTMLButtonElement).disabled).toBe(false)});
 it("ignores a late first preview after the second preview has completed",async()=>{let resolveFirst!:(value:Response)=>void,resolveSecond!:(value:Response)=>void;const first=new Promise<Response>(r=>resolveFirst=r),second=new Promise<Response>(r=>resolveSecond=r);let count=0;server({preview:()=>++count===1?first:second});render(<ImportPage navigate={()=>{}}/>);await userEvent.upload(screen.getByLabelText(/Файл \(.csv/),file("First"));await userEvent.click(screen.getByRole("button",{name:"Проверить файл"}));await waitFor(()=>expect(count).toBe(1));await userEvent.upload(screen.getByLabelText(/Файл \(.csv/),file("Second"));await userEvent.click(screen.getByRole("button",{name:"Проверить файл"}));await waitFor(()=>expect(count).toBe(2));resolveSecond(json(preview("second")));expect(await screen.findByRole("cell",{name:"Second"})).toBeTruthy();resolveFirst(json(preview("first")));await waitFor(()=>expect(screen.queryByRole("cell",{name:"First"})).toBeNull());expect(screen.getByRole("cell",{name:"Second"})).toBeTruthy()});
 it.each([{status:404,message:"Preview не найден. Проверьте файл заново."},{status:410,message:"Срок preview истёк. Проверьте файл заново."},{status:409,message:"Token уже использован. Начните новый импорт."}])("shows a distinct token error for $status",async({status,message})=>{server({commit:()=>json({error:{code:"token_error",message:"server"}},status)});vi.spyOn(window,"confirm").mockReturnValue(true);render(<ImportPage navigate={()=>{}}/>);await uploadAndPreview();await userEvent.click(screen.getByRole("button",{name:/Импортировать выбранные/}));expect((await screen.findByRole("alert")).textContent).toContain(message)});
 it("keeps preview and selection after 422",async()=>{server({commit:()=>json({error:{code:"import_validation_error",message:"invalid"}},422)});vi.spyOn(window,"confirm").mockReturnValue(true);render(<ImportPage navigate={()=>{}}/>);await uploadAndPreview();await userEvent.click(screen.getByRole("button",{name:/Импортировать выбранные/}));expect((await screen.findByRole("alert")).textContent).toContain("Сервер отклонил выбранные строки");expect(screen.getByRole("heading",{name:"Preview"})).toBeTruthy();expect((screen.getByRole("checkbox",{name:/Строка 2/}) as HTMLInputElement).checked).toBe(true)});
 it("uses the same preview workflow for drag and drop",async()=>{const fetch=server();render(<ImportPage navigate={()=>{}}/>);fireEvent.drop(screen.getByText(/Файл разбирается/).nextElementSibling!,{dataTransfer:{files:[file("Dropped")]}});await userEvent.click(screen.getByRole("button",{name:"Проверить файл"}));expect(await screen.findByRole("cell",{name:"Dropped"})).toBeTruthy();expect(calls(fetch,"/imports/preview")).toHaveLength(1)});
});
