export type Solution={id?:string;solution_text:string;final_answer:string;solution_steps:string[]};
export type RubricItem={id?:string;criterion:string;max_points:string;required:boolean;common_failure:string;order_index?:number};
export type Rubric={id?:string;grading_mode:"points";max_score?:string;notes:string;items:RubricItem[]};
export type Answer={id?:string;answer_value:string;tolerance:string;unit:string;normalization_rule:string;value_kind?:"legacy_untyped"|"text"|"decimal"|"expression"|"choice_set";canonical_text?:string|null;canonical_decimal?:string|null;option_keys?:string[];absolute_tolerance?:string|null;relative_tolerance?:string|null;unit_code?:string|null;normalization_policy_code?:string|null;normalization_policy_version?:number|null};
export type ChoiceOption={id?:string;option_key:string;content:string;order_index:number};
export type ChoiceScoringPolicy={mode:"all_or_nothing"|"per_option";policy_version:number;option_rules:{option_key:string;weight:string}[]};
export type TypicalError={id?:string;skill_id:string;code:string;title:string;description:string;severity:"low"|"medium"|"high";remediation_hint:string;detection_hint:string};
export type Hint={id?:string;level:number;hint_text:string};
export type Methodology={expected_solution:Solution|null;rubric:Rubric|null;accepted_answers:Answer[];typical_errors:TypicalError[];hints:Hint[];choice_options?:ChoiceOption[];choice_scoring_policy?:ChoiceScoringPolicy|null};
export type FieldErrors=Record<string,string>;
const nullable=(x:string)=>x.trim()===""?null:x.trim();
export function methodologyToForm(value:any):Methodology{return {
  expected_solution:value?.expected_solution?{...value.expected_solution,final_answer:value.expected_solution.final_answer??"",solution_steps:[...value.expected_solution.solution_steps]}:null,
  rubric:value?.rubric?{...value.rubric,notes:value.rubric.notes??"",items:value.rubric.items.map((x:any)=>({...x,max_points:String(x.max_points),common_failure:x.common_failure??""}))}:null,
  accepted_answers:(value?.accepted_answers??[]).map((x:any)=>({...x,tolerance:x.tolerance==null?"":String(x.tolerance),unit:x.unit??"",normalization_rule:x.normalization_rule??""})),
  typical_errors:(value?.typical_errors??[]).map((x:any)=>({...x,remediation_hint:x.remediation_hint??"",detection_hint:x.detection_hint??""})),
  hints:(value?.hints??[]).map((x:any,i:number)=>({...x,level:i+1})),
  ...(value?.choice_options!==undefined?{choice_options:value.choice_options.map((x:any)=>({...x}))}:{}),
  ...(value?.choice_scoring_policy!==undefined?{choice_scoring_policy:value.choice_scoring_policy}: {})};}
export function formToPayload(form:Methodology){return {
  expected_solution:form.expected_solution?{solution_text:form.expected_solution.solution_text.trim(),final_answer:nullable(form.expected_solution.final_answer),solution_steps:form.expected_solution.solution_steps.map(x=>x.trim())}:null,
  rubric:form.rubric?{grading_mode:"points",notes:nullable(form.rubric.notes),items:form.rubric.items.map(x=>({criterion:x.criterion.trim(),max_points:x.max_points.trim(),required:x.required,common_failure:nullable(x.common_failure)}))}:null,
  accepted_answers:form.accepted_answers.map(x=>({answer_value:x.answer_value.trim(),tolerance:nullable(x.tolerance),unit:nullable(x.unit),normalization_rule:nullable(x.normalization_rule),...(x.value_kind!==undefined?{value_kind:x.value_kind,canonical_text:x.canonical_text??null,canonical_decimal:x.canonical_decimal??null,option_keys:x.option_keys??[],absolute_tolerance:x.absolute_tolerance??null,relative_tolerance:x.relative_tolerance??null,unit_code:x.unit_code??null,normalization_policy_code:x.normalization_policy_code??null,normalization_policy_version:x.normalization_policy_version??null}:{})})),
  typical_errors:form.typical_errors.map(x=>({skill_id:x.skill_id,code:x.code.trim(),title:x.title.trim(),description:x.description.trim(),severity:x.severity,remediation_hint:nullable(x.remediation_hint),detection_hint:nullable(x.detection_hint)})),
  hints:form.hints.map((x,i)=>({level:i+1,hint_text:x.hint_text.trim()})),
  ...(form.choice_options!==undefined?{choice_options:form.choice_options.map(({option_key,content,order_index})=>({option_key,content,order_index}))}:{}),
  ...(form.choice_scoring_policy!==undefined?{choice_scoring_policy:form.choice_scoring_policy}: {})};}
export function rubricTotal(items:RubricItem[]){let scale=0,total=0n;for(const x of items){const raw=x.max_points.trim();if(!/^\d+(\.\d+)?$/.test(raw))continue;const [,fraction=""]=raw.split(".");const next=Math.max(scale,fraction.length);total*=10n**BigInt(next-scale);total+=BigInt(raw.replace(".",""))*10n**BigInt(next-fraction.length);scale=next}if(!scale)return total.toString();const s=total.toString().padStart(scale+1,"0");return `${s.slice(0,-scale)}.${s.slice(-scale).replace(/0+$/,'')||'0'}`}
export function validateMethodology(f:Methodology,answerFormat:string){const e:FieldErrors={};const req=(path:string,v:string)=>{if(!v.trim())e[path]="Обязательное поле"};if(f.expected_solution){req("solution.solution_text",f.expected_solution.solution_text);f.expected_solution.solution_steps.forEach((x,i)=>req(`solution.steps.${i}`,x))}if(f.rubric){const seen=new Set<string>();f.rubric.items.forEach((x,i)=>{req(`rubric.items.${i}.criterion`,x.criterion);const k=x.criterion.trim().toLowerCase();if(k&&seen.has(k))e[`rubric.items.${i}.criterion`]="Критерий дублируется";seen.add(k);if(!/^\d+(\.\d+)?$/.test(x.max_points)||Number(x.max_points)<=0)e[`rubric.items.${i}.max_points`]="Введите число больше нуля"})}const answers=new Set<string>();f.accepted_answers.forEach((x,i)=>{req(`answers.${i}.answer_value`,x.answer_value);const k=x.answer_value.trim().toLowerCase();if(k&&answers.has(k))e[`answers.${i}.answer_value`]="Ответ дублируется";answers.add(k);if(x.tolerance&&(!/^\d+(\.\d+)?$/.test(x.tolerance)||Number(x.tolerance)<0))e[`answers.${i}.tolerance`]="Допуск должен быть неотрицательным";if(answerFormat!=="number"&&x.tolerance)e[`answers.${i}.tolerance`]="Допуск доступен только для number"});const codes=new Set<string>();f.typical_errors.forEach((x,i)=>{if(!x.skill_id)e[`errors.${i}.skill_id`]="Выберите навык";["code","title","description"].forEach(k=>req(`errors.${i}.${k}`,(x as any)[k]));const k=`${x.skill_id}:${x.code.trim().toLowerCase()}`;if(x.code.trim()&&codes.has(k))e[`errors.${i}.code`]="Код дублируется для этого навыка";codes.add(k)});f.hints.forEach((x,i)=>req(`hints.${i}.hint_text`,x.hint_text));return e}
