import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {MethodologyEditor} from "./MethodologyEditor";

afterEach(()=>{cleanup();vi.restoreAllMocks()});
const methodology={expected_solution:{id:"s",solution_text:"Existing solution",final_answer:null,solution_steps:["Step"]},rubric:{id:"r",grading_mode:"points",max_score:"1",notes:null,items:[{id:"i",criterion:"Existing criterion",max_points:"1",required:true,common_failure:null,order_index:0}]},accepted_answers:[{id:"a",answer_value:"42",tolerance:null,unit:null,normalization_rule:null}],typical_errors:[],hints:[{id:"h",level:1,hint_text:"Existing hint"}]};
const card=(status="draft",archived_at:string|null=null)=>({archived_at,latest_version:{id:"version",status,answer_format:"number",skills:[{skill_id:"skill",name:"Algebra"}],methodology}});
const setup=(value=card())=>render(<MethodologyEditor card={value} mainPanel={<p>Main statement</p>} onDirtyChange={()=>{}} onSaved={()=>{}}/>);
describe("editor",()=>{
 it("renders existing data and switches tabs without a request",async()=>{const fetch=vi.spyOn(globalThis,"fetch");setup();expect(screen.getByText("Main statement")).toBeTruthy();await userEvent.click(screen.getByRole("tab",{name:"Решение"}));expect(screen.getByDisplayValue("Existing solution")).toBeTruthy();expect(fetch).not.toHaveBeenCalled()});
 it("supports tab keyboard navigation",()=>{setup();const main=screen.getByRole("tab",{name:"Основное"});fireEvent.keyDown(main,{key:"End"});expect(screen.getByRole("tab",{name:"Подсказки"}).getAttribute("aria-selected")).toBe("true")});
 it("saves every block regardless of active tab and uses response",async()=>{let body:any;vi.spyOn(globalThis,"fetch").mockImplementation(async(_url,init)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify(methodology),{status:200,headers:{"Content-Type":"application/json"}})});setup();await userEvent.click(screen.getByRole("tab",{name:"Подсказки"}));await userEvent.type(screen.getByDisplayValue("Existing hint")," updated");await userEvent.click(screen.getByRole("button",{name:"Сохранить методическую структуру"}));await waitFor(()=>expect(screen.getByText("Методическая структура сохранена.")).toBeTruthy());expect(Object.keys(body)).toEqual(["expected_solution","rubric","accepted_answers","typical_errors","hints"])});
 it.each([[422,"validation_error"],[409,"typical_error_definition_conflict"]])("keeps form after %s",async(status,code)=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({error:{code,message:"Rejected",details:[]}}),{status,headers:{"Content-Type":"application/json"}}));setup();await userEvent.click(screen.getByRole("tab",{name:"Подсказки"}));const input=screen.getByDisplayValue("Existing hint");await userEvent.type(input," retained");await userEvent.click(screen.getByRole("button",{name:"Сохранить методическую структуру"}));await waitFor(()=>expect(screen.getByDisplayValue("Existing hint retained")).toBeTruthy())});
 it.each(["review","approved","archived"])("is read-only for %s",async status=>{setup(card(status));await userEvent.click(screen.getByRole("tab",{name:"Решение"}));expect(screen.getByText(/Только просмотр/)).toBeTruthy();expect(screen.queryByRole("button",{name:"Сохранить методическую структуру"})).toBeNull();expect((screen.getByDisplayValue("Existing solution") as HTMLTextAreaElement).disabled).toBe(true)});
 it("has no save for archived card",async()=>{setup(card("draft","2026-01-01"));await userEvent.click(screen.getByRole("tab",{name:"Ответы"}));expect(screen.queryByRole("button",{name:"Сохранить методическую структуру"})).toBeNull()});
 it("reports dirty state",async()=>{const dirty=vi.fn();render(<MethodologyEditor card={card()} mainPanel={<p>Main</p>} onDirtyChange={dirty} onSaved={()=>{}}/>);await userEvent.click(screen.getByRole("tab",{name:"Решение"}));await userEvent.type(screen.getByDisplayValue("Existing solution")," changed");expect(dirty).toHaveBeenLastCalledWith(true)});
});
