import {describe,expect,it} from "vitest";
import {formToPayload,methodologyToForm,rubricTotal,validateMethodology} from "./methodology";

describe("methodology transformations",()=>{
  it("creates one empty form from an empty methodology",()=>expect(methodologyToForm({expected_solution:null,rubric:null,accepted_answers:[],typical_errors:[],hints:[]})).toEqual({expected_solution:null,rubric:null,accepted_answers:[],typical_errors:[],hints:[]}));
  it("always emits all five blocks, nullable strings and sequential hints",()=>{const form=methodologyToForm({expected_solution:{solution_text:" S ",final_answer:"",solution_steps:[" step "]},rubric:{grading_mode:"points",max_score:"3.3",notes:null,items:[{criterion:"B",max_points:"2.2",required:true,common_failure:null,order_index:1},{criterion:"A",max_points:"1.1",required:false,common_failure:"",order_index:0}]},accepted_answers:[{answer_value:" 3 ",tolerance:null,unit:"",normalization_rule:""}],typical_errors:[],hints:[{level:7,hint_text:"one"},{level:9,hint_text:"two"}]});expect(formToPayload(form)).toEqual({expected_solution:{solution_text:"S",final_answer:null,solution_steps:["step"]},rubric:{grading_mode:"points",notes:null,items:[{criterion:"B",max_points:"2.2",required:true,common_failure:null},{criterion:"A",max_points:"1.1",required:false,common_failure:null}]},accepted_answers:[{answer_value:"3",tolerance:null,unit:null,normalization_rule:null}],typical_errors:[],hints:[{level:1,hint_text:"one"},{level:2,hint_text:"two"}]})});
  it("preserves deletion of optional blocks",()=>expect(formToPayload({expected_solution:null,rubric:null,accepted_answers:[],typical_errors:[],hints:[]})).toMatchObject({expected_solution:null,rubric:null}));
  it("adds decimal scores without floating point accumulation",()=>expect(rubricTotal([{criterion:"a",max_points:"0.1",required:true,common_failure:""},{criterion:"b",max_points:"0.2",required:true,common_failure:""}])).toBe("0.3"));
  it("validates required fields, duplicates, positive numbers and skills",()=>{const errors=validateMethodology({expected_solution:{solution_text:" ",final_answer:"",solution_steps:[""]},rubric:{grading_mode:"points",notes:"",items:[{criterion:"same",max_points:"0",required:true,common_failure:""},{criterion:" Same ",max_points:"1",required:true,common_failure:""}]},accepted_answers:[{answer_value:"x",tolerance:"1",unit:"",normalization_rule:""},{answer_value:" X ",tolerance:"",unit:"",normalization_rule:""}],typical_errors:[{skill_id:"",code:"c",title:"",description:"",severity:"low",remediation_hint:"",detection_hint:""}],hints:[{level:1,hint_text:""}]},"short_text");expect(Object.keys(errors).length).toBeGreaterThan(8)});
});
