import {request} from "./api";
export type RemediationItem={position:number;task_version_id:string;selection_source:string;title:string|null;statement:string|null;task_type:string|null;answer_format:string|null;difficulty:number|null};
export type Remediation={id:string;student_id:string;class_group_id:string;source_assignment_id:string;source_assignment_participant_id:string;source_submission_id:string;source_check_run_id:string;status:"draft"|"assigned"|"cancelled";title:string;instructions:string|null;due_at:string|null;review_acknowledged_at:string|null;created_at:string;updated_at:string;assigned_at:string|null;cancelled_at:string|null;finding_ids:string[];items:RemediationItem[]};
export type Candidate={task_id:string;task_version_id:string;title:string|null;statement_preview:string;task_type:string;answer_format:string;difficulty:number;primary_skill_name:string|null;reasons:{match_type:string;matched_title:string|null}[]};
export const searchCandidates=(body:unknown):Promise<Candidate[]>=>request("/api/remediations/candidates/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
export const createRemediation=(body:unknown):Promise<Remediation>=>request("/api/remediations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
export const assignRemediation=(id:string,ack:boolean):Promise<Remediation>=>request(`/api/remediations/${id}/assign`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({acknowledge_review_required:ack})});
export const getRemediation=(id:string):Promise<Remediation>=>request(`/api/remediations/${id}`);
export const cancelRemediation=(id:string):Promise<Remediation>=>request(`/api/remediations/${id}/cancel`,{method:"POST"});
export const listStudentRemediations=():Promise<{items:any[]}>=>(request("/api/student/remediations"));
export const getStudentRemediation=(id:string):Promise<any>=>request(`/api/student/remediations/${id}`);
export const listTeacherRemediations=(c:string,s:string):Promise<{items:Remediation[]}>=>(request(`/api/classrooms/${c}/students/${s}/remediations`));
