import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {StudentAssignmentDetailPage,StudentAssignmentListPage,StudentAttemptPage} from "./StudentAssessmentPages";

const ok=(body:unknown,status=200)=>new Response(status===204?null:JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const assignment={assignment_id:"a1",assessment_id:"as1",title:"Контрольная",description:"Описание",status:"open" as const,start_at:"2020-01-01T00:00:00Z",due_at:"2099-01-01T00:00:00Z",max_attempts:2,assigned_variant_id:"v1",attempt_count:0,participant_id:"p1",current_draft_attempt_id:null,submitted_attempt_count:0,submitted_attempts:[] as {id:string;attempt_no:number;submitted_at:string}[]};
const items=[
 {id:"i1",task_version_id:"t1",position:1,points:"1.00",title:"Выбор",statement:"Один",task_type:"test",answer_format:"single_choice"},
 {id:"i2",task_version_id:"t2",position:2,points:"2.00",title:null,statement:"Несколько",task_type:"test",answer_format:"multiple_choice"},
 {id:"i3",task_version_id:"t3",position:3,points:"1.00",title:null,statement:"Текст",task_type:"open_question",answer_format:"short_text"},
 {id:"i4",task_version_id:"t4",position:4,points:"1.00",title:null,statement:"Число",task_type:"calculation",answer_format:"number"},
 {id:"i5",task_version_id:"t5",position:5,points:"1.00",title:null,statement:"Формула",task_type:"calculation",answer_format:"expression"},
 {id:"i6",task_version_id:"t6",position:6,points:"1.00",title:null,statement:"Эссе",task_type:"essay",answer_format:"long_text"},
] as any[];
const attempt=(answers:any[]=[],status:"draft"|"submitted"="draft")=>({id:"s1",attempt_no:1,status,assigned_variant_id:"v1",resumed:false,started_at:"2026-01-01T00:00:00Z",submitted_at:status==="submitted"?"2026-01-02T00:00:00Z":null,answers,items});
beforeEach(()=>{sessionStorage.clear();vi.stubGlobal("confirm",vi.fn(()=>true));vi.stubGlobal("crypto",{randomUUID:vi.fn(()=>"00000000-0000-4000-8000-000000000001")})});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals()});

describe("Student assessment list and detail",()=>{
 it("renders loading, assignment card, status, attempts and navigates",async()=>{let resolve!:(r:Response)=>void;vi.spyOn(globalThis,"fetch").mockReturnValue(new Promise(r=>resolve=r));const navigate=vi.fn();render(<StudentAssignmentListPage navigate={navigate}/>);expect(screen.getByRole("status").textContent).toContain("Загрузка");resolve(ok({items:[assignment],total:1,offset:0,limit:20}));expect(await screen.findByText("Контрольная")).toBeTruthy();expect(screen.getByText("0 из 2")).toBeTruthy();expect(screen.getByText("Доступна")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"Открыть"}));expect(navigate).toHaveBeenCalledWith("/student/assignments/a1")});
 it("retries list errors and shows the empty state",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockRejectedValueOnce(Error("offline")).mockResolvedValueOnce(ok({items:[],total:0,offset:0,limit:20}));render(<StudentAssignmentListPage navigate={vi.fn()}/>);await userEvent.click(await screen.findByRole("button",{name:"Повторить"}));expect(await screen.findByText("Назначенных работ пока нет.")).toBeTruthy();expect(fetch).toHaveBeenCalledTimes(2)});
 it("continues a draft without a START request",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValue(ok({...assignment,current_draft_attempt_id:"draft-1",attempt_count:1}));const navigate=vi.fn();render(<StudentAssignmentDetailPage assignmentId="a1" navigate={navigate}/>);await userEvent.click(await screen.findByRole("button",{name:"Продолжить попытку"}));expect(navigate).toHaveBeenCalledWith("/student/assignments/a1/attempts/draft-1");expect(fetch).toHaveBeenCalledTimes(1)});
 it("renders sorted submitted history without IDs and navigates to the read-only route",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(ok({...assignment,submitted_attempt_count:2,submitted_attempts:[{id:"uuid-secret-2",attempt_no:2,submitted_at:"2026-02-02T00:00:00Z"},{id:"uuid-secret-1",attempt_no:1,submitted_at:"2026-01-01T00:00:00Z"}]}));const navigate=vi.fn();render(<StudentAssignmentDetailPage assignmentId="a1" navigate={navigate}/>);expect(await screen.findByRole("heading",{name:"Отправленные попытки"})).toBeTruthy();expect(screen.getAllByText(/Попытка/).map(x=>x.textContent)).toEqual(["Попытка 1","Попытка 2"]);expect(screen.queryByText(/uuid-secret/)).toBeNull();await userEvent.click(screen.getAllByRole("button",{name:"Открыть"})[0]);expect(navigate).toHaveBeenCalledWith("/student/assignments/a1/attempts/uuid-secret-1")});
 it("reuses the START key after an uncertain network failure and removes it on success",async()=>{const calls:RequestInit[]=[];vi.spyOn(globalThis,"fetch").mockImplementation(async(_url,init)=>{calls.push(init||{});if(calls.length===1)return ok(assignment);if(calls.length===2)throw Error("offline");return ok(attempt())});const navigate=vi.fn();render(<StudentAssignmentDetailPage assignmentId="a1" navigate={navigate}/>);const start=await screen.findByRole("button",{name:"Начать попытку"});await userEvent.click(start);expect(await screen.findByText(/Не удалось подтвердить/)).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"Начать попытку"}));expect((calls[1].headers as Record<string,string>)["Idempotency-Key"]).toBe("start:00000000-0000-4000-8000-000000000001");expect((calls[2].headers as Record<string,string>)["Idempotency-Key"]).toBe((calls[1].headers as Record<string,string>)["Idempotency-Key"]);expect(sessionStorage.getItem("assessment:start:a1")).toBeNull();expect(navigate).toHaveBeenCalled()});
});

describe("Student attempt",()=>{
 const renderAttempt=(value=attempt())=>{vi.spyOn(globalThis,"fetch").mockImplementation(async url=>String(url).includes("/assignments/")?ok(assignment):ok(value));render(<StudentAttemptPage assignmentId="a1" submissionId="s1" navigate={vi.fn()} onDirtyChange={vi.fn()}/>)};
 it("offers all six raw editors and keeps number as text",async()=>{renderAttempt();expect(await screen.findByLabelText("ID выбранного варианта")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"2"}));expect(screen.getByText("IDs выбранных вариантов")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"3"}));expect(screen.getByLabelText("Краткий ответ")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"4"}));expect((screen.getByLabelText("Число") as HTMLInputElement).type).toBe("text");await userEvent.click(screen.getByRole("button",{name:"5"}));expect(screen.getByLabelText("Выражение")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"6"}));expect(screen.getByLabelText("Развёрнутый ответ").tagName).toBe("TEXTAREA")});
 it("saves exact number raw and advances the CAS timestamp",async()=>{const puts:any[]=[];const fetch=vi.spyOn(globalThis,"fetch").mockImplementation(async(url,init)=>{if(String(url).includes("/assignments/"))return ok(assignment);if(init?.method==="PUT"){puts.push(JSON.parse(String(init.body)));return ok({item_id:"i4",raw_answer:puts.at(-1).raw_answer,normalized_answer:{decimal:"123"},created_at:"x",updated_at:`u${puts.length}`})}return ok(attempt())});render(<StudentAttemptPage assignmentId="a1" submissionId="s1" navigate={vi.fn()} onDirtyChange={vi.fn()}/>);await screen.findByText("Контрольная");await userEvent.click(screen.getByRole("button",{name:"4"}));const input=screen.getByLabelText("Число");await userEvent.type(input," 001,2300e2 ");await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));await screen.findByText("Ответ сохранён");expect(puts[0]).toEqual({raw_answer:" 001,2300e2 ",expected_updated_at:null});await userEvent.type(input,"x");await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));await waitFor(()=>expect(puts).toHaveLength(2));expect(puts[1].expected_updated_at).toBe("u1");expect(fetch).toHaveBeenCalled()});
 it("renders a submitted attempt read-only from raw answers only",async()=>{renderAttempt(attempt([{item_id:"i1",raw_answer:"raw-id",normalized_answer:"SECRET",created_at:"x",updated_at:"x"}],"submitted"));expect(await screen.findByDisplayValue("raw-id")).toBeTruthy();expect(screen.queryByText("SECRET")).toBeNull();expect(screen.queryByRole("button",{name:"Сохранить ответ"})).toBeNull();expect(screen.queryByRole("button",{name:"Очистить ответ"})).toBeNull();expect(screen.queryByRole("button",{name:"Отправить работу"})).toBeNull();await userEvent.click(screen.getByRole("button",{name:"2"}));expect(screen.getByText("Ответ не дан")).toBeTruthy()});
});

const apiError=(code:string,message=code,status=409)=>ok({error:{code,message,details:[]}},status);
const answer=(item_id:string,raw_answer:any,updated_at="T1")=>({item_id,raw_answer,normalized_answer:"NORMALIZED_SECRET",created_at:"T0",updated_at});
function renderDraft(fetchImpl:(url:string,init?:RequestInit)=>Promise<Response>,answers:any[]=[]){const onDirtyChange=vi.fn();const spy=vi.spyOn(globalThis,"fetch").mockImplementation((url,init)=>fetchImpl(String(url),init));render(<StudentAttemptPage assignmentId="a1" submissionId="s1" navigate={vi.fn()} onDirtyChange={onDirtyChange}/>);return {spy,onDirtyChange}}

describe("Student submit behavioral contract",()=>{
 it("blocks submit while a local raw answer is dirty",async()=>{const submit=vi.fn();renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="POST"){submit();return ok(attempt([],"submitted"))}return ok(attempt())});const input=await screen.findByLabelText("ID выбранного варианта");await userEvent.type(input,"unsaved");await userEvent.click(screen.getByRole("button",{name:"Отправить работу"}));expect(screen.getAllByText("Сначала сохраните изменённые ответы.").length).toBeGreaterThan(0);expect(submit).not.toHaveBeenCalled();expect(input).toHaveProperty("value","unsaved")});
 it("does not submit when confirmation is cancelled",async()=>{vi.stubGlobal("confirm",vi.fn(()=>false));const posts:RequestInit[]=[];renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="POST")posts.push(init);return ok(attempt())});await screen.findByText(/Черновик/);await userEvent.click(screen.getByRole("button",{name:"Отправить работу"}));expect(posts).toHaveLength(0);expect(screen.getByLabelText("ID выбранного варианта")).not.toHaveProperty("readOnly",true)});
 it("submits exact command and switches to raw-only read-only",async()=>{const calls:{url:string;init?:RequestInit}[]=[];const persisted=answer("i1","raw-id");renderDraft(async(url,init)=>{calls.push({url,init});if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="POST")return ok(attempt([persisted],"submitted"));return ok(attempt([persisted]))},[persisted]);await screen.findByDisplayValue("raw-id");await userEvent.click(screen.getByRole("button",{name:"Отправить работу"}));await screen.findByText("Попытка 1 · Отправлена");const post=calls.find(c=>c.init?.method==="POST")!;expect(post.url).toContain("/api/assessment-core/student/attempts/s1/submit");expect(post.init?.body).toBe("{}");expect((post.init?.headers as Record<string,string>)["Idempotency-Key"]).toMatch(/^submit:/);expect(sessionStorage.getItem("assessment:submit:s1")).toBeNull();expect(screen.getByDisplayValue("raw-id")).toBeTruthy();expect(screen.queryByText("NORMALIZED_SECRET")).toBeNull();expect(screen.queryByRole("button",{name:"Сохранить ответ"})).toBeNull();expect(screen.queryByRole("button",{name:"Очистить ответ"})).toBeNull();expect(screen.queryByRole("button",{name:"Отправить работу"})).toBeNull()});
 it("reuses the same submit key after an uncertain network failure",async()=>{const keys:string[]=[];let posts=0;renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="POST"){posts++;keys.push((init.headers as Record<string,string>)["Idempotency-Key"]);if(posts===1)throw Error("offline");return ok(attempt([],"submitted"))}return ok(attempt())});await screen.findByText(/Черновик/);await userEvent.click(screen.getByRole("button",{name:"Отправить работу"}));expect(await screen.findByText(/Не удалось подтвердить/)).toBeTruthy();expect(sessionStorage.getItem("assessment:submit:s1")).toBe(keys[0]);await userEvent.click(screen.getByRole("button",{name:"Отправить работу"}));await screen.findByText("Попытка 1 · Отправлена");expect(keys).toHaveLength(2);expect(keys[1]).toBe(keys[0]);expect(keys[0]).toMatch(/^submit:/);expect(keys[0]).not.toBe(`start:${keys[0].slice(7)}`);expect(sessionStorage.getItem("assessment:submit:s1")).toBeNull();expect(sessionStorage.getItem("assessment:start:a1")).toBeNull()});
 it("refreshes an already-submitted attempt without a second POST",async()=>{let gets=0,posts=0;renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="POST"){posts++;return apiError("submission_already_submitted")}gets++;return ok(attempt([],gets>1?"submitted":"draft"))});await screen.findByText(/Черновик/);await userEvent.click(screen.getByRole("button",{name:"Отправить работу"}));expect(await screen.findByText("Работа уже была отправлена.")).toBeTruthy();expect(screen.getByText("Попытка 1 · Отправлена")).toBeTruthy();expect(posts).toBe(1);expect(gets).toBe(2);expect(screen.queryByRole("button",{name:"Отправить работу"})).toBeNull()});
 it("allows a confirmed zero-answer submission",async()=>{let posts=0;renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="POST"){posts++;return ok(attempt([],"submitted"))}return ok(attempt())});await screen.findByText(/Черновик/);await userEvent.click(screen.getByRole("button",{name:"Отправить работу"}));await waitFor(()=>expect(posts).toBe(1));expect(screen.getByText("Попытка 1 · Отправлена")).toBeTruthy()});
});

describe("Student answer persistence behavioral contract",()=>{
 it("refreshes remote raw after CAS conflict and never retries PUT",async()=>{let gets=0,puts=0;const initial=answer("i1","old","T1"),remote=answer("i1","remote","T2");renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="PUT"){puts++;expect(JSON.parse(String(init.body))).toEqual({raw_answer:"stale",expected_updated_at:"T1"});return apiError("concurrent_conflict")}gets++;return ok(attempt([gets>1?remote:initial]))},[initial]);const input=await screen.findByDisplayValue("old");await userEvent.clear(input);await userEvent.type(input,"stale");await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));expect(await screen.findByText("Ответ изменился в другой вкладке. Загружена актуальная версия.")).toBeTruthy();expect(screen.getByDisplayValue("remote")).toBeTruthy();expect(puts).toBe(1);expect(gets).toBe(2)});
 it("clears a persisted answer with DELETE and the next save creates with null CAS",async()=>{const requests:{url:string;init?:RequestInit}[]=[];const persisted=answer("i1","old");renderDraft(async(url,init)=>{requests.push({url,init});if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="DELETE")return ok(null,204);if(init?.method==="PUT")return ok(answer("i1",JSON.parse(String(init.body)).raw_answer,"T2"));return ok(attempt([persisted]))},[persisted]);const input=await screen.findByDisplayValue("old");await userEvent.click(screen.getByRole("button",{name:"Очистить ответ"}));expect((input as HTMLInputElement).value).toBe("");expect(requests.find(r=>r.init?.method==="DELETE")?.url).toContain("/attempts/s1/answers/i1");await userEvent.type(input,"new");await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));expect(JSON.parse(String(requests.find(r=>r.init?.method==="PUT")?.init?.body))).toEqual({raw_answer:"new",expected_updated_at:null})});
 it("persists an empty multiple-choice array with PUT, never DELETE",async()=>{const mutations:RequestInit[]=[];renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method){mutations.push(init);return ok(answer("i2",[],"T2"))}return ok(attempt([answer("i2",["old"],"T1")]))});await screen.findByText(/Черновик/);await userEvent.click(screen.getByRole("button",{name:"2"}));await userEvent.click(screen.getByRole("button",{name:"Удалить вариант 1"}));await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));expect(mutations.map(x=>x.method)).toEqual(["PUT"]);expect(JSON.parse(String(mutations[0].body))).toEqual({raw_answer:[],expected_updated_at:"T1"});expect(screen.getByText("Отвечено 1 из 6")).toBeTruthy()});
 it.each([{button:"4",label:"Число",raw:" 001,2300e2 "},{button:"5",label:"Выражение",raw:"  x + X  "},{button:"6",label:"Развёрнутый ответ",raw:"  line 1\r\nline 2  "}])("preserves exact $label raw in PUT",async({button,label,raw})=>{let payload:any;renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="PUT"){payload=JSON.parse(String(init.body));return ok(answer(button==="4"?"i4":button==="5"?"i5":"i6",payload.raw_answer,"T2"))}return ok(attempt())});await screen.findByText(/Черновик/);await userEvent.click(screen.getByRole("button",{name:button}));const control=screen.getByLabelText(label);if(raw.includes("\r\n")){Object.defineProperty(control,"value",{configurable:true,value:raw});fireEvent.input(control)}else fireEvent.change(control,{target:{value:raw}});await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));await waitFor(()=>expect(payload).toBeTruthy());expect(payload).toEqual({raw_answer:raw,expected_updated_at:null})});
 it("preserves multiple-choice array ordering",async()=>{let payload:any;renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="PUT"){payload=JSON.parse(String(init.body));return ok(answer("i2",payload.raw_answer,"T2"))}return ok(attempt())});await screen.findByText(/Черновик/);await userEvent.click(screen.getByRole("button",{name:"2"}));await userEvent.click(screen.getByRole("button",{name:"Добавить вариант"}));await userEvent.type(screen.getByLabelText("Вариант 1"),"b");await userEvent.click(screen.getByRole("button",{name:"Добавить вариант"}));await userEvent.type(screen.getByLabelText("Вариант 2"),"a");await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));expect(payload.raw_answer).toEqual(["b","a"])});
 it("keeps unsaved raw and app dirty state across item navigation",async()=>{const {spy,onDirtyChange}=renderDraft(async url=>url.includes("/assignments/")?ok(assignment):ok(attempt()));const input=await screen.findByLabelText("ID выбранного варианта");await userEvent.type(input,"local");await waitFor(()=>expect(onDirtyChange).toHaveBeenCalledWith(true));await userEvent.click(screen.getByRole("button",{name:"2"}));await userEvent.click(screen.getByRole("button",{name:"1"}));expect(screen.getByDisplayValue("local")).toBeTruthy();expect(spy.mock.calls.some(([,init])=>init?.method==="PUT")).toBe(false)});
 it.each(["assignment_deadline_passed","assignment_closed"])("preserves local raw and blocks mutations after %s",async code=>{renderDraft(async(url,init)=>{if(url.includes("/assignments/"))return ok(assignment);if(init?.method==="PUT")return apiError(code,code,409);return ok(attempt())});const input=await screen.findByLabelText("ID выбранного варианта");await userEvent.type(input,"keep me");await userEvent.click(screen.getByRole("button",{name:"Сохранить ответ"}));expect(await screen.findByText(code==="assignment_closed"?"Работа закрыта.":"Срок выполнения работы завершён.")).toBeTruthy();expect(input).toHaveProperty("value","keep me");expect(screen.queryByText("Ответ сохранён")).toBeNull();expect(screen.queryByRole("button",{name:"Сохранить ответ"})).toBeNull()});
});

describe("Student assignment detail authority states",()=>{
 it("prevents a duplicate START while the first command is pending",async()=>{let resolve!:(value:Response)=>void,starts=0;vi.spyOn(globalThis,"fetch").mockImplementation(async(_url,init)=>{if(!init?.method)return ok(assignment);starts++;return new Promise(r=>resolve=r)});const navigate=vi.fn();render(<StudentAssignmentDetailPage assignmentId="a1" navigate={navigate}/>);const button=await screen.findByRole("button",{name:"Начать попытку"});await userEvent.click(button);await userEvent.click(button);expect(starts).toBe(1);resolve(ok(attempt()));await waitFor(()=>expect(navigate).toHaveBeenCalledTimes(1))});
 it.each([{value:{...assignment,attempt_count:2,max_attempts:2},message:"Лимит попыток исчерпан."},{value:{...assignment,status:"closed" as const},message:"Работа закрыта."}])("disables START for $message",async({value,message})=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(ok(value));render(<StudentAssignmentDetailPage assignmentId="a1" navigate={vi.fn()}/>);expect(await screen.findByText(message)).toBeTruthy();expect(screen.queryByRole("button",{name:"Начать попытку"})).toBeNull()});
 it.each(["assignment_not_started","attempt_limit_reached"])("shows authoritative START error %s",async code=>{vi.spyOn(globalThis,"fetch").mockImplementation(async(_url,init)=>init?.method?apiError(code,code,409):ok(assignment));render(<StudentAssignmentDetailPage assignmentId="a1" navigate={vi.fn()}/>);await userEvent.click(await screen.findByRole("button",{name:"Начать попытку"}));expect(await screen.findByText(code==="assignment_not_started"?"Работа ещё не началась.":"Лимит попыток исчерпан.")).toBeTruthy()});
});
