import {afterEach,describe,expect,it,vi} from "vitest";import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {StudentRemediationDetailPage} from "./StudentRemediationsPage";import * as api from "./remediationApi";
vi.mock("./remediationApi",async original=>{const actual=await original<typeof import("./remediationApi")>();return {...actual,getStudentRemediationExecution:vi.fn(),startRemediation:vi.fn(),saveRemediationAnswer:vi.fn(),deleteRemediationAnswer:vi.fn(),submitRemediation:vi.fn()}});
const get=vi.mocked(api.getStudentRemediationExecution),start=vi.mocked(api.startRemediation),save=vi.mocked(api.saveRemediationAnswer),del=vi.mocked(api.deleteRemediationAnswer),submit=vi.mocked(api.submitRemediation);
const item=(format="short_text",extra={})=>({remediation_plan_item_id:`item-${format}`,position:0,task_version_id:"v",task_title:"Задача",task_statement:"Ответьте",student_raw_answer:"мой ответ",task_type:"problem",answer_format:format,difficulty:10,choice_options:format.includes("choice")?[{option_id:"a",content:"A"},{option_id:"b",content:"B"}]:[],result_status:null,score_suggested:null,max_score:null,student_feedback:null,...extra});
const execution=(status:string,extra={})=>({remediation_id:"rem",title:"Отработка",instructions:"Инструкция",plan_status:status==="cancelled"?"cancelled":"assigned",due_at:null,execution_status:status,submission_id:status==="not_started"?null:"sub",submission_status:status==="not_started"?null:status==="in_progress"?"draft":"submitted",attempt_no:status==="not_started"?null:1,started_at:null,submitted_at:null,check_run_id:null,check_run_status:null,items:[item()],...extra});
afterEach(()=>{cleanup();vi.clearAllMocks();vi.restoreAllMocks()});
describe("StudentRemediationDetailPage C9 execution",()=>{
 it.each([["not_started","Не начато"],["in_progress","Выполняется"],["submitted","Сдано. Проверка ещё не началась."],["checking","Проверяется"],["checked","Проверено"],["review_required","Требуется проверка учителя."],["check_failed","Ошибка проверки"],["expired","Срок выполнения истёк."],["cancelled","Отработка отменена учителем."]])("renders %s accessibly",async(status,label)=>{get.mockResolvedValue(execution(status) as any);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);expect((await screen.findAllByText(label)).length).toBeGreaterThan(0);if(["expired","cancelled"].includes(status))expect(screen.queryByRole("button",{name:"Сохранить ответ"})).toBeNull()});
 it.each([["pending","В очереди на проверку"],["running","Проверяется"],["failed_retryable","Проверка временно не завершена."],["failed_terminal","Не удалось завершить проверку."]])("renders check run %s safely",async(run,label)=>{get.mockResolvedValue(execution("checking",{check_run_status:run}) as any);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);expect(await screen.findByText(label)).toBeTruthy()});
 it("starts on the server and reloads instead of inventing local state",async()=>{get.mockResolvedValueOnce(execution("not_started") as any).mockResolvedValueOnce(execution("in_progress") as any);start.mockResolvedValue(execution("in_progress") as any);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);await userEvent.click(await screen.findByRole("button",{name:"Начать отработку"}));await waitFor(()=>expect(start).toHaveBeenCalledWith("rem"));expect(get).toHaveBeenCalledTimes(2);expect(await screen.findByText("Выполняется")).toBeTruthy()});
 it("uses the shared editors and remediation save/delete APIs",async()=>{get.mockResolvedValue(execution("in_progress",{items:[item("single_choice",{student_raw_answer:null}),item("multiple_choice",{student_raw_answer:[]}),item("short_text"),item("number",{student_raw_answer:3}),item("long_text")]}) as any);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);await screen.findByText("Отработка");expect(screen.getAllByText("Ответьте")).toHaveLength(5);const text=screen.getAllByRole("textbox")[2];await userEvent.clear(text);await userEvent.type(text,"новый");await userEvent.click(screen.getAllByRole("button",{name:"Сохранить ответ"})[2]);await waitFor(()=>expect(save).toHaveBeenCalledWith("rem","item-short_text","новый"));await userEvent.click(screen.getAllByRole("button",{name:"Очистить ответ"})[2]);expect(del).toHaveBeenCalledWith("rem","item-short_text")});
 it("confirms submit, reports success, and reloads",async()=>{get.mockResolvedValueOnce(execution("in_progress") as any).mockResolvedValueOnce(execution("submitted") as any);submit.mockResolvedValue(execution("submitted") as any);vi.spyOn(globalThis,"confirm").mockReturnValue(true);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);await userEvent.click(await screen.findByRole("button",{name:"Сдать отработку"}));expect(confirm).toHaveBeenCalled();await screen.findByText("Отработка отправлена на проверку.");expect(submit).toHaveBeenCalledTimes(1);expect(get).toHaveBeenCalledTimes(2)});
 it.each(["submitted","checking","checked","review_required"])("reconciles an ambiguous submit to durable %s without retry",async(status)=>{get.mockResolvedValueOnce(execution("in_progress") as any).mockResolvedValueOnce(execution(status) as any);submit.mockRejectedValue(new TypeError("network"));vi.spyOn(globalThis,"confirm").mockReturnValue(true);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);await userEvent.click(await screen.findByRole("button",{name:"Сдать отработку"}));expect(await screen.findByText("Отработка отправлена на проверку.")).toBeTruthy();expect(submit).toHaveBeenCalledTimes(1)});
 it("reports an ambiguous submit that remains in progress",async()=>{get.mockResolvedValueOnce(execution("in_progress") as any).mockResolvedValueOnce(execution("in_progress") as any);submit.mockRejectedValue(new TypeError("network"));vi.spyOn(globalThis,"confirm").mockReturnValue(true);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);await userEvent.click(await screen.findByRole("button",{name:"Сдать отработку"}));expect(await screen.findByText(/Не удалось подтвердить отправку/)).toBeTruthy();expect(submit).toHaveBeenCalledTimes(1)});
 it("shows only the bounded student result and suppresses review feedback/internal fields",async()=>{get.mockResolvedValue(execution("review_required",{items:[item("short_text",{result_status:"unclear",score_suggested:4,max_score:10,student_feedback:"UNSAFE UNCERTAIN",teacher_summary:"PRIVATE TEACHER",findings:[{snapshot_title:"PRIVATE DIAGNOSTIC"}],skill_id:"PRIVATE SKILL",typical_error_id:"PRIVATE ERROR",review_reason:"PRIVATE REASON",model_limitations:"PRIVATE LIMIT",rubric:"PRIVATE RUBRIC",expected_solution:"PRIVATE SOLUTION",accepted_answers:["PRIVATE ACCEPTED"],provider:"PRIVATE PROVIDER"})]}) as any);render(<StudentRemediationDetailPage id="rem" navigate={vi.fn()}/>);await screen.findByText("Требуется проверка учителя.");expect(screen.getByText("мой ответ")).toBeTruthy();expect(screen.getByText("Предварительный балл: 4 из 10")).toBeTruthy();for(const secret of ["UNSAFE UNCERTAIN","PRIVATE TEACHER","PRIVATE DIAGNOSTIC","PRIVATE SKILL","PRIVATE ERROR","PRIVATE REASON","PRIVATE LIMIT","PRIVATE RUBRIC","PRIVATE SOLUTION","PRIVATE ACCEPTED","PRIVATE PROVIDER"])expect(document.body.textContent).not.toContain(secret)});
});
