// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {FolderBrowser} from "./FolderBrowser";
const subject={id:"s1",name:"Математика"},tag=(id:string,name:string,status="active")=>({id,name,normalized_name:name.toLowerCase(),category:{code:"exam",name:"Экзамен",sort_order:1},subject:null,status,replacement:null,created_at:"",created_by:"",updated_at:"",updated_by:""});
const level={subject,folder:null,breadcrumb:[],folders:[],tasks:{items:[],total:0,offset:0,limit:20},level_task_total:0,subject_task_total:0};
const json=(x:any,status=200)=>Promise.resolve(new Response(JSON.stringify(x),{status,headers:{"Content-Type":"application/json"}}));
function server(){return vi.fn((input:RequestInfo|URL)=>{const u=String(input);if(u.includes("/tags?") )return json({items:[tag("a","ОГЭ"),tag("b","Практика")],total:2,offset:0,limit:50});if(u.match(/\/tags\/a$/))return json(tag("a","ОГЭ"));if(u.match(/\/tags\/b$/))return json(tag("b","Практика"));if(u.match(/\/tags\/old$/))return json({...tag("old","Старый","deprecated"),replacement:{id:"a",name:"ОГЭ",category_code:"exam",subject_id:null,status:"active"}});if(u.includes("folders/tree"))return json({subject,folders:[]});if(u.includes("/catalog/"))return json({items:[]});return json(level)})}
async function view(url="/content-bank/subjects/s1",folderId:null|string=null){history.replaceState({},"",url);const f=server();vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" folderId={folderId} navigate={()=>{}}/>);await screen.findByRole("button",{name:"Добавить фильтр"});return f}
async function add(){await userEvent.click(screen.getByRole("button",{name:"Добавить фильтр"}));await userEvent.click(screen.getByRole("button",{name:"Теги"}))}
async function choose(name="ОГЭ"){const input=await screen.findByRole("combobox",{name:"Поиск: Теги"});await userEvent.type(input,name[0]);await userEvent.click(await screen.findByRole("option",{name:new RegExp(name)}))}
afterEach(()=>{cleanup();vi.restoreAllMocks();history.replaceState({},"","/")});
describe("compact tag filter integration",()=>{
 it("is absent until added",async()=>{await view();expect(screen.queryByRole("combobox",{name:"Поиск: Теги"})).toBeNull()});
 it("is added through compact filters",async()=>{await view();await add();expect(screen.getByRole("combobox",{name:"Поиск: Теги"})).toBeTruthy()});
 it("requests active subject-compatible catalog",async()=>{const f=await view();await add();await userEvent.click(screen.getByRole("combobox",{name:"Поиск: Теги"}));await waitFor(()=>expect(f.mock.calls.some(x=>{const u=new URL(String(x[0]));return u.pathname.endsWith("/tags")&&u.searchParams.get("status")==="active"&&u.searchParams.get("subject_id")==="s1"})).toBe(true))});
 it("selects one and serializes one tag_id",async()=>{await view();await add();await choose();expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["a"])});
 it("selects multiple as repeated parameters",async()=>{await view();await add();await choose();await choose("Практика");expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["a","b"]);expect(location.search).not.toContain("a%2Cb")});
 it("sends repeated IDs to subject contents",async()=>{const f=await view();await add();await choose();await choose("Практика");await waitFor(()=>expect(f.mock.calls.some(x=>new URL(String(x[0])).searchParams.getAll("tag_id").join() === "a,b")).toBe(true))});
 it("sends repeated IDs inside a folder without changing pathname",async()=>{const f=await view("/content-bank/subjects/s1/folders/f1","f1");await add();await choose();expect(location.pathname).toBe("/content-bank/subjects/s1/folders/f1");await waitFor(()=>expect(f.mock.calls.some(x=>String(x[0]).includes("/folders/f1/contents")&&new URL(String(x[0])).searchParams.get("tag_id")==="a")).toBe(true))});
 it("explains AND semantics",async()=>{await view();await add();expect(screen.getByText("Задания должны содержать все выбранные теги.")).toBeTruthy()});
 it("prevents duplicate selection",async()=>{await view();await add();await choose();await userEvent.click(screen.getByRole("combobox",{name:"Поиск: Теги"}));expect(screen.queryByRole("option",{name:/ОГЭ/})).toBeNull()});
 it("removes one chip only",async()=>{await view();await add();await choose();await choose("Практика");await userEvent.click(screen.getByRole("button",{name:"Удалить тег «ОГЭ»"}));expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["b"])});
 it("removes the whole filter",async()=>{await view();await add();await choose();await userEvent.click(screen.getByRole("button",{name:"Убрать фильтр “Теги”"}));expect(new URLSearchParams(location.search).has("tag_id")).toBe(false);expect(screen.queryByRole("combobox",{name:"Поиск: Теги"})).toBeNull()});
 it("resets offset while preserving q difficulty and sort",async()=>{await view("/content-bank/subjects/s1?q=x&difficulty_min=10&sort_by=title&offset=40");await add();await choose();const p=new URLSearchParams(location.search);expect(p.get("offset")).toBe("0");expect(p.get("q")).toBe("x");expect(p.get("difficulty_min")).toBe("10");expect(p.get("sort_by")).toBe("title")});
 it("restores and deduplicates a direct URL",async()=>{const f=await view("/content-bank/subjects/s1?tag_id=a&tag_id=a&tag_id=b");expect(await screen.findByText("ОГЭ")).toBeTruthy();expect(await screen.findByText("Практика")).toBeTruthy();expect(f.mock.calls.filter(x=>String(x[0]).endsWith("/tags/a"))).toHaveLength(1);expect(new URL(String(f.mock.calls.find(x=>String(x[0]).includes("/contents?"))![0])).searchParams.getAll("tag_id")).toEqual(["a","b"])});
 it("restores deprecated direct ID visibly",async()=>{await view("/content-bank/subjects/s1?tag_id=old");expect(await screen.findByText("Старый")).toBeTruthy();expect(screen.getByText("Устарел")).toBeTruthy()});
 it("handles unknown direct ID without raw UUID",async()=>{const f=server();f.mockImplementation((input:any)=>String(input).endsWith("/tags/missing")?json({error:{code:"tag_not_found",message:"raw"}},404):server()(input));history.replaceState({},"","/content-bank/subjects/s1?tag_id=missing");vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={()=>{}}/>);expect(await screen.findByText("Недоступный тег")).toBeTruthy();expect(screen.queryByText("missing")).toBeNull();expect(await screen.findByRole("alert")).toBeTruthy()});
 it("Back restores previous selection",async()=>{await view();await add();await choose();history.pushState({},"","/content-bank/subjects/s1?tag_id=b");dispatchEvent(new PopStateEvent("popstate"));expect(await screen.findByText("Практика")).toBeTruthy()});
 it("pagination preserves selected IDs",async()=>{const f=await view("/content-bank/subjects/s1?tag_id=a");await screen.findByText("ОГЭ");expect(f.mock.calls.some(x=>String(x[0]).includes("tag_id=a"))).toBe(true)});
});

describe("filter request resilience",()=>{
 it("catalog retry keeps direct URL selection and hides raw backend error",async()=>{history.replaceState({},"","/content-bank/subjects/s1?tag_id=a");let catalogs=0;const f=vi.fn((input:any)=>{const u=String(input);if(u.endsWith("/tags/a"))return json(tag("a","ОГЭ"));if(u.includes("/tags?")){catalogs++;return catalogs===1?json({error:{code:"future",message:"RAW STACK"}},500):json({items:[tag("b","Практика")],total:1,offset:0,limit:50})}if(u.includes("folders/tree"))return json({subject,folders:[]});if(u.includes("/catalog/"))return json({items:[]});return json(level)});vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={()=>{}}/>);expect(await screen.findByText("ОГЭ")).toBeTruthy();await userEvent.click(screen.getByRole("combobox",{name:"Поиск: Теги"}));expect(await screen.findByText("Не удалось загрузить теги.")).toBeTruthy();expect(screen.queryByText(/RAW STACK/)).toBeNull();expect(screen.getByText("ОГЭ")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"Повторить"}));expect(await screen.findByRole("option",{name:/Практика/})).toBeTruthy();expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["a"]);expect(catalogs).toBe(2)});
 it("late catalog A cannot replace B or clear selected chip",async()=>{history.replaceState({},"","/content-bank/subjects/s1?tag_id=a");let resolveA!:(r:Response)=>void;const pending=new Promise<Response>(r=>resolveA=r);const f=vi.fn((input:any)=>{const u=String(input);if(u.endsWith("/tags/a"))return json(tag("a","ОГЭ"));if(u.includes("/tags?")){const q=new URL(u).searchParams.get("q");return q==="а"?pending:json({items:[tag("b","Бета")],total:1,offset:0,limit:50})}if(u.includes("folders/tree"))return json({subject,folders:[]});if(u.includes("/catalog/"))return json({items:[]});return json(level)});vi.stubGlobal("fetch",f);render(<FolderBrowser subjectId="s1" navigate={()=>{}}/>);await screen.findByText("ОГЭ");const input=screen.getByRole("combobox",{name:"Поиск: Теги"});await userEvent.type(input,"а");await userEvent.clear(input);await userEvent.type(input,"б");expect(await screen.findByRole("option",{name:/Бета/})).toBeTruthy();resolveA(new Response(JSON.stringify({items:[tag("old","Альфа")],total:1,offset:0,limit:50}),{status:200,headers:{"Content-Type":"application/json"}}));await Promise.resolve();expect(screen.queryByText("Альфа")).toBeNull();expect(screen.getByRole("option",{name:/Бета/})).toBeTruthy();expect(screen.getByText("ОГЭ")).toBeTruthy()});
 it("Back and Forward restore exact chips and contents queries",async()=>{const f=await view();await add();await choose();await choose("Практика");expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["a","b"]);history.back();await waitFor(()=>expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["a"]));expect(screen.getByText("ОГЭ")).toBeTruthy();expect(screen.queryByText("Практика")).toBeNull();history.forward();await waitFor(()=>expect(new URLSearchParams(location.search).getAll("tag_id")).toEqual(["a","b"]));expect(await screen.findByText("Практика")).toBeTruthy();expect(f.mock.calls.some(x=>new URL(String(x[0])).searchParams.getAll("tag_id").join() === "a,b")).toBe(true)});
});
