import {useEffect,useId,useRef,useState} from "react";
import {ApiError,getTags,type ManagedTag,type TagRef} from "./api";

const categoryNames:Record<string,string>={exam:"Экзамен",purpose:"Назначение",methodology:"Методика",task_feature:"Особенность задания",usage_level:"Уровень использования"};
export const tagErrorText=(error:unknown)=>{if(!(error instanceof ApiError))return "Не удалось выполнить действие с тегами.";return ({tag_concurrent_modification:"Теги уже изменены в другой вкладке.",task_version_not_found:"Версия задания не найдена.",task_version_not_editable:"Теги можно менять только у последней черновой версии.",tag_not_found:"Один из тегов больше не существует.",tag_deprecated:"Устаревший тег нельзя добавить.",tag_subject_mismatch:"Тег относится к другому предмету.",duplicate_tag_assignment:"Тег выбран повторно.",tag_limit_exceeded:"Можно выбрать не более восьми тегов."} as Record<string,string>)[error.code]||error.message||"Не удалось сохранить теги."};

export function TagChips({tags,limit,removable=false,onRemove}:{tags:TagRef[];limit?:number;removable?:boolean;onRemove?:(id:string)=>void}){if(!tags.length)return null;const shown=limit?tags.slice(0,limit):tags,hidden=tags.slice(shown.length);const all=tags.map(x=>`${x.name}${x.status==="deprecated"?" (устарел)":""}`).join(", ");return <div className="tag-chips" aria-label={`Теги: ${all}`}>{shown.map(tag=><span className={`tag-chip ${tag.status==="deprecated"?"deprecated":""}`} key={tag.id} title={tag.replacement?`Устарел. Рекомендуется: ${tag.replacement.name}`:tag.status==="deprecated"?"Устарел":undefined}>{tag.name}{tag.status==="deprecated"&&<small> Устарел</small>}{removable&&<button type="button" aria-label={`Удалить тег «${tag.name}»`} onClick={()=>onRemove?.(tag.id)}>×</button>}</span>)}{hidden.length>0&&<span className="tag-more" title={`Скрытые теги: ${hidden.map(x=>x.name).join(", ")}`} aria-label={`Ещё ${hidden.length}: ${hidden.map(x=>x.name).join(", ")}`}>+{hidden.length}</span>}</div>}

export function TagPicker({subjectId,value,onChange,label="Теги",disabled=false}:{subjectId?:string;value:TagRef[];onChange:(tags:TagRef[])=>void;label?:string;disabled?:boolean}){const id=useId(),[query,setQuery]=useState(""),[items,setItems]=useState<ManagedTag[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[open,setOpen]=useState(false),[active,setActive]=useState(0),[retry,setRetry]=useState(0),seq=useRef(0);
 useEffect(()=>{if(disabled||!open)return;const controller=new AbortController(),current=++seq.current;setLoading(true);setError("");const p=new URLSearchParams({status:"active",limit:"50"});if(subjectId)p.set("subject_id",subjectId);if(query.trim())p.set("q",query.trim());getTags(p,controller.signal).then(x=>{if(current===seq.current){setItems(Array.isArray(x.items)?x.items:[]);setActive(0)}}).catch(e=>{if(current===seq.current&&e?.name!=="AbortError")setError("Не удалось загрузить теги.")}).finally(()=>{if(current===seq.current)setLoading(false)});return()=>controller.abort()},[subjectId,query,retry,disabled,open]);
 const available=items.filter(x=>!value.some(v=>v.id===x.id));const add=(tag:ManagedTag)=>{if(value.length>=8||value.some(x=>x.id===tag.id))return;onChange([...value,{id:tag.id,name:tag.name,category_code:tag.category.code,subject_id:tag.subject?.id??null,status:tag.status,replacement:tag.replacement}]);setQuery("");setOpen(false)};
 return <div className="tag-picker"><label htmlFor={id}>{label} <span className="optional-note">(необязательно)</span></label><TagChips tags={value} removable={!disabled} onRemove={tagId=>onChange(value.filter(x=>x.id!==tagId))}/>{!disabled&&value.length>0&&<button type="button" className="link-button" onClick={()=>onChange([])}>Очистить все теги</button>}{!disabled&&<><input id={id} role="combobox" aria-label={`Поиск: ${label}`} aria-expanded={open} aria-controls={`${id}-options`} aria-activedescendant={open&&available[active]?`${id}-${available[active].id}`:undefined} autoComplete="off" placeholder="Найти канонический тег" value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setOpen(true);setActive(x=>Math.min(x+1,available.length-1))}if(e.key==="ArrowUp"){e.preventDefault();setActive(x=>Math.max(0,x-1))}if(e.key==="Enter"&&open&&available[active]){e.preventDefault();add(available[active])}if(e.key==="Escape")setOpen(false)}} disabled={value.length>=8}/>{value.length>=8&&<p role="status">Выбрано максимальное количество: 8.</p>}{open&&<div id={`${id}-options`} role="listbox" className="tag-options">{loading?<p role="status">Загрузка тегов…</p>:error?<div className="alert error" role="alert">{error} <button type="button" onClick={()=>setRetry(x=>x+1)}>Повторить</button></div>:available.length?available.map((tag,index)=><button type="button" role="option" aria-selected={index===active} id={`${id}-${tag.id}`} key={tag.id} onMouseDown={e=>e.preventDefault()} onClick={()=>add(tag)}>{tag.name}<small>{tag.category.name||categoryNames[tag.category.code]} · {tag.subject?.name??"Для всех предметов"}</small></button>):<p>{query?"Совпадений не найдено.":"Доступных тегов пока нет."}</p>}</div>}</>}</div>}
