import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {useState} from "react";
import {afterEach,describe,expect,it,vi} from "vitest";
import {TagChips,TagPicker,tagErrorText} from "./TagPicker";
import {ApiError,type TagRef} from "./api";
const tag=(id:string,name=`Тег ${id}`,subject:string|null=null):any=>({id,name,normalized_name:name.toLowerCase(),category:{code:"exam",name:"Экзамен",sort_order:1},subject:subject?{id:subject,name:"Математика"}:null,status:"active",replacement:null,created_at:"",created_by:"",updated_at:"",updated_by:""});
const response=(items:any[])=>new Response(JSON.stringify({items,total:items.length,offset:0,limit:50}),{status:200,headers:{"Content-Type":"application/json"}});
function Host({initial=[] as TagRef[],subject="s"}){const [value,setValue]=useState(initial);return <TagPicker subjectId={subject} value={value} onChange={setValue}/>}
afterEach(()=>vi.restoreAllMocks());
describe("TagPicker",()=>{
 it("loads active compatible catalog with subject and canonical search",async()=>{const f=vi.spyOn(globalThis,"fetch").mockResolvedValue(response([tag("1")]));render(<Host/>);await userEvent.click(screen.getByRole("combobox"));await screen.findByText("Тег 1");expect(String(f.mock.calls[0][0])).toContain("status=active");expect(String(f.mock.calls[0][0])).toContain("subject_id=s")});
 it("selects by keyboard",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(response([tag("1")]));render(<Host/>);const input=screen.getByRole("combobox");await userEvent.click(input);await screen.findByText("Тег 1");await userEvent.keyboard("{Enter}");expect(screen.getByLabelText(/Теги: Тег 1/)).toBeTruthy()});
 it("does not offer selected duplicate",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(response([tag("1")]));render(<Host initial={[{id:"1",name:"Тег 1",category_code:"exam",subject_id:null,status:"active"}]}/>);await userEvent.click(screen.getByRole("combobox"));await waitFor(()=>expect(screen.getByText("Доступных тегов пока нет.")).toBeTruthy())});
 it("removes one accessible chip",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(response([]));render(<Host initial={[{id:"1",name:"ОГЭ",category_code:"exam",subject_id:null,status:"active"}]}/>);await userEvent.click(screen.getByRole("button",{name:"Удалить тег «ОГЭ»"}));expect(screen.queryByText("ОГЭ")).toBeNull()});
 it("clears all",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(response([]));render(<Host initial={[{id:"1",name:"ОГЭ",category_code:"exam",subject_id:null,status:"active"}]}/>);await userEvent.click(screen.getByText("Очистить все теги"));expect(screen.queryByText("ОГЭ")).toBeNull()});
 it("enforces eight tag limit",()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue(response([]));render(<Host initial={Array.from({length:8},(_,i)=>({id:String(i),name:`T${i}`,category_code:"exam",subject_id:null,status:"active"}))}/>);expect((screen.getByRole("combobox") as HTMLInputElement).disabled).toBe(true);expect(screen.getByText(/максимальное количество/)).toBeTruthy()});
 it("shows loading without false empty",()=>{vi.spyOn(globalThis,"fetch").mockReturnValue(new Promise(()=>{}));render(<Host/>);expect(screen.queryByText("Доступных тегов пока нет.")).toBeNull()});
 it("shows safe error and retry",async()=>{const f=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(new Response("{}",{status:500})).mockResolvedValueOnce(response([]));render(<Host/>);await userEvent.click(screen.getByRole("combobox"));await screen.findByText("Не удалось загрузить теги.");await userEvent.click(screen.getByText("Повторить"));await waitFor(()=>expect(f).toHaveBeenCalledTimes(2))});
 it("late response cannot replace current search",async()=>{let resolveA!:(x:Response)=>void;const a=new Promise<Response>(r=>resolveA=r);const f=vi.spyOn(globalThis,"fetch").mockReturnValueOnce(a).mockResolvedValueOnce(response([tag("b","Beta")]));render(<Host/>);const input=screen.getByRole("combobox");await userEvent.type(input,"b");await screen.findByText("Beta");resolveA(response([tag("a","Alpha")]));await Promise.resolve();expect(screen.queryByText("Alpha")).toBeNull();expect(f).toHaveBeenCalledTimes(2)});
 it("renders deprecated replacement and compact overflow accessibly",()=>{render(<TagChips limit={3} tags={[{id:"1",name:"Старый",category_code:"exam",subject_id:null,status:"deprecated",replacement:{id:"r",name:"Новый",category_code:"exam",subject_id:null,status:"active"}},...Array.from({length:3},(_,i)=>({id:`x${i}`,name:`X${i}`,category_code:"exam",subject_id:null,status:"active" as const}))]}/>);expect(screen.getByText("Устарел")).toBeTruthy();expect(screen.getByLabelText(/Ещё 1/)).toBeTruthy();expect(screen.getByText("Старый").title).toContain("Новый")});
 it("localizes every assignment contract error and future fallback",()=>{for(const code of ["tag_concurrent_modification","task_version_not_found","task_version_not_editable","tag_not_found","tag_deprecated","tag_subject_mismatch","duplicate_tag_assignment","tag_limit_exceeded"])expect(tagErrorText(new ApiError(409,code,"raw"))).not.toBe("raw");expect(tagErrorText(new ApiError(500,"future","Безопасно"))).toBe("Безопасно")});
});
