// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {TaskCard} from "./main";
const ref=(id:string,name:string,status="active")=>({id,name,category_code:"exam",subject_id:null,status,replacement:null});
const catalog=(id:string,name:string)=>({...ref(id,name),normalized_name:name.toLowerCase(),category:{code:"exam",name:"Экзамен",sort_order:1},subject:null,created_at:"",created_by:"",updated_at:"",updated_by:""});
const card=(status="draft",updated_at="A",tags:any[]=[ref("a","ОГЭ")])=>({id:"task",subject:{id:"s",name:"Математика"},grade:{id:"g",name:"7"},topic:{id:"t",name:"Алгебра"},subtopic:null,created_by:"actor",created_at:"2026-01-01T00:00:00Z",updated_at,archived_at:status==="archived"?"2026-01-02T00:00:00Z":null,latest_version:{id:"v",version_no:1,title:"Задача",statement:"Условие",task_type:"problem",answer_format:"number",difficulty:25,source:null,status,skills:[],created_by:"actor",created_at:"2026-01-01T00:00:00Z",approved_by:null,approved_at:null,updated_at,methodology:{expected_solution:null,rubric:null,accepted_answers:[],typical_errors:[],hints:[]},tags},approved_version:null,versions:[{id:"v",version_no:1,status,created_at:"2026-01-01T00:00:00Z",approved_at:null,tags}]});
const json=(body:any,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));
function setup(status="draft",handler?:(url:string,init?:RequestInit)=>Promise<Response>){const calls:{url:string,init?:RequestInit}[]=[];vi.stubGlobal("fetch",vi.fn((input:any,init?:RequestInit)=>{const url=String(input);calls.push({url,init});if(handler)return handler(url,init);if(url.includes("/tags?"))return json({items:[catalog("a","ОГЭ"),catalog("b","Практика")],total:2,offset:0,limit:50});if(url.includes("/audit"))return json({items:[],total:0,offset:0,limit:20});if(init?.method==="PUT")return json({task_id:"task",task_version_id:"v",version_no:1,updated_at:"B",tags:[ref("b","Практика")]});return json(card(status))}));render(<TaskCard taskId="task" navigate={()=>{}} onDirtyChange={()=>{}}/>);return calls}
async function addB(){const input=await screen.findByRole("combobox",{name:"Поиск: Теги"});await userEvent.type(input,"П");await userEvent.click(await screen.findByRole("option",{name:/Практика/}))}
afterEach(()=>{cleanup();vi.restoreAllMocks()});
describe("task tag editor integration",()=>{
 it("shows server tags in latest draft",async()=>{setup();expect(await screen.findByText("ОГЭ")).toBeTruthy();expect((screen.getByRole("button",{name:"Сохранить теги"}) as HTMLButtonElement).disabled).toBe(true)});
 it("adding marks editor dirty and enables save",async()=>{setup();await addB();expect((screen.getByRole("button",{name:"Сохранить теги"}) as HTMLButtonElement).disabled).toBe(false)});
 it("no-op never sends assignment PUT",async()=>{const calls=setup();await screen.findByText("ОГЭ");await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));expect(calls.filter(x=>x.init?.method==="PUT")).toHaveLength(0)});
 it("save sends exact full set and CAS timestamp",async()=>{const calls=setup();await addB();await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));await waitFor(()=>expect(calls.some(x=>x.init?.method==="PUT")).toBe(true));const body=JSON.parse(String(calls.find(x=>x.init?.method==="PUT")!.init!.body));expect(body).toEqual({tag_ids:["a","b"],expected_updated_at:"A"})});
 it("double click produces one PUT",async()=>{let resolve!:(r:Response)=>void;const calls=setup("draft",(url,init)=>{if(url.includes("/tags?"))return json({items:[catalog("b","Практика")],total:1,offset:0,limit:50});if(url.includes("/audit"))return json({items:[],total:0,offset:0,limit:20});if(init?.method==="PUT")return new Promise(r=>resolve=r);return json(card())});await addB();await userEvent.dblClick(screen.getByRole("button",{name:"Сохранить теги"}));expect(calls.filter(x=>x.init?.method==="PUT")).toHaveLength(1);resolve(new Response(JSON.stringify({task_id:"task",task_version_id:"v",version_no:1,updated_at:"B",tags:[ref("a","ОГЭ"),ref("b","Практика")]}),{status:200,headers:{"Content-Type":"application/json"}}))});
 it("success adopts server tags",async()=>{setup();await addB();await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));expect((await screen.findByRole("status")).textContent).toContain("Теги сохранены");expect(screen.queryByText("ОГЭ")).toBeNull();expect(screen.getByText("Практика")).toBeTruthy()});
 it("validation error preserves local selection",async()=>{setup("draft",(url,init)=>url.includes("/tags?")?json({items:[catalog("b","Практика")],total:1,offset:0,limit:50}):url.includes("/audit")?json({items:[],total:0,offset:0,limit:20}):init?.method==="PUT"?json({error:{code:"tag_subject_mismatch",message:"raw"}},422):json(card()));await addB();await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));expect((await screen.findByRole("alert")).textContent).toContain("другому предмету");expect(screen.getByText("Практика")).toBeTruthy()});
 it("CAS conflict keeps local state and offers refresh",async()=>{setup("draft",(url,init)=>url.includes("/tags?")?json({items:[catalog("b","Практика")],total:1,offset:0,limit:50}):url.includes("/audit")?json({items:[],total:0,offset:0,limit:20}):init?.method==="PUT"?json({error:{code:"tag_concurrent_modification",message:"raw"}},409):json(card()));await addB();await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));expect(await screen.findByRole("button",{name:"Загрузить актуальную версию"})).toBeTruthy();expect(screen.getByText("Практика")).toBeTruthy()});
 it("review is read-only",async()=>{setup("review");expect(await screen.findByText("ОГЭ")).toBeTruthy();expect(screen.queryByRole("combobox",{name:"Поиск: Теги"})).toBeNull()});
 it("approved is read-only",async()=>{setup("approved");expect(await screen.findByText("ОГЭ")).toBeTruthy();expect(screen.queryByRole("button",{name:"Сохранить теги"})).toBeNull()});
 it("archived deprecated association stays visible",async()=>{setup("archived",(url)=>url.includes("/audit")?json({items:[],total:0,offset:0,limit:20}):json(card("archived","A",[{...ref("old","Старый","deprecated"),replacement:ref("a","ОГЭ")}])));expect(await screen.findByText("Старый")).toBeTruthy();expect(screen.getByText("Устарел")).toBeTruthy();expect(screen.queryByRole("combobox",{name:"Поиск: Теги"})).toBeNull()});
});

describe("complete CAS reconciliation",()=>{
 it("uses A, refreshes snapshot B, saves with B, adopts C and sends no third PUT",async()=>{let cardGets=0;const puts:any[]=[];vi.stubGlobal("fetch",vi.fn((input:any,init?:RequestInit)=>{const url=String(input);if(url.includes("/tags?"))return json({items:[catalog("a","ОГЭ"),catalog("b","Практика")],total:2,offset:0,limit:50});if(url.includes("/audit"))return json({items:[],total:0,offset:0,limit:20});if(init?.method==="PUT"){const body=JSON.parse(String(init.body));puts.push(body);return puts.length===1?json({error:{code:"tag_concurrent_modification",message:"raw"}},409):json({task_id:"task",task_version_id:"v",version_no:1,updated_at:"C",tags:[ref("a","ОГЭ"),ref("b","Практика")]})}cardGets++;return json(card("draft",cardGets===1?"A":"B",cardGets===1?[ref("a","ОГЭ")]:[ref("b","Практика")]))}));render(<TaskCard taskId="task" navigate={()=>{}} onDirtyChange={()=>{}}/>);await addB();await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));expect(await screen.findByRole("button",{name:"Загрузить актуальную версию"})).toBeTruthy();expect(puts[0]).toEqual({tag_ids:["a","b"],expected_updated_at:"A"});await userEvent.click(screen.getByRole("button",{name:"Загрузить актуальную версию"}));await waitFor(()=>expect(cardGets).toBe(2));expect(screen.queryByText("ОГЭ")).toBeNull();expect(screen.getByText("Практика")).toBeTruthy();const input=screen.getByRole("combobox",{name:"Поиск: Теги"});await userEvent.type(input,"О");await userEvent.click(await screen.findByRole("option",{name:/ОГЭ/}));await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));await waitFor(()=>expect(puts).toHaveLength(2));expect(puts[1]).toEqual({tag_ids:["b","a"],expected_updated_at:"B"});expect(await screen.findByText("ОГЭ")).toBeTruthy();expect((screen.getByRole("button",{name:"Сохранить теги"}) as HTMLButtonElement).disabled).toBe(true);await userEvent.click(screen.getByRole("button",{name:"Сохранить теги"}));expect(puts).toHaveLength(2)})
});

describe("task card DTO display boundary",()=>{
 it("renders read-only DTO tags and difficulty without catalog or detail N+1",async()=>{const urls:string[]=[];vi.stubGlobal("fetch",vi.fn((input:any)=>{const url=String(input);urls.push(url);if(url.includes("/audit"))return json({items:[],total:0,offset:0,limit:20});return json(card("approved","B",[ref("a","ОГЭ"),{...ref("old","Старый","deprecated"),replacement:ref("new","Новый")}]))}));render(<TaskCard taskId="task" navigate={()=>{}} onDirtyChange={()=>{}}/>);expect(await screen.findByText("ОГЭ")).toBeTruthy();expect(screen.getByText("Старый")).toBeTruthy();expect(screen.getByText("Сложность").nextElementSibling?.textContent).toBe("25");expect(screen.getByText("Старый").title).toContain("Новый");expect(urls.filter(u=>/\/tags(?:\/|\?)/.test(u))).toHaveLength(0)})
});
