import {useCallback,useEffect,useState} from "react";
import {ApiError,closeTeacherAssignment,createPublishedAssessmentAssignment,listAssessments,listClassAssignments,publishAndAssignAssessment,type AssessmentStatus,type AssessmentSummary,type ClassAssignmentSummary} from "./api";
export const assignmentDisplayStatus=(a:Pick<ClassAssignmentSummary,"status"|"start_at"|"due_at">,now=Date.now())=>a.status==="closed"?"Закрыта":now<+new Date(a.start_at)?"Запланирована":now<=+new Date(a.due_at)?"Идёт":"Срок истёк";
const date=(v:string)=>new Date(v).toLocaleString("ru-RU");
export function TeacherClassAssessmentsSection(p:{classId:string;className:string;archived:boolean;activeStudentCount:number;configured:boolean;navigate:(to:string)=>void}){
 const [filter,setFilter]=useState<"all"|"open"|"closed">("all"),[page,setPage]=useState<{items:ClassAssignmentSummary[];total:number}>({items:[],total:0}),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{setPage(await listClassAssignments(p.classId,filter))}catch{setMessage("Не удалось загрузить назначения.")}finally{setLoading(false)}},[p.classId,filter]);useEffect(()=>{load()},[load]);
 const blocked=p.archived?"Новые работы нельзя назначать архивному классу.":!p.configured?"Сначала администратор должен указать класс обучения.":!p.activeStudentCount?"Добавьте учеников в класс перед назначением работы.":"";
 const close=async(a:ClassAssignmentSummary)=>{if(confirm("Закрыть назначение?\n\nУченики больше не смогут начинать, сохранять или отправлять ответы по этой работе.")){await closeTeacherAssignment(a.id);await load()}};
 return <section><div className="section-heading"><h2>Самостоятельные работы</h2><button disabled={!!blocked} onClick={()=>setShow(true)}>Назначить работу</button></div>{blocked&&<p>{blocked}</p>}{message&&<p role="status">{message}</p>}{show&&<Form {...p} done={async m=>{setShow(false);setMessage(m);await load()}} cancel={()=>setShow(false)}/>}<div className="tabs">{([['all','Все'],['open','Открытые'],['closed','Закрытые']] as const).map(([v,l])=><button key={v} onClick={()=>setFilter(v)}>{l}</button>)}</div>{loading?<p>Загрузка работ…</p>:page.items.length?<div className="table-wrap"><table><thead><tr><th>Работа</th><th>Состояние</th><th>Начало</th><th>Срок</th><th>Участники</th><th>Попыток</th><th>Действия</th></tr></thead><tbody>{page.items.map(a=><tr key={a.id}><td>{a.assessment_title}</td><td>{assignmentDisplayStatus(a)}</td><td>{date(a.start_at)}</td><td>{date(a.due_at)}</td><td>{a.participant_count}</td><td>{a.max_attempts}</td><td><button onClick={()=>p.navigate(`/assessments/${a.assessment_id}`)}>Открыть работу</button>{a.status==="open"&&<button onClick={()=>close(a)}>Закрыть</button>}</td></tr>)}</tbody></table></div>:<p>Самостоятельных работ пока нет.</p>}</section>
}
function Form(p:{classId:string;className:string;done:(m:string)=>Promise<void>;cancel:()=>void}){const [status,setStatus]=useState<AssessmentStatus|"all">("all"),[works,setWorks]=useState<AssessmentSummary[]>([]),[work,setWork]=useState<AssessmentSummary>(),[start,setStart]=useState(""),[due,setDue]=useState(""),[attempts,setAttempts]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState("");useEffect(()=>{listAssessments(status==="all"?undefined:status,0,100).then(x=>setWorks(x.items))},[status]);
 const submit=async()=>{if(!work||!start||!due||+new Date(start)>=+new Date(due)||attempts<1||attempts>100){setError("Проверьте начало, срок и максимум попыток (1–100).");return}const body={class_group_id:p.classId,start_at:new Date(start).toISOString(),due_at:new Date(due).toISOString(),max_attempts:attempts};if(!confirm(work.status==="draft"?`Опубликовать работу «${work.title}» и назначить классу «${p.className}»?\n\nПосле публикации содержимое работы нельзя будет изменить.`:`Назначить работу «${work.title}» классу «${p.className}»?`))return;setBusy(true);try{work.status==="draft"?await publishAndAssignAssessment(work.id,body):await createPublishedAssessmentAssignment(work.id,body);await p.done(work.status==="draft"?"Работа опубликована и назначена классу.":"Работа назначена классу.")}catch(e){try{const x=await listClassAssignments(p.classId);if(x.items.some(a=>a.assessment_id===work.id&&a.class_group_id===p.classId&&a.start_at===body.start_at&&a.due_at===body.due_at&&a.max_attempts===body.max_attempts)){await p.done("Назначение подтверждено после обновления данных.");return}}catch{}setError(e instanceof ApiError&&e.code==="invalid_task_version"?"Одно из заданий этой работы больше нельзя использовать для нового назначения.":"Не удалось подтвердить назначение. Обновите данные и повторите действие.")}finally{setBusy(false)}};
 return <div className="assignment-panel"><h3>Назначить работу</h3><label>Показать<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Все</option><option value="draft">Черновики</option><option value="published">Опубликованные</option></select></label><label>Работа<select value={work?.id||""} onChange={e=>setWork(works.find(x=>x.id===e.target.value))}><option value="">Выберите работу</option>{works.map(x=><option key={x.id} value={x.id}>{x.title} — {x.status==="draft"?"Черновик":"Опубликована"} · вариантов: {x.variant_count}</option>)}</select></label>{work&&<p>{work.status==="draft"?"Работа будет опубликована. После публикации её содержимое нельзя будет изменить.":"Будет создано новое назначение этой опубликованной работы. Содержимое работы не изменится."}</p>}<label>Начало<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Срок<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Максимум попыток<input type="number" min={1} max={100} value={attempts} onChange={e=>setAttempts(+e.target.value)}/></label>{error&&<div role="alert">{error}</div>}<button disabled={busy||!work} onClick={submit}>{busy?"Назначение…":work?.status==="draft"?"Опубликовать и назначить":"Назначить классу"}</button><button disabled={busy} onClick={p.cancel}>Отмена</button></div>}
