import {afterEach,describe,expect,it,vi} from "vitest";import {cleanup,render,screen,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {TeacherRemediationBuilderPage} from "./TeacherRemediationBuilderPage";import {getStudentAssignmentResult} from "./classroomResultsApi";import * as api from "./remediationApi";
vi.mock("./classroomResultsApi",()=>({getStudentAssignmentResult:vi.fn()}));vi.mock("./remediationApi",()=>({searchCandidates:vi.fn(),createRemediation:vi.fn(),assignRemediation:vi.fn()}));const source=vi.mocked(getStudentAssignmentResult),search=vi.mocked(api.searchCandidates),create=vi.mocked(api.createRemediation),assign=vi.mocked(api.assignRemediation);
const finding=(type:string,id:string,title:string)=>({finding_id:id,finding_type:type,snapshot_title:title,snapshot_code:null,snapshot_criterion:null,severity:"medium",confidence:".8"});
const result=(review=false)=>({assignment_id:"a",assignment_participant_id:"p",student_id:"s",student_display_name:"Иван",assessment_title:"Алгебра",class_group_id:"c",current_attempt_no:1,current_attempt_status:"submitted",attempts:[{submission_id:"sub",attempt_no:1,status:"submitted",started_at:"x",submitted_at:"x"}],selected_submission_id:"sub",selected_attempt_no:1,latest_check_run_id:"run",latest_check_run_status:"completed",check_status:review?"review_required":"checked",suggested_score_total:"7",max_score_total:"10",diagnostics:{skills:[],typical_errors:[]},items:[{assessment_item_id:"i",position:1,task_version_id:"v",task_title:"Исходная",task_statement:"Условие",student_answer:{},check_result:{check_result_id:"r",result_status:"incorrect",checker_type:"ai",score_suggested:"0",max_score:"1",confidence:".8",summary:"",teacher_summary:null,needs_human_review:review,review_reason:null,model_limitations:null,findings:[finding("skill","f1","Дроби"),finding("typical_error","f2","Знак")]}}]});
const candidate=(n:number)=>({task_id:`t${n}`,task_version_id:`v${n}`,title:`Кандидат ${n}`,statement_preview:"Практика",task_type:"problem",answer_format:"short_text",difficulty:20,primary_skill_name:"Дроби",reasons:[{match_type:"skill",matched_title:"Дроби"}]});
afterEach(()=>{cleanup();vi.clearAllMocks();vi.restoreAllMocks();history.replaceState({},"","/")});
describe("TeacherRemediationBuilderPage C8",()=>{
 it("loads source and diagnostics without automatically creating a remediation",async()=>{source.mockResolvedValue(result() as any);render(<TeacherRemediationBuilderPage classId="c" assignmentId="a" studentId="s" navigate={vi.fn()}/>);expect(await screen.findByText("Самостоятельная работа: Алгебра")).toBeTruthy();expect(screen.getByText("Навык: Дроби")).toBeTruthy();expect(screen.getByText("Типичная ошибка: Знак")).toBeTruthy();expect(screen.getByText("Предварительный балл: 7 / 10")).toBeTruthy();expect(create).not.toHaveBeenCalled()});
 it("supports suggested/manual lookup, add, reorder, remove, and the 20-item limit",async()=>{source.mockResolvedValue(result() as any);search.mockResolvedValue(Array.from({length:21},(_,i)=>candidate(i+1)));render(<TeacherRemediationBuilderPage classId="c" assignmentId="a" studentId="s" navigate={vi.fn()}/>);await screen.findByText("Алгебра",{exact:false});expect(screen.getByRole("button",{name:"По рекомендации"})).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"Подобрать задания"}));expect(await screen.findAllByText(/Почему предложено: Дроби/)).toHaveLength(21);expect(document.body.textContent).not.toMatch(/AI.*балл/i);for(const button of screen.getAllByRole("button",{name:"Добавить"}).slice(0,20))await userEvent.click(button);expect(screen.getByText("20 / 20 заданий")).toBeTruthy();expect((screen.getAllByRole("button",{name:"Добавить"})[20] as HTMLButtonElement).disabled).toBe(true);await userEvent.click(screen.getAllByRole("button",{name:"Вверх"})[1]);await userEvent.click(screen.getAllByRole("button",{name:"Удалить"})[0]);expect(screen.getByText("19 / 20 заданий")).toBeTruthy();await userEvent.click(screen.getByRole("button",{name:"Вручную"}));await userEvent.type(screen.getByLabelText("Поиск заданий"),"проценты");await userEvent.click(screen.getByRole("button",{name:"Подобрать задания"}));expect(search).toHaveBeenLastCalledWith(expect.objectContaining({mode:"manual",q:"проценты",limit:20}))});
 it("saves a draft and sends only after explicit review acknowledgement",async()=>{source.mockResolvedValue(result(true) as any);search.mockResolvedValue([candidate(1)]);create.mockResolvedValue({...candidate(1),id:"rem"} as any);assign.mockResolvedValue({} as any);vi.spyOn(globalThis,"confirm").mockReturnValue(true);render(<TeacherRemediationBuilderPage classId="c" assignmentId="a" studentId="s" navigate={vi.fn()}/>);await screen.findByText("Алгебра",{exact:false});await userEvent.click(screen.getByRole("button",{name:"Подобрать задания"}));await userEvent.click(await screen.findByRole("button",{name:"Добавить"}));const send=screen.getByRole("button",{name:"Отправить ученику"}) as HTMLButtonElement;expect(send.disabled).toBe(true);expect(assign).not.toHaveBeenCalled();await userEvent.click(screen.getByRole("button",{name:"Сохранить черновик"}));expect(await screen.findByText("Черновик отработки сохранён.")).toBeTruthy();expect(JSON.stringify(create.mock.calls[0][0])).not.toMatch(/owner_user_id|actor_user_id/);await userEvent.click(screen.getByRole("checkbox",{name:/Я проверил/}));expect(send.disabled).toBe(false);await userEvent.click(send);await waitFor(()=>expect(assign).toHaveBeenCalledWith("rem",true))});
});
