import {FormEvent,useCallback,useEffect,useState} from "react";
import {ApiError} from "./api";
import {createNote,deleteNote,listNotes,updateNote,type TeacherNote} from "./classroomNotesApi";
const time=(v:string)=>new Date(v).toLocaleString("ru-RU");
export function TeacherNotesSection({classId,studentId,archived,onLost}:{classId:string;studentId?:string;archived:boolean;onLost?:()=>void}){
 const [notes,setNotes]=useState<TeacherNote[]>([]),[body,setBody]=useState(""),[edit,setEdit]=useState<TeacherNote>(),[editBody,setEditBody]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(signal?:AbortSignal)=>{const page=await listNotes(classId,studentId,signal);setNotes(page.items)},[classId,studentId]);
 useEffect(()=>{const c=new AbortController();load(c.signal).catch(x=>{if(x?.name!=="AbortError")setError("Не удалось загрузить заметки.")});return()=>c.abort()},[load]);
 const fail=async(x:unknown)=>{if(x instanceof ApiError&&x.code==="note_concurrent_conflict"){setError("Эта заметка уже была изменена. Данные обновлены.");await load().catch(()=>{})}else if(x instanceof ApiError&&x.code==="student_not_found"){setError("Ученик больше не относится к этому классу.");onLost?.()}else setError("Не удалось сохранить изменения.")};
 const add=async(e:FormEvent)=>{e.preventDefault();if(busy||!body.trim())return;setBusy(true);setError("");try{await createNote(classId,body,studentId);setBody("");await load()}catch(x){await fail(x)}finally{setBusy(false)}};
 const save=async()=>{if(!edit||busy)return;setBusy(true);setError("");try{await updateNote(classId,edit,editBody,studentId);setEdit(undefined);await load()}catch(x){await fail(x)}finally{setBusy(false)}};
 const remove=async(note:TeacherNote)=>{if(busy||!confirm("Удалить заметку?"))return;setBusy(true);setError("");try{await deleteNote(classId,note.id,studentId);await load()}catch(x){await fail(x)}finally{setBusy(false)}};
 return <section className="teacher-notes"><h2>{studentId?"Заметки об ученике":"Заметки о классе"}</h2>{error&&<div className="alert error" role="alert">{error}</div>}<form onSubmit={add}><label>Текст заметки<textarea maxLength={12000} value={body} disabled={archived||busy} onChange={e=>setBody(e.target.value)}/></label><button disabled={archived||busy||!body.trim()}>{busy?"Сохранение…":"Добавить заметку"}</button></form>{archived&&<p className="muted">Новые заметки нельзя добавлять {studentId?"архивному ученику":"в архивный класс"}.</p>}{notes.length===0?<p>Заметок пока нет.</p>:<div className="note-list">{notes.map(note=><article className="note-card" key={note.id}><small>{time(note.created_at)}{note.updated_at!==note.created_at&&<> · Изменено {time(note.updated_at)}</>}</small>{edit?.id===note.id?<><textarea maxLength={12000} value={editBody} onChange={e=>setEditBody(e.target.value)}/><div><button disabled={busy||!editBody.trim()} onClick={save}>Сохранить</button> <button className="secondary" disabled={busy} onClick={()=>setEdit(undefined)}>Отмена</button></div></>:<><p className="note-body">{note.body}</p><div><button className="secondary" disabled={busy} onClick={()=>{setEdit(note);setEditBody(note.body)}}>Изменить</button> <button className="secondary" disabled={busy} onClick={()=>remove(note)}>Удалить</button></div></>}</article>)}</div>}</section>
}
