import {afterEach,describe,expect,it,vi} from "vitest";import {cleanup,render,screen} from "@testing-library/react";import {TeacherRemediationDetailPage} from "./TeacherRemediationDetailPage";import * as api from "./remediationApi";
vi.mock("./remediationApi",async original=>({...await original<typeof import("./remediationApi")>(),getRemediation:vi.fn(),getRemediationResult:vi.fn(),cancelRemediation:vi.fn()}));const getPlan=vi.mocked(api.getRemediation),getResult=vi.mocked(api.getRemediationResult);
const plan=(status:string)=>({id:"r",student_id:"s",class_group_id:"c",source_assignment_id:"a",source_assignment_participant_id:"p",source_submission_id:"sub",source_check_run_id:"run",status,title:"Отработка",instructions:"Повторить",due_at:null,review_acknowledged_at:null,created_at:"x",updated_at:"x",assigned_at:null,cancelled_at:null,finding_ids:[],items:[{position:0,task_version_id:"v",selection_source:"suggested",title:"Задача",statement:"Условие",task_type:"problem",answer_format:"short_text",difficulty:10}]});
const result=(status:string)=>({remediation_id:"r",plan_status:"assigned",execution_status:status,student_id:"s",student_display_name:"Иван",submission_id:"sub",submission_status:"submitted",started_at:null,submitted_at:null,check_run_id:"run",check_run_status:status==="checking"?"pending":null,failure_code:null,suggested_score_total:7,max_score_total:10,suggested_percent:70,review_required_count:0,items:[]});
afterEach(()=>{cleanup();vi.clearAllMocks()});
describe("TeacherRemediationDetailPage C8/C9 result",()=>{
 it.each([["draft","черновик"],["assigned","назначена"],["cancelled","отменена"]])("renders %s plan read-only",async(status,label)=>{getPlan.mockResolvedValue(plan(status) as any);getResult.mockResolvedValue(result(status==="draft"?"not_started":status==="cancelled"?"cancelled":"in_progress") as any);render(<TeacherRemediationDetailPage id="r" navigate={vi.fn()}/>);expect(await screen.findByText(`Отработка: ${label}`)).toBeTruthy()});
 it.each(["not_started","in_progress","submitted","checking","checked","review_required","check_failed","expired","cancelled"])("renders execution state %s",async status=>{getPlan.mockResolvedValue(plan(status==="cancelled"?"cancelled":"assigned") as any);getResult.mockResolvedValue(result(status) as any);render(<TeacherRemediationDetailPage id="r" navigate={vi.fn()}/>);await screen.findByText("Иван");expect(screen.getByText(/Выполнение:/)).toBeTruthy()});
 it("renders teacher result and grouped bounded diagnostics without evidence",async()=>{getPlan.mockResolvedValue(plan("assigned") as any);getResult.mockResolvedValue({...result("checked"),items:[{remediation_plan_item_id:"i",position:0,task_version_id:"v",task_title:"Задача",task_statement:"Условие",student_raw_answer:{value:"42"},check_result:{check_result_id:"cr",result_status:"correct",checker_type:"ai",score_suggested:7,max_score:10,confidence:.9,summary:"Резюме",teacher_summary:"Комментарий учителю",needs_human_review:false,review_reason:null,model_limitations:null},findings:["skill","typical_error","rubric","general"].map((finding_type,i)=>({finding_id:String(i),finding_type,snapshot_title:["Дроби","Знак","Критерий","Общее"][i],snapshot_criterion:null,severity:"medium",confidence:.75,evidence:{secret:"RAW_EVIDENCE"}}))}]} as any);render(<TeacherRemediationDetailPage id="r" navigate={vi.fn()}/>);for(const text of ["Предварительный балл:","Резюме","Комментарий учителю","Навыки","Типичные ошибки","Критерии","Общие замечания"])expect((await screen.findAllByText(text,{exact:false})).length).toBeGreaterThan(0);expect(screen.getByText(/42/)).toBeTruthy();expect(document.body.textContent).not.toContain("RAW_EVIDENCE")});
});
