import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen} from "@testing-library/react";
import {TeacherAssignmentResultsPage} from "./TeacherAssignmentResultsPage";
import {getAssignmentResults} from "./classroomResultsApi";
vi.mock("./classroomResultsApi",async importOriginal=>({...await importOriginal<typeof import("./classroomResultsApi")>(),getAssignmentResults:vi.fn()}));
const get=vi.mocked(getAssignmentResults);
const row=(activity_status:string,check_status:string,latest_check_run_status:string|null=null,score:string|null=null)=>({assignment_participant_id:`p-${activity_status}-${check_status}`,student_id:`s-${activity_status}-${check_status}`,student_display_name:`Ученик ${activity_status} ${check_status}`,is_current_class_member:true,student_archived:false,activity_status,current_attempt_no:null,current_attempt_status:null,latest_submitted_attempt_no:null,latest_submitted_at:null,latest_check_run_status,check_status,suggested_score_total:score,max_score_total:"10",review_required_count:0,skill_finding_count:0,typical_error_finding_count:0});
afterEach(()=>{cleanup();vi.clearAllMocks()});
describe("TeacherAssignmentResultsPage C7 projection",()=>{
 it("renders every activity/check state, preliminary and null scores",async()=>{get.mockResolvedValue({assignment_id:"a",assessment_id:"x",assessment_title:"Работа",class_group_id:"c",class_group_name:"8А",assignment_status:"active",start_at:null,due_at:null,participant_count:8,not_started_count:1,in_progress_count:1,submitted_count:1,checking_count:2,checked_count:1,review_required_count:1,check_failed_count:1,items:[row("not_started","not_submitted"),row("in_progress","not_submitted"),row("submitted","submitted"),row("submitted","checking","pending"),row("submitted","checking","running"),row("submitted","checked",null,"7"),row("submitted","review_required",null,"6"),row("submitted","check_failed","failed_terminal")] as any});render(<TeacherAssignmentResultsPage classId="c" assignmentId="a" navigate={vi.fn()}/>);await screen.findByText("Работа");for(const text of ["Не начинал","Выполняет","Сдано","В очереди на проверку","Проверяется","Проверено","Нужна проверка учителя","Ошибка проверки"])expect(screen.getAllByText(text).length).toBeGreaterThan(0);expect(screen.getByText("Предварительный балл")).toBeTruthy();expect(screen.queryByText("Итоговая оценка")).toBeNull();expect(screen.getAllByText("—").length).toBeGreaterThan(0);expect(screen.queryByText(/^0 \/ 10$/)).toBeNull()});
 it("shows historical badges without destination and trusts latest failed projection",async()=>{get.mockResolvedValue({assignment_id:"a",assessment_id:"x",assessment_title:"Работа",class_group_id:"c",class_group_name:"8А",assignment_status:"active",start_at:null,due_at:null,participant_count:1,not_started_count:0,in_progress_count:0,submitted_count:1,checking_count:0,checked_count:0,review_required_count:0,check_failed_count:1,items:[{...row("submitted","check_failed","failed_terminal",null),is_current_class_member:false,student_archived:true,student_display_name:"Иван"}]} as any);render(<TeacherAssignmentResultsPage classId="c" assignmentId="a" navigate={vi.fn()}/>);await screen.findByText("Переведён");expect(screen.getByText("Архив")).toBeTruthy();expect(screen.getByText("Ошибка проверки")).toBeTruthy();expect(screen.queryByText(/9 \/ 10/)).toBeNull();expect(document.body.textContent).not.toContain("destination")});
});
